cmd/cli/upload.go
test/e2e_test.go

I was getting a `no such file or directory` error when passing in the raw base64 encoded signature via command line arg as shown https://github.com/sigstore/cosign#upload-a-generated-signature. It's because the error signals to interpret the argument as a raw base64 encoded signature instead of a file or `stdin`. So this clears the error to avoid inadvertently returning an error and exiting the program.

Update to prevent error for base64 encoded signature passed in via arg

---

README.md

Signed-off-by: Luke Hinds <lhinds@redhat.com>

Add missing https prefix to fix link

---

cmd/cli/verify.go
pkg/cosign/tlog/upload.go
pkg/cosign/tlog/verify.go
test/e2e_test.go

Add some logic to detect the case when a signature already exists.

---

README.md

Add TLOG details to README

---

README.md

Add permanent link to slack invite.

---

pkg/cosign/kms/gcp/gcp.go
pkg/cosign/kms/gcp/gcp_test.go
pkg/cosign/kms/kms.go

* moved gcp/ into its own package
* use regexp for parsing kms resource reference
* added unit test for parsing
/cc @priyawadhwa

polish kms reference parsing

---

README.md
test/e2e_test.sh

* enabled 'set -ex' in e2etest (was ignoring failing cmd)
* updated install instructions
Closes #79.

fix build path in test/docs

---

cmd/cosign/cli/sign.go
cmd/cosign/cli/verify.go
pkg/cosign/upload.go
test/e2e_test.go

Simplify the experimental env var handling.

---

test/e2e_test.go
test/e2e_test.sh

test: put e2e tests behind a build tag

---

pkg/cosign/fetch.go

The signature that was being saved didn't include the certificate&chain so this wasn't working with fulcio 😓 
fixes bug from #63

Fix bug introduced by parallelization

---

cmd/cosign/cli/generate_key_pair.go
pkg/cosign/kms/gcp/gcp.go
pkg/cosign/kms/kms.go

Add the public key from KMS

---

README.md

Based on: https://github.com/sigstore/cosign/issues/40#issuecomment-802971435
Signed-off-by: Luke Hinds <lhinds@redhat.com>

Add Jfrog Artifactory

---

.github/dependabot.yml

Feat- Enable dependabot settings

---

.github/workflows/build.yaml
.gitignore
Makefile

Add cross target to makefile.

---

.github/workflows/build.yaml
Makefile

Publish containers as part of the build.

---

.github/workflows/build.yaml
cmd/cosign/cli/sign_blob.go

I think this should fix #142 
I need to stop procrastinating and figure out how to get testing for the oauth flow setup ASAP. #88 
Does anyone know a a good way to use secrets in github actions during PR reviews?

Fix the empty key error in keyless sign-blob.

---

cmd/cosign/cli/generate_key_pair.go
test/e2e_test.go

It's pretty much impossible to pass in a PW through a Github action any other way.

Add a COSIGN_PASSWORD environment variable.

---

cmd/cosign/cli/generate_key_pair.go
cmd/cosign/cli/generate_key_pair_test.go

distinguish COSIGN_PASSWORD empty vs unset

---

pkg/cosign/fulcio/fulcio.go

Add copyright statement

---

pkg/cosign/fulcio/fulcio.go
pkg/cosign/fulcio/fulcio_test.go

add some unit testing for the OIDC token flow

---

README.md

cosign has now been tested with distribution!

Add distribution/distribution to the list!

---

FUN.md

Signed-off-by: Mark Bestavros <mbestavr@redhat.com>

Correct experimental feature flag in FUN.md

---

go.mod
go.sum
pkg/cosign/fulcio/fulcio.go

New fulcio server.

---

README.md

Add OCI artifacts/oras to docs!

---

README.md

Add GitHub Container Registry to the docs!

---

README.md

They have an awesome public demo server setup at demo.goharbor.io. This made
testing super easy!
Ref #40

Add CNCF Harbor support to the list!

---

README.md

Lucky number 10! There are more of these than I thought.

Add the Digital Ocean container registry!

---

.github/workflows/build.yaml
Makefile

Update the build scripts to use our github action instead of the version we just built here.

Prep for v0.2.0

---

CHANGELOG.md

Add v0.2.0 CHANGELOG.

---

FUN.md

Fix hard-mode verification step in FUN.md

---

pkg/cosign/upload.go

Signed-off-by: Dentrax <furkan.turkal@hotmail.com>

better experimental flag handling

---

cmd/cosign/cli/verify.go

output in JSON by default and add a flag to disable this option and output in "plain text""
examples:
JSON:
```console
$ ./cosign verify -key test-cosing-pub.pub xoph/cosigntest:doublesigned
Verification for xoph/cosigntest:doublesigned --
- The signatures were verified against the specified public key
[{"Critical":{"Identity":{"docker-reference":""},"Image":{"Docker-manifest-digest":"sha256:2f6d89c49ad745bfd5d997f9b2d253329323da4c500c7fe343e068c0382b8df4"},"Type":"cosign container signature"},"Optional":null},{"Critical":{"Identity":{"docker-reference":""},"Image":{"Docker-manifest-digest":"sha256:2f6d89c49ad745bfd5d997f9b2d25332932 …
```

cosign/verify: output JSON for the signing information

---

KEYLESS.md
cmd/cosign/cli/sign.go
cmd/cosign/cli/sign_blob.go
go.sum
pkg/cosign/fulcio/fulcio.go

Device mode for CI signatures

---

cmd/cosign/cli/generate.go
cmd/cosign/cli/sign.go
cmd/cosign/cli/sign_blob.go
cmd/cosign/cli/upload.go
cmd/cosign/cli/verify.go
go.mod
go.sum
pkg/cosign/kms/gcp/gcp.go
pkg/cosign/verify.go
test/e2e_test.go

update `sigstore/sigstore` dependency

---

README.md

Document the release container location.

---

.github/workflows/e2e_tests.yml

Add the dependency for our post-build e2e runs.

---

.github/workflows/tests.yaml

Followup from this discussion https://github.com/sigstore/cosign/pull/230#discussion_r610770964
sorry about that, my fault
/assign @ahmetb

ci/boilerplate: fix bolierplate check

---

cmd/cosign/cli/sign.go
cmd/cosign/cli/sign_blob.go
pkg/cosign/fulcio/fulcio.go

Refactor to use the signer interface more.

---

Makefile

Add CGO for the cross builds.

---

pkg/cosign/fulcio/fulcio.go

Switch the fulcio hostname back.

---

README.md

Update the intro to the docs with more features!

---

cmd/cosign/cli/flags.go
cmd/cosign/cli/flags_test.go
cmd/cosign/cli/public_key.go
cmd/cosign/cli/sign.go
cmd/cosign/cli/sign_blob.go
cmd/cosign/cli/verify.go

This gets more important with yubikeys.

Add a one of function for command line parsing.

---

.github/workflows/build.yaml
.github/workflows/cross.yaml

Switch the CI builds to use OSX machines for mac builds and linux machines for linux builds.

---

cmd/cosign/cli/verify_blob.go

One more interface refactor to make security keys easier.

---

.github/workflows/cross.yaml

Fix a typo in the cross script.

---

KEYLESS.md
TOKENS.md

- Add YubiKey 4 Series to the tested token.md
as discussed in the slack thread: https://sigstore.slack.com/archives/C01DGF0G8U9/p1618152631017700?thread_ts=1617978837.007000&cid=C01DGF0G8U9

Add YubiKey 4 Series to the tested token.md

---

CODEOWNERS

Signed-off-by: Luke Hinds <lhinds@redhat.com>

Implement codeowners

---

test/e2e_test_secrets.sh

Fix e2e/kms test.

---

cmd/cosign/main.go

This is helpful for running cosign within a container when you do not have access to a shell to redirect output to a file. For example, using the cosign container within CI systems e.g. as a task in Tekton, makes redirecting all output to a file very useful for easier post-processing to analyze the results.

Add flag to log all output to a file

---

CHANGELOG.md
RELEASES.md

Adds docs on release cutting info. 

[docs] Add info on how to cut a release

---

.github/workflows/cross.yaml

update cross.yaml to output binaries with version info

---

CHANGELOG.md

Add 0.3.1 release notes

---

TOKENS.md

Improve the getting started docs for signing with tokens.

---

cmd/cosign/cli/keys.go
cmd/cosign/cli/sign.go
cmd/cosign/cli/sign_blob.go
cmd/cosign/cli/upload.go
cmd/cosign/cli/verify_blob.go
pkg/cosign/pivkey/pivkey.go
pkg/cosign/remote.go
pkg/cosign/upload.go
pkg/cosign/verify.go
test/e2e_test.go

Dedupe signature uploads

---

go.mod
go.sum
pkg/cosign/verify.go

Update rekor to pick up new API changes.

---

CHANGELOG.md
SPEC.md
pkg/cosign/fetch.go
pkg/cosign/upload_test.go
test/e2e_test.go

`.cosign` -> `.sig`

---

.github/workflows/cross.yaml

Signed-off-by: Christian Pearce <christian@pearcec.com>

Rename windows executable with .exe extension

---

cmd/cosign/cli/verify.go

fixes https://github.com/sigstore/cosign/issues/291

Add bundle to JSON output

---

pkg/cosign/keys.go

Make pemType public for chains

---

CHANGELOG.md

Add commit notes for v0.4.0

---

pkg/cosign/remote.go

fix COSIGN_DOCKER_MEDIA_TYPES

---

.github/workflows/build.yaml
.github/workflows/e2e_tests.yml
.github/workflows/tests.yaml
KEYLESS.md
KMS.md
README.md
RELEASES.md
SPEC.md
TOKENS.md
USAGE.md
cmd/cosign/cli/sign.go

Channeling @jonjohnsonjr for great power

numerous minor fixes

---

README.md
cmd/cosign/cli/sign.go

add docs for COSIGN_DOCKER_MEDIA_TYPES var

---

.github/workflows/cross.yaml
Makefile
cmd/cosign/cli/pivcli/commands.go
cmd/cosign/cli/pivcli/disabled.go
cmd/cosign/cli/pivcli/piv_tool.go
pkg/cosign/pivkey/disabled.go
pkg/cosign/pivkey/pivkey.go

add `make cosign-static` target, use in CI `cross` for linux

---

cmd/cosign/cli/copy.go
test/e2e_test_secrets.sh

fix `copy` and associated e2e test

---

cmd/cosign/cli/sign_blob.go

I noticed this with asraa@ when testing some security key signing.

Fix log index printing output.

---

README.md
pkg/cosign/upload.go
pkg/cosign/verify.go
test/e2e_test.go

Signed-off-by: Bob Callaway <bob.callaway@gmail.com>

change to rekor.sigstore.dev

---

.gitignore
README.md
cmd/cosign/cli/sign.go
cmd/cosign/cli/upload.go
cmd/cosign/cli/upload_blob.go
cmd/cosign/cli/verify.go
cmd/cosign/main.go
cmd/sget/cli/sget.go
cmd/sget/main.go
pkg/cosign/fetch.go
pkg/cosign/remote/index.go
pkg/cosign/remote/remote.go
pkg/cosign/upload.go
test/e2e_test.go

Add an upload-blob subcommand and new sget client.

---

cmd/sget/main.go

We want to ensure the digest matches before we emit anything to stdout
to avoid e.g. piping malicious payloads to bash prior to validation.

Buffer output before writing to stdout

---

.github/workflows/build.yaml
.github/workflows/cross.yaml
.github/workflows/e2e_tests.yml
.github/workflows/tests.yaml

bump go version to 1.16.4

---

cmd/cosign/cli/upload_blob.go
cmd/cosign/cli/upload_blob_test.go
cmd/sget/main.go
test/e2e_test_secrets.sh

Add some more tests/fix bugs in sget/upload-blob

---

KEYLESS.md
cmd/cosign/cli/verify.go
cmd/cosign/cli/verify_blob.go

Use the SAN for verification instead of Common Names.

---

KEYLESS.md
cmd/cosign/cli/sign.go
cmd/cosign/cli/sign_blob.go
go.mod
go.sum
pkg/cosign/fulcio/fulcio.go
pkg/cosign/fulcio/fulcio_test.go
test/e2e_test.go

Support OIDC ID Tokens on the command line.

---

cmd/cosign/cli/sign.go
cmd/cosign/cli/sign_blob.go
cmd/cosign/cli/util.go
cmd/cosign/cli/verify.go
cmd/cosign/cli/verify_blob.go
cmd/sget/cli/sget.go
copasetic/main.go
pkg/cosign/upload.go
pkg/cosign/verify.go
test/e2e_test.go

move env vars out of `pkg`

---

go.mod
go.sum
pkg/cosign/fulcio/fulcio.go

This contains the recent vault fixes and support for SPIFFE IDs

Update sigstore/sigstore library.

---

EXAMPLES.md

Alter GCP KMS example to differentiate it from the standard flow

---

test/e2e_test_secrets.sh

temporarily disable `sget` e2e tests

---

pkg/cosign/kubernetes/secret.go
pkg/cosign/kubernetes/secret_test.go

Allow updating an existing k8s secret in addition to creating a new one.

---

test/e2e_test_secrets.sh

fix `sget` e2e test

---

test/e2e_test_secrets.sh

leverage env vars more in e2e tests, allow for other KMS keys to be used

---

.github/workflows/build.yaml
.github/workflows/cross.yaml
.github/workflows/e2e_tests.yml
.github/workflows/tests.yaml

update to go 1.16.5

---

.github/workflows/build.yaml

update CI cosign to v0.5.0

---

.github/workflows/build.yaml
.github/workflows/tests.yaml
Makefile

incremental updates to utilities required in our github actions

---

CHANGELOG.md

add v0.5.0 release notes

---

README.md

Document how to sign Tekton Bundles in cosign.

---

cmd/cosign/cli/download.go
copasetic/main.go
pkg/cosign/fetch.go
pkg/cosign/verify.go
test/e2e_test.go

refactor `FetchSignatures`

---

cmd/cosign/cli/attach/sig.go
cmd/cosign/cli/clean.go
cmd/cosign/cli/copy.go
cmd/cosign/cli/sign.go
cmd/cosign/cli/triangulate.go
pkg/cosign/fetch.go
test/e2e_test.go

Start preparing for multiple attachment types.

---

cmd/cosign/cli/verify_dockerfile.go
cmd/cosign/cli/verify_dockerfile_test.go
test/e2e_test.sh

add more tests and documentation for `verify-dockerfile`

---

TOKENS.md

update tokens doc page

---

README.md

fix for sub-command upload-blob in README.md

---

go.mod
go.sum

Bump sigstore one more time for passing GCP tests.

---

cmd/cosign/cli/keys.go
cmd/cosign/cli/public_key.go
cmd/cosign/cli/sign.go
cmd/cosign/cli/sign_blob.go
cmd/cosign/cli/verify.go
cmd/cosign/cli/verify_blob.go
cmd/sget/cli/sget.go
copasetic/main.go
pkg/cosign/keys.go
pkg/cosign/pivkey/disabled.go
pkg/cosign/verify.go

Plumb context options through `pkg` utilities

---

cmd/cosign/cli/sign.go
cmd/cosign/cli/sign_blob.go

`Sign` -> `SignMessage`

---

cmd/cosign/cli/keys.go
cmd/cosign/cli/verify.go
cmd/cosign/cli/verify_blob.go
cmd/sget/cli/sget.go
copasetic/main.go
pkg/cosign/keys.go
pkg/cosign/pivkey/disabled.go
pkg/cosign/verify.go

remove obsolete TransparentVerifier interface

---

cmd/cosign/cli/attach/sbom.go
cmd/cosign/cli/attach/sig.go
cmd/cosign/cli/clean.go
cmd/cosign/cli/sign.go
cmd/cosign/cli/triangulate.go
cmd/cosign/cli/upload/blob.go
cmd/cosign/cli/upload/wasm.go
pkg/cosign/remote/index.go
pkg/cosign/remote/remote.go

plumb through more contexts for registry operations

---

go.mod
go.sum

Bump sigstore for an OIDC fix.

---

pkg/cosign/pivkey/pivkey.go

Move the piv tool to use the new sigstore interfaces.

---

.goreleaser.yml
Makefile
release/README.md
release/cloudbuild.yaml
release/release-cosign.pub

Use GCP KMS to sign the blobs and the image

use gcp kms to sign the release

---

CHANGELOG.md

add v0.6.0 relnotes

---

.github/workflows/build.yaml
.github/workflows/cross.yaml
.github/workflows/e2e_tests.yml
.github/workflows/tests.yaml
Dockerfile

update workflows (other than release) to go 1.16.6

---

go.mod
go.sum

update deps, run `go mod tidy`

---

Dockerfile
Makefile
release/cloudbuild.yaml

make base image an arg, use distroless/static for releases

---

README.md

Update the readme a bit.

---

cmd/cosign/cli/sign.go
cmd/cosign/cli/sign_blob.go

Remove duplication between sign and sign-blob.

Refactor the way certs are handled.

---

cmd/cosign/cli/attach/sbom.go
cmd/cosign/cli/attach/sig.go
cmd/cosign/cli/clean.go
cmd/cosign/cli/copy.go
cmd/cosign/cli/download/sbom.go
cmd/cosign/cli/download/signature.go
cmd/cosign/cli/sign.go
cmd/cosign/cli/triangulate.go
cmd/cosign/cli/upload/blob.go
cmd/cosign/cli/upload/wasm.go
cmd/cosign/cli/util.go
cmd/cosign/cli/verify.go
cmd/sget/cli/sget.go
copasetic/main.go
pkg/cosign/fetch.go
pkg/cosign/verify.go
test/e2e_test.go

refactor attached image code

---

USAGE.md

add additional KMS use cases of cosign

---

cmd/cosign/cli/util.go

Signed-off-by: Appu Goundan <appu@google.com>
fixes #478

Add cosign/ to useragent for remote calls

---

cmd/cosign/cli/sign.go
go.mod
go.sum
pkg/cosign/fulcio/fulcio.go

use Fulcio's client creation utility

---

README.md

Update the docs to be explicit around 1.0!

---

CHANGELOG.md

v1.0.0 relnotes

---

.goreleaser.yml

Allow multiple files per archive.

---

README.md

Cosign is 1.0!

---

.github/workflows/build.yaml
README.md

use cosign v1.0.0

---

specs/SBOM_SPEC.md

SBOM specification!

---

specs/SBOM_SPEC.md

fixing typos in the documentation of SBOM specification

---

specs/SIGNATURE_SPEC.md

SIGNATURE_SPEC.md: fix typo

---

go.mod
go.sum

Help out dependabot and obsolete https://github.com/sigstore/cosign/pull/529

update go mods, tidy

---

.github/workflows/e2e_tests.yml

This was added in #537 and shouldn't have been.
@dlorenc

Don't run e2e tests on PRs

---

EXAMPLES.md

Add example of openssl signing.

---

cmd/cosign/cli/attest.go

this way, we can use cosign to upload attestations in chains! 
ref https://github.com/tektoncd/chains/issues/203

Make payload types public

---

CODEOWNERS

Signed-off-by: Hector Fernandez <hectorf@vmware.com>
Add new CODEOWNER for cosign to help maintaining the repository.

chore: add a new CODEOWNER

---

cmd/cosign/cli/attest.go

Set the correct predicate type/URI for each supported predicate type.

---

go.mod
go.sum

Bump go/storage.

---

Makefile

Resolves https://github.com/sigstore/cosign/issues/620
Signed-off-by: Pradeep Chhetri <pradeepchhetri4444@gmail.com>

Modify golangci-lint installation

---

cmd/cosign/cli/triangulate.go
pkg/cosign/fetch.go

Signed-off-by: Sambhav Kothari <sambhavs.email@gmail.com>

Add sbom and attestation to triangulate

---

.github/workflows/build.yaml
Makefile

Add ko targets for the webhook image.

---

.github/workflows/build.yaml
Makefile

Fix signing for the cosigned image.

---

.ko.yaml

Use a nonroot base image for ko-based images

---

release/cloudbuild.yaml

Switch the release cosign container to debug.

---

cmd/cosign/cli/attest.go
cmd/cosign/cli/clean.go
cmd/cosign/cli/download/sbom.go
cmd/cosign/cli/download/signature.go
cmd/cosign/cli/fulcio/fulcio.go
cmd/cosign/cli/generate.go
cmd/cosign/cli/pivcli/commands.go
cmd/cosign/cli/pivcli/piv_tool.go
cmd/cosign/cli/public_key.go
cmd/cosign/cli/sign.go
cmd/cosign/cli/sign_blob.go
cmd/cosign/cli/triangulate.go
cmd/cosign/cli/upload/blob.go
cmd/cosign/cli/verify.go
cmd/cosign/cli/version.go
cmd/cosign/main.go
cmd/sget/main.go
copasetic/main.go
pkg/cosign/tlog.go

Revert "Consistently use STDERR for output."

---

FUN.md
README.md
cmd/cosign/cli/attest.go
cmd/cosign/cli/sign.go

I noticed this and it bothered me. 🔬

Remove unnecessary space after 'with index:'

---

CHANGELOG.md
release/README.md

ref https://github.com/sigstore/cosign/issues/654

CHANGELOG for cosign 1.2

---

.goreleaser.yml
Dockerfile
Dockerfile.cosigned
Makefile
cmd/cosign/cli/pivcli/commands.go
cmd/cosign/cli/pivcli/piv_tool.go
release/cloudbuild.yaml

build/sign container images for cosign/cosigned using goreleaser
Also we build for Linux arm64 binaries and images and publish the docker manifest :)

build/sign container images for cosign/cosigned using goreleaser

---

.github/workflows/build.yaml
.github/workflows/cross.yaml
.github/workflows/e2e_tests.yml
.github/workflows/tests.yaml

update github actions to track the latest Go patch releases

---

pkg/cosign/fetch.go

Knative has a `pool` package that implements the `errgroup` interface, so it is a trivial simplication here.
N/A
```release-note
NONE
```

Take advantage of Knative's threadpool

---

go.mod

organize direct and transitive deps into their dedicated `require` directives

---

.github/workflows/kind-e2e-cosigned.yaml
test/e2e_test_insecure_registry.sh

Follow-up to https://github.com/sigstore/cosign/pull/669

add e2e tests for `-allow-insecure-registry` flag

---

cmd/sget/cli/commands.go
cmd/sget/cli/options/root.go
go.mod
pkg/sget/sget.go
test/e2e_test.go

Migrate `sget` to cobra. No functional change.
References https://github.com/sigstore/cosign/issues/706
```release-note
None.
```

Migrate sget to cobra.

---

copasetic/main.go

add -allow-insecure-registry flag to copasetic

---

cmd/cosign/cli/verify.go

GitHub certificates in Fulcio use the URIs field, while others use email.
Let's add both to the output formatting.
Fixes
```release-note
```

Add the URIs subject to our outputting.

---

CHANGELOG.md

add changelog for v1.2.1
this will be cherry-picked to the main branch after
n/a
```release-note
NONE
```

add changelog for v1.2.1

---

cmd/cosign/cli/attach/sig.go
cmd/cosign/cli/attest.go
cmd/cosign/cli/sign/sign.go
pkg/cosign/remote/remote.go

This is discarded as every call site, so we might as well not return it.
```release-note
NONE
```

Drop unused return value.

---

go.mod
go.sum

Still don't know why dependabot can't do this. Replaces #690.
Fixes
```release-note
```

Bump googleapis to 0.57.0.

---

pkg/cosign/remote/remote.go

This doesn't seem to be used anywhere, so clean it up.
```release-note
NONE
```

Drop unused method.

---

go.mod
go.sum

Poor dependabot. Replaces #744.
Fixes
```release-note
```

Bump opa to v0.32.1.

---

cmd/cosign/cli/sign/sign.go

My previous change made this dead, so clean it up.
N/A
```release-note
NONE
```

Drop this bit of dead code.

---

cmd/cosign/cli/attest.go
cmd/cosign/cli/sign/sign.go

There was a large chunk of code in sign/attest that was *largely* the same, and one instance was already leaning on the other for various utilities.  This change shares all of the common elements of this large chunk that were common with one small callback for handling the difference.
I'd have liked to have put this new helper into `cosign` alongside some of the other utilities, but it seems this would create a dependency cycle.
```release-note
NONE
```

Share more of the tlog upload logic.

---

cmd/cosign/cli/commands.go
cmd/cosign/cli/options/fulcio.go
cmd/cosign/cli/options/oidc.go
cmd/cosign/cli/options/rekor.go
cmd/cosign/cli/options/securitykey.go
cmd/cosign/cli/options/sign.go
cmd/cosign/cli/options/signblob.go
cmd/cosign/cli/sign.go
cmd/cosign/cli/sign/sign_blob.go
cmd/cosign/cli/signblob.go
cmd/cosign/main.go

Migrate `cosign sign-blob` to cobra.
```release-note
NONE
```

Migrate cosign sign-blob to cobra.

---

cmd/cosign/cli/commands.go
cmd/cosign/cli/options/fulcio.go
cmd/cosign/cli/options/public_key.go
cmd/cosign/cli/options/rekor.go
cmd/cosign/cli/options/security_key.go
cmd/cosign/cli/options/sign.go
cmd/cosign/cli/options/signblob.go
cmd/cosign/cli/public_key.go
cmd/cosign/cli/sign.go
cmd/cosign/cli/signblob.go
cmd/cosign/main.go

Migrate `cosign public-key` to cobra.
```release-note
NONE
```

Migrate cosign public-key to cobra.

---

cmd/cosign/cli/attest.go

This is very similar to the change to `sign`, but for `attest`.
Related: #666
```release-note
NONE
```

Switch `attest` to use `remote.WriteSignatures`.

---

pkg/cosign/verify.go

Rather than having every. single. error path in the loop over signatures do:
```go
if err != nil {
validationErrors = append(validationErrors, err.Error())
continue
}
```
This wraps the body of the loop in:
```go
if err := func(sig oci.Signature) error {
...
}(sig); err != nil {
validationErrors = append(validationErrors, err.Error())
continue
}
```
So that the paths within the body can now just `return err`.
There were enough paths here that this reduction seemed meaningful.
N/A
```release-note
NONE
```

Refactor the signature loop to reduce boilerplate.

---

pkg/oci/signatures.go

This has been addressed as part of the march towards #666, but never got cleaned up.
N/A
```release-note
NONE
```

Drop a stale TODO.

---

cmd/cosign/cli/upload/wasm.go

Remote err nil check before return

---

cmd/cosign/cli/upload/blob.go

Use `ref.Context().Digest()` to make digest.

---

README.md

Signed-off-by: Ville Aikas <vaikas@gmail.com>
Add a short note about cosigned webhook and a pointer to cosigned helm charts which contain the installation / configuration options.
Fixes
```release-note
```

add blurp / pointer to cosigned

---

.github/workflows/codeql-analysis.yml

fix codeql-action

---

README.md

correct docs for `go install`

---

go.mod
go.sum
pkg/cosign/verifiers.go

Switches from using `github.com/in-toto/in-toto-golang/pkg/ssl` to `github.com/secure-systems-lab/go-securesystemslib/dsse`.
N/A.
See: https://github.com/in-toto/in-toto-golang/pull/122
```release-note
Uses new provider for DSSE.
```

Switch DSSE provider to go-securesystemslib

---

cmd/cosign/cli/commands.go
cmd/cosign/cli/options/piv_tool.go
cmd/cosign/cli/piv_tool.go
cmd/cosign/cli/piv_tool_disabled.go
cmd/cosign/cli/pivcli/commands.go
cmd/cosign/cli/pivcli/piv_tool.go
cmd/cosign/main.go

- migrate `cosign piv-tool ...` to cobra.
```release-note
NONE
```

Migrate piv-tool tree to cobra

---

cmd/cosign/cli/options/predicate.go

Fixes
```release-note
* Bug fix: fixes --type flag for `cosign attest`
```
Previous behavior:
```
./cosign attest --predicate example.txt --key cosign.key --type custom gcr.io/asra-ali/busybox/demo
Error: signing gcr.io/asra-ali/busybox/demo: invalid predicate type: 
```
Now:
```
$ ./cosign attest --predicate example.txt --key cosign.key --type custom gcr.io/asra-ali/busybox/demo
Enter password for private key: Using payload from: example.txt
```

Fix `cosign attest` flags for `type`.

---

cmd/cosign/cli/commands.go
cmd/cosign/cli/completion.go

Co-authored-by: Erkan Zileli <erkan.zileli@trendyol.com>
add auto-completion support
Fixes #475 
```release-note
* Add new command for supporting auto-completion
```
cc: @dentrax @erkanzileli

feat: auto-completion support

---

doc/cosign.md
doc/cosign_attest.md
doc/cosign_completion.md

Some CLI changes were introduced since #839 was opened, caught in CI. 🎉 
```release-note
NONE
```

Generate docs for new CLI surfaces

---

.github/workflows/build.yaml

upgrade google/ko version in GitHub Action, get it from an environment variable
Fixes
```release-note
chore: upgrade google/ko version in GitHub Action, get it from an environment variable
```

chore: KO_VERSION as environment var

---

cmd/cosign/cli/policy_init.go

Signed-off-by: Luke Hinds <luke@redhat.com>

Error with the filename provided

---

cmd/cosign/cli/options/errors.go
cmd/cosign/cli/verify/verify_blob.go

verify-blob takes one of pubkey, cert or sk
Fixes #676

Fix verify-blob error message (#676)

---

pkg/cosign/git/github/github.go
pkg/cosign/git/gitlab/gitlab.go

We should store the public key also within GitHub/GitLab variable because we'll be verifying signatures based on them with the `verify` command with another scheme support such as "github:// or gitlab://".
Fixes
```release-note
feat: store public key within GitHub/GitLab variable
```
cc: @hectorj2f

feat: store public key within GitHub/GitLab variable

---

.github/workflows/build.yaml

Fix the KO_VERSION variable in the post-merge container build.

---

go.mod
go.sum

Dependabot still seems broken, one day we'll fix it!
Ref #898 #892 #879 #876
Fixes
```release-note
```

Bump dependencies and tidy.

---

pkg/cosign/kubernetes/webhook/validation.go

fix: Fixed multiple public keys issue

---

go.mod
go.sum

Replaces https://github.com/sigstore/cosign/pull/969 and https://github.com/sigstore/cosign/pull/961
Fixes
```release-note
```

Bump google.golang.org/api and github.com/go-openapi/strfmt.

---

CODEOWNERS

Adds me as a maintainer, cc: @dlorenc 
N/A
```release-note
```

Add luhring to codeowners

---

go.mod
go.sum

Replaces #976 and #977.
Fixes
```release-note
```

Bump opa and apis.

---

.github/workflows/build.yaml
.github/workflows/github-oidc.yaml
release/cloudbuild.yaml

update automation to use 1.3.0 release

---

go.mod
go.sum

This fixes #589 finally!
Fixes
```release-note
```

Bump sigstore/sigstore to pickup a fix for azure kms.

---

README.md

Ref #423 
Fixes
```release-note
```

Add an initial comparison document between nv2 and cosign.

---

go.mod
go.sum

Replaces #1007 
Fixes
```release-note
```

Bump the thales pkcs11 library to v1.2.5

---

CHANGELOG.md

Signed-off-by: Carlos Panato <ctadeu@gmail.com>
add changelog for v1.3.1
Fixes
```release-note
add changelog for v1.3.1
```

add changelog for v1.3.1

---

CHANGELOG.md

add change to 1.3.1 changelog

---

release/cloudbuild.yaml

- release: update cosign to 1.3.1 in cloudbuild
n/a
```release-note
release: update cosign to 1.3.1
```

release: update cosign to 1.3.1

---

README.md

https://github.com/sigstore/sigstore-website/pull/73 documented install
methods so now the README is out of date. Lets just link to the install
docs.
Closes #467
Signed-off-by: Brandon Philips <brandon@ifup.org>
[Fixes
](https://github.com/sigstore/cosign/issues/467)
```release-note
* README: Link to the install docs instead of copy pasting
```

README: simplify the install section

---

cmd/cosign/cli/policy_init.go

* Fixes root path name: apparently ghcr doesn't like the `.` in `root.json`, so moving to a fixed name of `root` works
Fixes
```release-note
```

policy: fix root path name

---

go.sum

- sync go mod
n/a
```release-note
NONE
```

sync go mod

---

go.mod
go.sum

This bumps opa, go-gitlab, and k8s.io/api
Replaces #1075 #1057 #1034
Fixes
```release-note
```

Bump some deps that dependabot missed.

---

cmd/cosign/cli/attest/attest.go
cmd/cosign/cli/sign/sign.go

/cc #844 and #931
```release-note
NONE
```

refactoring signature logic

---

.goreleaser.yml

Signed-off-by: Engin Diri <engin.diri@mail.schwarz>
Hello cosign community and @cpanato,
I added GoFish support via goreleasers (@caarlos0). The only things we need before merging this PR:
A github repo called: fish-food  similar to https://github.com/goreleaser/fish-food and and ensure access to it during the release process.
```yaml
owner: sigstore
name: fish-food
```
Fixes #855 
NONE
```release-note
```

feat(ci): Add Gofish support

---

cmd/cosign/cli/attest/attest.go
cmd/cosign/cli/sign/sign.go

minor: supply `ShouldUploadToTlog` with context

---

.goreleaser.yml
go.sum
release/README.md
release/cloudbuild.yaml

- add the keyless to the binaries and also send the data to tlog, after all the work made here https://github.com/sigstore/cosign/pull/1081 / https://github.com/sigstore/rekor/pull/501 thanks @asraa 
- update the release docs and now because we have the
```
gomod:
proxy: true
```
in the Goreleaser for the build reproducibility  we need to have the tag in place in the repository before running the release
rehearsal: https://github.com/cpanato/cosign/releases/tag/v99.999.03
verify binary with the keyless sig
```console
$ COSIGN_EXPERIMENTAL=true ./cosign-darwin-amd64 verify-blob --signature cosign-darwin-amd64-keyless.sig cosign-darwin-amd64
Certificate is trusted by Fulcio Root CA
Email: [keyless@cpanato-general.iam.gserviceaccount.com]
Issuer:  https://accounts.google.com
Verified OK
tlog …
```

add keyless to the binaries and send to tlog and update release docs

---

cmd/cosign/cli/sign/sign.go
internal/pkg/cosign/rekor/rekor.go

Ticket Link: #844
```release-note
NONE
```

have `rekor.NewSigner` accept a `*client.Rekor` instead of a URL

---

.github/workflows/tests.yaml

Co-authored-by: Doğukan Tuna <dogukan.tuna@trendyol.com>
Co-authored-by: Mert Bilgiç <mert.bilgic@trendyol.com>
Co-authored-by: Mehmet Mallı <mehmet.malli@trendyol.com>
remove unnecessary git command in the check license headers step in the GitHub workflow.
Fixes #1125 
```release-note
feat: enable --check flag of addlicense
```

feat: enable --check flag of addlicense

---

CHANGELOG.md

add relnotes for v1.4.0

---

.github/workflows/e2e-with-binary.yml

#1153
```release-note
NONE
```

re-enable windows in e2e-with-binary, fix issues

---

test/e2e_test_secrets.sh

This'll help avoid random failures due to PRs and merges competing for the same repo. Needed by https://github.com/sigstore/cosign/pull/1166
```release-note
NONE
```

use a different repo for each e2e test against the registry

---

.github/workflows/e2e_tests.yml
test/e2e_test_secrets.sh

https://github.com/sigstore/cosign/issues/1153
```release-note
NONE
```

enable e2e-test coverage for Win & OSX

---

test/e2e_test_secrets.sh

#1153
```release-note
NONE
```

add test for interactive private key password prompt

---

test/e2e_test_secrets.sh

add tests for `cosign initialize`

---

pkg/cosign/tuf/repository/snapshot.json
pkg/cosign/tuf/repository/timestamp.json

* Updates the embedded metadata, this will also fix the unwrite-able cache problem because it won't want to update the cache.
Fixes https://github.com/sigstore/cosign/issues/1207
```release-note
```

Update TUF snapshot and timestamp

---

internal/pkg/cosign/fulcio/fulcio.go
internal/pkg/cosign/rekor/rekor.go

https://github.com/sigstore/cosign/issues/844
```release-note
NONE
```

use `mutate.Signature` in the new `Signer`s

---

internal/pkg/cosign/sign.go

nit: add comments to `Signer` interface

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

update build images for release and bump cosign in the release job
n/a
```release-note
NONE
```

update build images for release and bump cosign in the release job

---

.github/workflows/build.yaml

generate/upload sbom for cosign projects
Fixes #1202
```release-note
feat: generate/upload sbom for cosign projects
```
cc: @imjasonh @mattmoor @cpanato @dlorenc

feat: generate/upload sbom for cosign projects

---

CODEOWNERS

update codeowners list with missing codeowners
n/a
```release-note
NONE
```

update codeowners list with missing codeowners

---

pkg/cosign/verify.go

fix: typo in the error message
Fixes
```release-note
fix: typo in the error message
```

fix: typo in the error message

---

go.mod
go.sum

Bump sigstore/sigstore.

---

pkg/signature/keys.go

feat: log error to stderr
Fixes #1259 
```release-note
feat: log error to stderr
```

feat: log error to stderr

---

go.mod
go.sum

Replaces #1272.
Fixes
```release-note
```

Bump miekg/pkcs11

---

specs/SBOM_SPEC.md

This documents the support for syft json added in #1137 
Signed-off-by: Sambhav Kothari <skothari44@bloomberg.net>
cosign already supports syft as an sbom format in #1137 but the spec was not updated to capture this support. This is a simple doc/spec change to bring it in line with the CLI.
Fixes
```release-note
Update SBOM spec to include support for syft json
```

Update SBOM spec to indicate compat for syft

---

go.mod
go.sum

Replaces #1282.
Fixes
```release-note
```

Bump google.golang.org/api.

---

cmd/cosign/cli/verify/verify_blob.go
cmd/cosign/cli/verify/verify_blob_test.go

I started looking at https://github.com/sigstore/cosign/issues/1193 and reorganized some code which should make it easier to implement!

Reorganize verify-blob code & add a unit test

---

IMPORT.md

An update to the import doc to reflect actual CLI usage.
Signed-off-by: Ivan Wallis ivan.wallis@venafi.com
Summary
Ticket Link
Fixes
Release Note

update import documentation

---

.github/workflows/scorecard_action.yml

Signed-off-by: Bob Callaway <bob.callaway@gmail.com>
Fixes
```release-note
```

add OSSF scorecard action

---

.github/workflows/build.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/cross.yaml
.github/workflows/donotsubmit.yaml
.github/workflows/e2e-with-binary.yml
.github/workflows/e2e_tests.yml
.github/workflows/github-oidc.yaml
.github/workflows/kind-e2e-cosigned.yaml
.github/workflows/milestone.yaml
.github/workflows/style.yaml
.github/workflows/tests.yaml
.github/workflows/validate-release.yml
.github/workflows/verify-docgen.yaml
.github/workflows/whitespace.yaml

Signed-off-by: Bob Callaway <bob.callaway@gmail.com>
Fixes
```release-note
```

pin github actions by digest

---

CODEOWNERS

Add vaikas to CODEOWNERS

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update cross builder image - the image is now signed using keyless method
```
$ COSIGN_EXPERIMENTAL=true TUF_ROOT=/tmp cosign verify ghcr.io/gythialy/golang-cross:v1.17.6-2@sha256:c03303287982360025dda196af6006fc5d1870955115efa8990d7278d8bfb7e9
client.go:196: root pinning is not supported in Spec 1.0.19
Verification for ghcr.io/gythialy/golang-cross@sha256:c03303287982360025dda196af6006fc5d1870955115efa8990d7278d8bfb7e9 --
- Existence of the claims in the transparency log was verified offline
[{"critical":{"identity":{"docker-reference":"ghcr.io/gythialy/golang-cross"},"image":{"docker-manifest-digest":"sha256:c03303287982360025dda …
```

update cross builder image - the image is now signed using keyless method

---

cmd/cosign/cli/verify.go
doc/cosign_verify-attestation.md

verify-attestation cue and rego policy doc
Fixes
```release-note
docs: verify-attestation cue and rego policy doc
```

docs: verify-attestation cue and rego policy doc

---

go.mod
go.sum

Fixes
```release-note
Bump sigstore/sigstore to pick up change for Vault logins.
```

Bump sigstore/sigstore to pick up oidc login for vault.

---

CHANGELOG.md

- add changelog for 1.5.1 release
n/a
```release-note
add changelog for 1.5.1 release
```

add changelog for 1.5.1 release

---

cmd/cosign/cli/commands.go
doc/cosign.md
doc/cosign_login.md

As we discussed in Sigstore Slack https://sigstore.slack.com/archives/C01DGF0G8U9/p1642610832086700, this PR will add login command to cosign.
thanks to @imjasonh ❤️
Fixes
```release-note
feat: login command
```

feat: login command

---

Makefile

Fixes #1450 
```release-note
feat: add -buildid= to ldflags
```

feat: add -buildid= to ldflags

---

README.md

This PR is a minor fix of `tkn cli` link in [README](https://github.com/sigstore/cosign/blob/main/README.md). 
N/A
```release-note
NONE
```

Fix tkn link in readme

---

go.mod
go.sum
pkg/cosign/git/gitlab/gitlab.go

Replaces #1449
Fixes
```release-note
```

Bump the gitlab library and add a nil opt for the API change.

---

release/release.mk

follow up of https://github.com/sigstore/cosign/pull/1472
n/a
```release-note
NONE
```

increase timeout for goreleaser snapshot

---

pkg/cosign/verify_test.go

Fix linter error on main

---

CHANGELOG.md

update changelog
Fixes
```release-note
```

Update Changelog for Security Advisory

---

CODEOWNERS

Fixes
```release-note
```
cc: @dentrax

feat: nominate Dentrax as codeowner

---

.github/workflows/milestone.yaml

use v6 api calls in GH action for updating release milestones

---

cmd/cosign/cli/options/fulcio.go
doc/cosign_attest.md
doc/cosign_policy_sign.md
doc/cosign_sign-blob.md
doc/cosign_sign.md

Both fulcio.sigstore.dev and v1.fulcio.sigstore.dev
point to the same backend.
Fixes https://github.com/sigstore/fulcio/issues/428
```release-note
Changed default Fulcio URL
```

Change Fulcio URL default to be fulcio.sigstore.dev

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update golang-cross to use go 1.17.8
- update cosign image to release v1.6.0
none
```release-note
NONE
```

Update images for release job

---

release/cloudbuild.yaml

fulcio->cosign
Fixes
```release-note
```

Fix copy/paste mistake in repo name.

---

go.mod
go.sum

Bump to knative pkg 1.3

---

.github/workflows/e2e_tests.yml

- update crane to v0.8.0 release
n/a
```release-note
NONE
```

update crane to v0.8.0 release

---

cmd/cosign/cli/verify/verify.go
cmd/cosign/cli/verify/verify_attestation.go

A certificate can also be provided in addition to a key ref or hardware
token.
Fixes
```release-note
```

Update error message for verify/verify attestation

---

pkg/providers/google/google.go

Remove the hardcoded sigstore audience

---

.goreleaser.yml

we removed all the replace directive so that is safe to add that back
- add back the go mod proxy
n/a
```release-note
NONE
```

add back the go mod proxy

---

.github/workflows/kind-cluster-image-policy.yaml

- enable 1.23 tests (Test cosigned with ClusterImagePolicy)
n/a
```release-note
NONE
```

enable 1.23 tests (Test cosigned with ClusterImagePolicy)

---

go.mod
go.sum
pkg/reconciler/clusterimagepolicy/clusterimagepolicy.go
pkg/reconciler/clusterimagepolicy/clusterimagepolicy_test.go
pkg/reconciler/testing/v1alpha1/factory.go

This PR reads the public key from the configured KMS authority and adds it to the ClusterImagePolicy ConfigMap. 
In a follow up PR, a resync period would be used to check the KMS service for changes.
Fixes
```release-note
```

cosigned: read the public key from the kms authority

---

release/cloudbuild.yaml

commenting out the copy from gcr to ghcr due issues on github side
None
```release-note
NONE
```

commenting out the copy from gcr to ghcr due issues on github side

---

pkg/cosign/tuf/client.go
pkg/cosign/tuf/client_test.go

* Remove old fulcio root from targets to fetch
* Do not require all fallbacks to be present, retrieve at least one.
Fixes
c/f this comment https://github.com/sigstore/cosign/issues/1716#issuecomment-1094460266
```release-note
```
cc @chunteck

bug: remove old fulcio root and fix fallback target code

---

CHANGELOG.md

- add changelog for v1.7.2
n/a
```release-note
NONE
```

add changelog for v1.7.2

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- Update release images
n/a
```release-note
NONE
```

update go builder and cosign images

---

CHANGELOG.md

- update changelog for 1.8.0
follow up of https://github.com/sigstore/cosign/pull/1803#issuecomment-1110120697
n/a
```release-note
NONE
```

update changelog for 1.8.0

---

README.md

Signed-off-by: Jack Baines jack.baines@uk.ibm.com
Adds IBM Cloud Container Registry to tested registry list
Closes https://github.com/sigstore/cosign/issues/1855
```release-note
NONE
```

Add IBM Cloud Container Registry to tested registry list

---

README.md

Signed-off-by: Ciara Carey <ccarey@cloudsmith.io>
Fixes
```release-note
```

Add Cloudsmith Container Registry to tested registry list

---

release/cloudbuild.yaml

- fix missing quote
`n/a` 
`n/a`

fix missing quote

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update cross-builder to go1.18.5
-  cosign image to 1.10.0
n/a
n/a

update cross-builder to go1.18.5 and cosign image to 1.10.0

---

.github/workflows/kind-verify-attestation.yaml

bump to scaffolding v0.4.4

---

CHANGELOG.md

add changelog for v1.11.0

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update builder image and cosign image

update builder image

---

.github/workflows/stale.yml

- add stale workflow using the workflow template

add stale workflow using the workflow template

---

.github/workflows/scorecard_action.yml

Signed-off-by: Azeem Shaikh <azeemshaikh38@gmail.com>
v2:alpha adds some bug fixes
NONE
NONE

Update Scorecard action to v2:alpha

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update go builder to go1.19.1

update go builder to go1.19.1

---

.github/workflows/tests.yaml

- update kind to use release v0.15.0 and some version comments

update kind to use release v0.15.0 and some version comments

---

CHANGELOG.md

- add changelog for v1.12.0 and v1.11.1

add changelog for v1.12.0 and v1.11.1

---

.github/workflows/kind-verify-attestation.yaml

Use 0.4.8 scaffolding for testing.

use scaffolding 0.4.8 for tests.

---

pkg/cosign/remote/index_test.go

replace deprecate package

---

CHANGELOG.md

- add changelog for v1.13.0 release

add changelog for v1.13.0 release

---

.github/workflows/depsreview.yml

switch to reusable workflow for license/vuln scan

---

cmd/cosign/cli/attest.go
cmd/cosign/cli/attest/attest.go
test/e2e_test.go

Refactor attest command to make it easier to set args

---

cmd/cosign/cli/verify.go
cmd/cosign/cli/verify/verify_blob.go
cmd/cosign/cli/verify/verify_blob_test.go
test/e2e_test.go

This way we don't have to pass in all the args in testing.

Refactor verify-blob command

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update builder image and cosign

update builder image and cosign

---

.github/workflows/build.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/cross.yaml
.github/workflows/donotsubmit.yaml
.github/workflows/e2e-with-binary.yml
.github/workflows/e2e_tests.yml
.github/workflows/github-oidc.yaml
.github/workflows/kind-verify-attestation.yaml
.github/workflows/tests.yaml
.github/workflows/validate-release.yml
.github/workflows/verify-docgen.yaml
.github/workflows/whitespace.yaml

- update ci to run jobs in the 1.0-fork branch

update ci to run jobs in the 1.0-fork branch

---

pkg/cosign/bundle/rekor_test.go

Add unit tests for the RekorBundle.

Add unit tests for the RekorBundle

---

test/sign_blob_test.sh

After the PR https://github.com/sigstore/cosign/pull/2400 the `.github/workflows/github-oidc.yaml` test start failing.
This PR updates the test, but I'm not sure if we want to ignore or update how we create the signature.
but with this change the flow works as well

update post submit test (.github/workflows/github-oidc.yaml)

---

Makefile
README.md
test/config/gettoken/gettoken.yaml

Add in missing v2 to go paths

---

.github/workflows/e2e-with-binary.yml

Somehow #2548 got merged even with this failing test.

Fix the file existence check.

---

.github/workflows/e2e-tests-kms.yml

replace `innovationnorway/setup-vault` that is not maintained to `cpanato/vault-installer`

use a maintained github action

---

.github/workflows/validate-release.yml

- refactor validate release job

refactor validate release job

---

README.md

Update docs to clarify that Cosign isn't only OCI

---

.github/workflows/e2e-tests-kms.yml

Signed-off-by: kpk47 <kkris@google.com>

Fix workflow parameter in e2e-kms test.

---

.golangci.yml
pkg/cosign/env/env.go

This will be better if we ever want to forbid other things.

Use local nolint, don't ignore whole files.

---

README.md

Closes https://github.com/sigstore/cosign/issues/2582
The Developer Installation instructions in the README mention Go 1.17 as minimally required. This is no longer the case. Cosign requires Go 1.19 in order to be installed successfully.
NONE
Updating docs here: https://github.com/sigstore/docs/pull/55

Update to Go 1.19 in the README Developer Installation instructions

---

test/e2e_test_insecure_registry.sh

Export COSIGN_YES=true var in insecure registry test

---

pkg/cosign/rego/rego.go

This log has been added here https://github.com/sigstore/cosign/pull/2577. We can safely remove it.

rego: remove unnecessary log

---

.github/workflows/e2e-tests-kms.yml

fix e2e-test-kms.sh: use newer version of cpanato/vault-installer

fix e2e-test-kms.sh: use newer version of cpanato/vault-installer

---

.github/workflows/build.yaml
.github/workflows/github-oidc.yaml
.github/workflows/kind-verify-attestation.yaml
.github/workflows/tests.yaml

- update setup-ko action to use new home ko-build/setup-ko
- bump kind to 0.17.0
cc @imjasonh

Update ko action and bump kind

---

EXAMPLES.md
KEYLESS.md
KMS.md
PKCS11.md
README.md
TOKENS.md
cmd/cosign/cli/verify/verify.go

Remove hardcoded Fulcio from output

---

ALUMNI.md

Add ALUMNI.md file

---

go.mod
go.sum

Update go-tuf dependency to latest

---

CHANGELOG.md

Update CHANGELOG for 2.0.0-rc.1

---

release/cloudbuild.yaml

the rc.1 release is broken because we need to skip the prompts

Skip confirmation prompt in cosign release flow

---

release/cloudbuild.yaml

update cosign image in cloudbuild release

---

.github/workflows/e2e-with-binary.yml
.github/workflows/github-oidc.yaml
.github/workflows/kind-verify-attestation.yaml
cmd/cosign/cli/options/signblob.go
test/e2e_test.sh

cleanup mentions of experimental var for 2.0

---

release/cloudbuild.yaml

- fix indentation and cosign verify command

fix indentation and cosign verify command

---

CHANGELOG.md

- add changelog for v2.0.0-rc.2 release

add changelog for v2.0.0-rc.2 release

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update builder image to use go1.20.1

update builder image to use go1.20.1

---

CHANGELOG.md

2.0.0 changelog

---

.github/workflows/validate-release.yml
.goreleaser.yml
release/cloudbuild.yaml

- update cosign and builder image and remove deprecated flags

update cosign and builder image and remove deprecated flags

---

Makefile

- update ko-local build
Fixes: https://github.com/sigstore/cosign/issues/2786

update ko-local build

---

cmd/cosign/cli/attach.go
doc/cosign_attach_attestation.md

Update URL to the in-toto bundle spec. The current link is broken.
NONE
Doc update included in PR

docs: update URL to in-toto bundle spec

---

cmd/cosign/cli/dockerfile/verify.go
cmd/cosign/cli/dockerfile/verify_test.go
cmd/cosign/cli/download/attestation.go
cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go
cmd/cosign/cli/publickey/public_key.go
cmd/cosign/cli/sign/sign_blob.go
cmd/cosign/cli/verify.go
cmd/cosign/cli/verify/verify.go
cmd/cosign/cli/verify/verify_attestation.go
cmd/cosign/cli/verify/verify_blob.go
cmd/cosign/cli/verify/verify_test.go
pkg/sget/sget.go

see https://github.com/sigstore/cosign/issues/2510

Use ui lib where applicable

---

README.md

Fix a typo
None
No, it is itself an update to documentation

docs(README): add the missing space

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- bump cross builder image to use go1.20.3

bump cross builder image to use go1.20.3

---

CHANGELOG.md

Add CHANGELOG for 2.0.1

---

release/ko-sign-release-images.sh

Remove force flag from release script

---

cmd/cosign/cli/copy/copy.go
go.mod
go.sum

I noticed that `cosign copy` was remarkably slow, so I bumped the go-containerregistry dependency to pick up some work I've been doing recently to simplify fixing that slowness.
I tested this by running `cosign copy` twice to copy `gcr.io/projectsigstore/cosign:v1.13.0` to Artifact Registry in us-central1. The second push is slower because it doesn't actually have to copy anything.
We're roughly 3x faster after this change.
|           | First Push | Second Push |
|-----------|------------|-------------|
| Before    | 69s        | 23s         |
| After     | **21s**    | **8s**      |
| Reduction | 70%        | 65%         |
There's more we can do, but this is an easy place to start.
`cosign copy` was optimized to copy images faster.

feat: Make cosign copy faster

---

CHANGELOG.md

Add CHANGELOG for v2.0.2

---

README.md

This removes the old demo gif in the Readme. Keeps it in line with changes in the docs repo.
Closes #2764

Removes old demo gif

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- Update cross builder and cosign images

Update cross builder and cosign images

---

pkg/providers/github/github.go

This should hopefully prevent transient flakes like this from breaking the signing flow:
```
Error: signing <IMAGE>: getting signer: getting key from Fulcio: fetching ambient OIDC credentials: Get "https://pipelines.actions.githubusercontent.com/WqlXQpGk4jIRp0EIHdmEkX1DGop5AMBj84NFOHZl2aUEmQZzFF/00000000-0000-0000-0000-000000000000/_apis/distributedtask/hubs/Actions/plans/b2699663-e65d-4294-81f5-0c040e4150df/jobs/2b13fac2-87c9-576d-edab-8ff6e585dee0/idtoken?api-version=2.0&audience=sigstore": stream error: stream ID 1; CANCEL; received from peer
```

retry GH OIDC requests up to 3 times

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update builder image to use go1.20.5

update builder image to use go1.20.5

---

.github/workflows/tests.yaml
.golangci.yml
Makefile

- Update golangci-lint and add depguard rules

Update golangci-lint and add depguard rules

---

CHANGELOG.md

add changelog for v2.1.1

---

.github/workflows/validate-release.yml

We started to have issues related to the available disk space in our runners. When running our CI job to validate the release, we faced these problems as explained in [here](https://github.com/sigstore/cosign/issues/3149).
closes https://github.com/sigstore/cosign/pull/3169
ci: free up disk space in the github runner.

ci: free up disk space in the gh runner

---

.github/workflows/kind-verify-attestation.yaml

test using latest release of scaffolding

---

CHANGELOG.md

add changelog for v2.2.0

---

cmd/cosign/cli/attest/attest.go

We need cred helpers and other info set in the remote opts to resolve the upstream attesations, otherwise this will fail in automated environments.
/cc @priyawadhwa @strongjz 
- Fixed bug in `cosign attest` where OCI remote configuration wasn't properly set.
n/a

attest: pass OCI remote opts to att resolver.

---

SECURITY.md

Should be set at the org level rather than repo level

Remove security policy

---

cmd/cosign/cli/copy.go
doc/cosign_copy.md

@znewman01 
Resolves this: https://github.com/sigstore/cosign/pull/3234#discussion_r1327966973

fix: dedent line in cosign copy doc

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update builder image to use go1.21.2

update builder image to use go1.21.2

---

.github/workflows/kind-verify-attestation.yaml

bump scaffolding to latest release in tests

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update builder image to use go1.21.3

update builder image to use go1.21.3

---

test/e2e_test.sh

DNM: Increase timeout of e2e tests

---

CHANGELOG.md

Add changelog for v2.2.2

---

cmd/cosign/cli/attach.go
doc/cosign_attach_signature.md

closes #3463 
Add sufficient examples for `cosign attach signature` command in CLI.
Enhancement

add examples for cosign attach signature cmd

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update builder image to use go1.21.6

update builder image to use go1.21.6

---

.github/workflows/kind-verify-attestation.yaml

update scaffolding version used in tests

---

.github/workflows/cross.yaml

follow up of #3501 
```
cut: you must specify a list of bytes, characters, or fields
```
https://github.com/sigstore/cosign/actions/runs/7677254104/job/20925763579

fix cross test

---

cmd/cosign/cli/download/sbom.go
cmd/cosign/cli/generate/generate.go
cmd/cosign/cli/verify/verify_blob.go
internal/pkg/cosign/common.go
pkg/cosign/verify.go
pkg/providers/interface.go

PR fixes the issues flagged by semgrep - `semgrep --config http://semgrep.dev/r/dgryski.semgrep-go`.
Output of `semgrep --config http://semgrep.dev/r/dgryski.semgrep-go` - see the [gist](https://gist.github.com/dmitris/198c82ff7d4c29847d26ee1a3cf3ee41).
NONE
n/ap

fix semgrep issues for dgryski.semgrep-go ruleset

---

.github/workflows/tests.yaml

free up disk space during e2e test runs

---

release/cloudbuild.yaml

1.13.x release: Fix spacing

---

.goreleaser.yml

This is using Cosign v1 to sign, so we need to experimental flag set.

release 1.13.x: fix goreleaser

---

CHANGELOG.md

Update CHANGELOG for v1.13.6

---

.github/workflows/kind-verify-attestation.yaml

bump scaffolding to v0.6.17 release for testing

---

.github/workflows/cut-release.yml

switch to community repo of reusable-release

---

cmd/cosign/cli/options/save.go
cmd/cosign/cli/save.go
doc/cosign_save.md

This PR closes: https://github.com/sigstore/cosign/issues/3630, it adds registry options to the cosign save cmd, I am fairly certain my changes here are correct, looking for more guidance if needed :) 
You can now use cosign save with HTTP and Insecure registries, it also includes registry Auth flags etc..
No docs changes necessary, `cosign save --help` explains everything

add registry options to cosign save

---

cmd/cosign/cli/attach/attach.go

fix: close attestationFile

---

test/README.md

Add README.md for tests

---

.github/workflows/e2e-tests.yml
.github/workflows/kind-verify-attestation.yaml

Bump scaffolding version

---

CHANGELOG.md

Add CHANGELOG for v2.3.0

---

.github/workflows/e2e-tests.yml
.github/workflows/kind-verify-attestation.yaml

bump scaffolding version in tests to 0.7.5

---

.github/workflows/validate-release.yml
test/e2e_test.sh

This cleans up debugging on #3809 and removes ineffective `apt purge` calls.

tidy up validate release script

---

.github/workflows/build.yaml

Add login for GHCR

---

.github/workflows/build.yaml

Add missing permission to push containers

---

README.md

resolve https://github.com/sigstore/cosign/issues/3883
I fixed a link of installation guide on README file.
Fix broken link on README file.

Fix documentation link for installation guide on README file

---

.github/workflows/e2e-tests.yml
.github/workflows/kind-verify-attestation.yaml

bump scaffolding release to v0.7.11

---

CHANGELOG.md

update changelog for v2.4.1

---

README.md

fix typo in readme for move to GHCR

---

README.md

Fixes https://github.com/sigstore/cosign/issues/3911

Update README scorecard badge link

---

specs/SIGNATURE_SPEC.md

Fixes https://github.com/sigstore/cosign/issues/3908

Remove usage.md from spec, point to client spec

---

cmd/cosign/cli/attest/attest_blob.go
cmd/cosign/cli/attest/attest_blob_test.go
cmd/cosign/cli/fulcio/fulcio.go
go.mod
internal/pkg/cosign/tsa/client/client.go
internal/pkg/cosign/tsa/mock/mock_tsa_client.go
internal/pkg/cosign/tsa/signer.go
pkg/cosign/errors_test.go
pkg/cosign/verify.go

Signed-off-by: Cody Soyland <codysoyland@github.com>
This removes the deprecated `github.com/pkg/errors` package, which has been replaced by the standard library. This work was previously done in https://github.com/sigstore/cosign/pull/1887, but several invocations have been gradually added since then.
Fixes https://github.com/sigstore/cosign/issues/1880 again :)

Remove dependency on github.com/pkg/errors

---

.github/workflows/build.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/conformance.yml
.github/workflows/donotsubmit.yaml
.github/workflows/e2e-tests.yml
.github/workflows/e2e-with-binary.yml
.github/workflows/github-oidc.yaml
.github/workflows/golangci-lint.yml
.github/workflows/kind-verify-attestation.yaml
.github/workflows/tests.yaml
.github/workflows/validate-release.yml
.github/workflows/verify-docgen.yaml
.github/workflows/whitespace.yaml

also uses `go-version-file` to minimize changes required on go major upgrade

fix zizmor issues

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update builder to use go1.23.4

update builder to use go1.22.10

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update builder to use go1.23.4

update builder to use go1.23.4

---

.github/workflows/conformance.yml

Bump conformance to latest version

---

CHANGELOG.md

update v2.4.2 changelog

---

CHANGELOG.md

Add changelog for v2.4.3

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update builder to use go1.24

update builder to use go1.24

---

.github/workflows/e2e-tests.yml
.github/workflows/kind-verify-attestation.yaml

bump to latest scaffolding release for testing

---

.github/workflows/validate-release.yml
release/cloudbuild.yaml

- update builder to use go1.24.1

update builder to use go1.24.1

---

.github/workflows/golangci-lint.yml
.golangci.yml
cmd/cosign/cli/attach/sig.go
cmd/cosign/cli/bundle/bundle_test.go
cmd/cosign/cli/sign/sign_test.go
cmd/cosign/cli/verify.go
cmd/cosign/cli/verify/verify_blob_attestation.go
cmd/cosign/cli/verify/verify_blob_attestation_test.go
cmd/cosign/cli/verify/verify_blob_test.go
cmd/cosign/errors/generate_docs.go
pkg/cosign/remote/index.go
pkg/cosign/tsa_test.go
pkg/cosign/verifiers.go
pkg/oci/internal/signature/layer.go
pkg/oci/layout/signatures.go
pkg/oci/mutate/signatures_test.go
pkg/oci/remote/signatures.go
pkg/oci/signature/layer.go
pkg/oci/static/file_test.go
test/helpers.go

Update golangci-lint to v2, update golangci-lint-action

---

cmd/cosign/cli/verify.go
doc/cosign_verify-blob.md

This PR fixes the missing indentation in `verify-blob` command docs.
Fixes #4158

Fix indentation in `verify-blob` command examples

---

cmd/cosign/cli/options/attest.go
doc/cosign_attest.md

remove unused recursive flag on attest command

---

cmd/cosign/cli/attest.go

PR sorts non-std imports alphabetically in cmd/cosign/cli/attest.go
NONE
N/A

cmd/cosign/cli/attest.go - sort imports

---

cmd/cosign/cli/attest/attest_blob.go
cmd/cosign/cli/bundle.go
cmd/cosign/cli/clean.go
cmd/cosign/cli/commands.go
cmd/cosign/cli/copy.go
cmd/cosign/cli/dockerfile.go
cmd/cosign/cli/download.go
cmd/cosign/cli/env.go
cmd/cosign/cli/generate.go
cmd/cosign/cli/generate_key_pair.go
cmd/cosign/cli/initialize.go
cmd/cosign/cli/load.go
cmd/cosign/cli/manifest.go
cmd/cosign/cli/options/annotations.go
cmd/cosign/cli/options/attach.go
cmd/cosign/cli/options/files.go
cmd/cosign/cli/options/predicate.go
cmd/cosign/cli/options/signature_digest.go
cmd/cosign/cli/sign/sign.go
test/e2e_test.go

sort Go imports alphabetically - extension of https://github.com/sigstore/cosign/pull/4196 for a number of other files with the similar "import mess" 😄 
NONE
n/a

sort Go imports alphabetically

---

.github/workflows/depsreview.yml

Should pick up the latest workflow for scanning for license issues.

Run reusable dependency review workflow from main

---

cmd/cosign/cli/sign/sign.go
cmd/cosign/cli/sign/sign_blob.go
go.mod
go.sum
pkg/cosign/verify.go
pkg/cosign/verify_bundle.go

One minor functional change, printing verification errors when verifying multiple signed timestamps.

Bump sigstore-go to v1.0, fix lint errors

---

.github/workflows/e2e-tests.yml
.github/workflows/kind-verify-attestation.yaml

update tests for latest scaffolding release

---

pkg/types/media.go

Golangci-lint was updated in
https://github.com/sigstore/cosign/pull/4279 but the linter seems to have missed this file then and is now being tripped up by it.

Fix lint error for types package

---

CHANGELOG.md

Add changelog for v2.5.3

---

.github/workflows/conformance.yml
.github/workflows/validate-release.yml
cmd/cosign/cli/verify/verify.go
cmd/cosign/cli/verify/verify_test.go
go.mod
go.sum
release/cloudbuild.yaml

This brings in two commits from the main branch to be a part of 2.6.1 - Building with Go 1.25.1, and an update to the output for cosign sign. This also bumps sigstore-go to set more descriptive user agents.
Besides security patches or significant bug fixes, we'll aim for this to be the last Cosign v2 release.

Cherrypicked updates for 2.6.1

---

.github/workflows/e2e-with-binary.yml
.github/workflows/kind-verify-attestation.yaml
cmd/cosign/cli/attest.go
cmd/cosign/cli/attest_blob.go
cmd/cosign/cli/options/attest.go
cmd/cosign/cli/options/attest_blob.go
cmd/cosign/cli/options/sign.go
cmd/cosign/cli/options/signblob.go
cmd/cosign/cli/sign.go
cmd/cosign/cli/signblob.go
doc/cosign_attest-blob.md
doc/cosign_attest.md
doc/cosign_sign-blob.md
doc/cosign_sign.md

This will also use sigstore-go's signing API by default.

Fetch service URLs from the TUF PGI signing config by default

---

.goreleaser.yml

update goreleaser flags to pass `--bundle` since that's now required.

update goreleaser config for v3.0.0 release

---

CHANGELOG.md

update CL for v3.0.1 release
