- README.md
- pkg/fetch.go
Before
```
$ cosign verify -key=cosign.pub ubuntu
error: GET https://index.docker.io/v2/library/ubuntu/manifests/sha256-703218c0465075f4425e58fac086e09e1de5c340b12976ab9eb8ad26615c3715: MANIFEST_UNKNOWN: manifest unknown; map[Tag:sha256-703218c0465075f4425e58fac086e09e1de5c340b12976ab9eb8ad26615c3715]
```
After
```
$ go run ./cmd verify -key cosign.pub ubuntu
error: manifest not found: index.docker.io/library/ubuntu:sha256-703218c0465075f4425e58fac086e09e1de5c340b12976ab9eb8ad26615c3715
exit status 1
```
It might be even better to say something like, "Is the image signed?" but this is a minor improvement at least.
> Better error message when the image hasn't been signed

- cmd/sign.go
- cmd/upload.go
- pkg/fetch.go
- pkg/remote.go
We shouldn't try to be too fancy here, it's best to stick with one
until more registries support the index format.
> Switch back to only supporting legacy signature formats.

- pkg/cosign/payload.go
- pkg/cosign/verify.go
- test/e2e_test.go
Using `Digest.Hex` drops the algorithm, but `Docker-manifest-digest` is supposed to include the algorithm.
> Include algorithm in Docker-manifest-digest

- cmd/main.go
This is useful to help debug things e.g. registry support.
> Add debug flag to log https request/response info

- FUN.md
- README.md
> Magic signed git commits!

- pkg/cosign/fetch.go
- pkg/cosign/remote.go
Before, we were calling the token exchange several times for no reason.
This reuses the v1.Image from remote.Image for fetching layers, which
can reuse the token from the original exchange. For me, this caused
verify to go from 5s to 1s overall.
Signed-off-by: Jon Johnson <jonjohnson@google.com>
> Make verify faster

- cmd/cosign/cli/sign.go
Right now we ask for password even if -key file doesn't exist.
> Do not prompt for password if ENOENT

- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_test.go
Closes #78. I also added a test around the functionality.
> return an error when both -key and -kms are used

- .github/workflows/tests.yaml
Locks the Go version to 1.15.10 (the latest 1.15 release at the time of commit), which is consistent with `go.mod`.
Also runs go tests as part of the pipeline.
> CI: lock Go version and run unit tests

- Makefile
- cmd/cosign/cli/version.go
- cmd/cosign/main.go
Sample output:
```shell
→ cosign version
cli.VersionInfo{GitVersion:"ddeddcb", GitCommit:"ddeddcb405f9967d9816a93177a2a2f078f17fbc", GitTreeState:"clean", BuildDate:"2021-03-19T00:35:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
Closes #96.
> Add version subcommand and Makefile

- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- cmd/cosign/cli/upload.go
- pkg/cosign/fetch.go
- pkg/cosign/fulcio/fulcio.go
- pkg/cosign/remote.go
This is the last change to fix up the next version of the fulcio API.
> Separate out the root/chain from the cert we get.

- Makefile
* Enabled static binary in go build.
> Feat - Included static binary in go build

- .gitignore
- Makefile
The lint target was failing without the golanglint tool.
> Feat - Included the golanglint-ci to be downloaded

- cmd/cosign/cli/errors.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_test.go
- test/e2e_test.go
My second pass at fixing this, closes #78. Thankyou to @priyawadhwa for catching that the issue wasn't fully resolved.
In order to add a test around the change I have refactored [`cli/verify.go`](https://github.com/chrnorm/cosign/blob/3f83da7da087513ad9d98bf35e6b551126cc0dff/cmd/cosign/cli/verify.go) to be closer to an [idiomatic ffcli example](https://github.com/peterbourgon/ff/tree/master/ffcli/examples/objectctl): I've added a `VerifyCommand` struct with an `Exec` receiver method which executes the actual command. 
Using a struct to hold configuration and writing to the struct using `flagset.StringVar` allows tests to be written around command execution (in this case, I've added a test checking the behaviour of when `-key` and `-kms` are both passed). See …
> `cosign validate`: return an error when kms and key arguments are both provided

- .github/workflows/build.yaml
> Whoops, sign with the linux binary always in our CI builds.

- .github/workflows/build.yaml
- .ko.yaml
- Makefile
This still doesn't build as part of our release process, we need to hook up GCP creds
somewhere.
This also fixes #126 
> Add a ko-built docker image to the makefile.

- .github/workflows/build.yaml
- Makefile
- README.md
Also change the location to have 'cosign' in the last part of the repo.
> Start signing the containers for our CI builds.

- cmd/cosign/cli/verify.go
We don't actually have a way to get into this state with the flags today. If
you use certs, the tlog has to be checked.
> Remove warning around not checking cert expiry.

- README.md
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/upload.go
- pkg/cosign/upload.go
- pkg/cosign/upload_test.go
This env var will allow users to specify which repo they want cosign signatures stored in!
I had to do some kinda sketchy string replacement to replace just the subrepo -- if we just directly replace the registry, we'd end up with something like this (which would be cleaner in the code, but isn't as pretty):
```
export COSIGN_REPOSITORY=gcr.io/distroless-signatures
gcr.io/cosign-signatures/static -> gcr.io/distroless/cosign-signatures/static
```
fixes https://github.com/sigstore/cosign/issues/122
> Add support for COSIGN_REPOSITORY env var

- cmd/cosign/cli/public_key.go
If you don't specify any args to "cosign public-key" right now it fails with
error: read: . is a directory
which is fairly confusing. So I'm using KeyParseError to indicate there's an
issue with these flags.
> cmd: check for missing args in public-key

- cmd/cosign/cli/generate_key_pair.go
In lack of a proper examples field, using ffcli's LongHelp to render some extra
fields to make commands more usable.
Sending a single command for feedback, will follow up with more if the format
is acceptable.
> cmd: use LongHelp to add examples/caveats

- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_test.go
- test/e2e_test.go
All of our testing (e2e and unit) unfortunately happens after flags are
parsed so we missed this.
> Fix the flag parsing in verify.

- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
Use KeyParseError (instead of "help requested" error) when both -key and -kms
are omitted.
> cmd: more meaningful error when -key|-kms missing

- .github/workflows/e2e_tests.yml
- test/e2e_test_secrets.sh
These run through the full bash flow rather than using go to hook
up after flag parsing.
> Add e2e tests with a new secret.

- copasetic/main.go
- pkg/cosign/verify.go
previously the roots were hardcoded in TrustedCert() function as
fulcio.Roots (and the passed value was usuned), but I assume this is not
what was intended.
> pass fulcio.Roots properly

- cmd/cosign/cli/verify.go
Fixes a bug where nothing happens if we pass in `-kms` because we're checking to make sure `-key` has a value
> Fix bug with -kms flag and verify

- README.md
I have tested cosign for gitlab container registry and work! 
My verify result:
```
$ cosign verify -key cosign.pub registry.gitlab.com/eminks/denemler:latest
- The signatures were verified against the specified public key
- WARNING - THE CERTIFICATE EXPIRY WAS NOT CHECKED. set COSIGN_EXPERIMENTAL=1 to check!
{"Critical":{"Identity":{"docker-reference":""},"Image":{"Docker-manifest-digest":"sha256:c93fa5b332de47c9f031284c7aa7a95988536e515571b73fa6294a0f54b289aa"},"Type":"cosign container signature"},"Optional":null}
```
Based on: #40
> Add Gitlab Container Registry

- README.md
- pkg/cosign/verify.go
This was nice when we used shorter ed25519 ones, it's not worth the complexity now with multi-line strings.
> Remove support for keys as base64 strings on the command line.

- cmd/cosign/cli/generate_key_pair.go
- cmd/cosign/cli/public_key.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- cmd/cosign/cli/verify_blob.go
- pkg/cosign/keys.go
- pkg/cosign/upload.go
- pkg/cosign/verify.go
> Upload entire certificate PEMs to rekor.

- .github/workflows/build.yaml
This is the only way to test changes to the workflow without merging to main.
> Make the build action run on all branch pushes.

- cmd/cosign/cli/generate.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- cmd/cosign/cli/upload.go
- pkg/cosign/payload.go
- pkg/cosign/sign.go
- pkg/cosign/verify.go
We should be abstracting Signer and Verifier (and Public Key provider) sooner rather than later. This gets us a step in that direction, but there's a lot more retooling to do on the interfaces
> Initial creation of Signer and Verifier interfaces.

- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_blob.go
- test/e2e_test_secrets.sh
This will be nice to have for signing kaniko and distroless in Cloud Build -- it's easier to have one cosign image step that can take in multiple image names to sign, than to have one step per image.
Output now looks like:
```
$ ./cosign sign -kms gcpkms://projects/priya-wadhwa/locations/global/keyRings/cosign/cryptoKeys/cosign gcr.io/priya-wadhwa/test gcr.io/priya-wadhwa/executor:test
Pushing signature to: gcr.io/priya-wadhwa/test:sha256-74e4a68dfba6f40b01787a3876cc1be0fb1d9025c3567cf8367c659f2187234f.cosign
Pushing signature to: gcr.io/priya-wadhwa/executor:sha256-aea14d1c82ad9b52bc10a05d12c99c513d55606627bcc31825c54abbaac9ed78.cosign
$ ./cosign verify -key cosign.pub gcr.io/priya-wadhwa/test gcr.io/priya-wadhwa/executor:test
Verification for gcr.io/priya-wadhwa/test --
The following …
```
> Allow passing in multiple image names to sign and verify

- README.md
- USAGE.md
- cmd/cosign/cli/public_key.go
- cmd/cosign/cli/public_key_test.go
- test/e2e_test.go
Adds a flag for specifying the output file for the public key when using `cosign public-key`:
`cosign public-key -key <key> -outfile somefile.pub`
By default, it writes to standard out now.
Example:
```
$ ./cosign public-key -key cosign.key -outfile a.txt
Enter password for private key: 
Public key written to  a.txt
$ cat a.txt
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAETvioBh+xbZH4IMlltKuIGuVEYjqF
HdA7wGAHvdkB12TSULi6v/0PTdRU8Vap94/vspnNcD1SY9NkXavR5lt+Mw==
-----END PUBLIC KEY-----
$ ./cosign public-key -key cosign.key 
Enter password for private key: 
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAETvioBh+xbZH4IMlltKuIGuVEYjqF
HdA7wGAHvdkB12TSULi6v/0PTdRU8Vap94/vspnNcD1SY9NkXavR5lt+Mw==
-----END PUBLIC …
```
> cmd: add option to specify public key output file

- cmd/cosign/cli/generate_key_pair.go
- cmd/cosign/cli/public_key.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_blob.go
- copasetic/main.go
- pkg/cosign/keys.go
- pkg/cosign/kms/gcp/gcp.go
- pkg/cosign/kms/kms.go
- pkg/cosign/sign.go
- pkg/cosign/verify.go
There's still more work to be done to productionize and de-spaghettify things:
* Verifier wrapper for x509 certs
* Refactoring to consolidate duplicated code
* Probably move interface types to their own file for the sake of clarity w.r.t. the relationships
> More work on the Signer, Verifier, PublicKeyProvider APIs

- Makefile
- cmd/cosign/cli/version.go
- cmd/cosign/cli/version_test.go
- go.mod
- Fix buildDate
- add flag to output the version in json. Default plain text
examples:
```console
$ ./cosign version
GitVersion:    v0.2.0-3-g1a75ff2
GitCommit:     1a75ff292076142483955e4681b1e0b0a7e3f1a9
GitTreeState:  clean
BuildDate:     2021-03-30T15:31:42Z
GoVersion:     go1.16.1
Compiler:      gc
Platform:      darwin/amd64
$ ./cosign version --json
{
"GitVersion": "v0.2.0-3-g1a75ff2",
"GitCommit": "1a75ff292076142483955e4681b1e0b0a7e3f1a9",
"GitTreeState": "clean",
"BuildDate": "2021-03-30T15:31:42Z",
"GoVersion": "go1.16.1",
"Compiler": "gc",
"Platform": "darwin/amd64"
}
$ ./cosign version --json | jq -r '.GitVersion'
v0.2.0-3-g1a75ff2
```
> cosign/version: fix buildDate and add flag to output in json

- cmd/cosign/cli/generate_key_pair.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/triangulate.go
- cmd/cosign/cli/upload.go
- pkg/cosign/fetch.go
- pkg/cosign/upload.go
- pkg/cosign/upload_test.go
- pkg/cosign/verify.go
- test/e2e_test_secrets.sh
This fixes a few bugs in cosign:
1. Actually generate the key pair when we run generate-key-pair with the -kms flag
2. Account for COSIGN_REPOSITORY on verify
3. Account for COSIGN_REPOSITORY on triangulate
> Fix a couple bugs in cosign

- pkg/cosign/upload_test.go
- test/e2e_test_secrets.sh
So  #222 [broke](https://github.com/sigstore/cosign/runs/2271983573?check_suite_focus=true) the e2e tests 😞 
Looks like it failed because `COSIGN_REPOITORY` tried to send signatures to a new registry (gcr) but actually resolved to (us-central1-docker.pkg.dev) -- this is something we should probably fix, but also I'm not sure how often people will be storing signatures in a different registry
> Use same registry throughout e2e test

- .github/workflows/build.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e_tests.yml
- .github/workflows/tests.yaml
- ci/build: build/push when creating tags as well
- ci: small cleanup 
- update golangci-lint to 1.39 release
- use sigstore/cosign-installer@v0.1.0 instead of sigstore/cosign-installer@main
When creating a Tag for the release the build workflow should be triggered to build cosign for the tag
> ci/build: build/push when creating tags as well

- Makefile
This is needed for the hardware token drivers.
> Add CGO_ENABLED=1 for ko.

- cmd/cosign/cli/flags.go
- cmd/cosign/cli/sign.go
Getting an error when using experimental mode with the keyless option. This fix allows it while still checking that if we're in experimental mode, we cannot provide both `-key` and `-kms`.
Signed-off-by: Ivan Font <ifont@redhat.com>
> Allow keyless option in experimental mode

- cmd/cosign/cli/flags.go
- cmd/cosign/cli/keys_test.go
- cmd/cosign/cli/pivcli/commands.go
- cmd/cosign/cli/public_key.go
- cmd/cosign/cli/public_key_test.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- cmd/cosign/cli/sign_test.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_blob.go
- pkg/cosign/pivkey/pivkey.go
- test/e2e_test.go
This replaces #169, and fixes #108 
The only thing I don't love here is the poor test coverage. I can't think of anything meaningful here though, unit testing the API with a mock key seems like a waste of effort and maintenance headache.
Maybe a manual test that we can run that requires actual key presses?
> Yubikey/PIV signing support!

- CHANGELOG.md
> Release notes for 0.3.0!

- Makefile
- cmd/cosign/cli/pivcli/commands.go
- cmd/cosign/cli/pivcli/disabled.go
- cmd/cosign/cli/pivcli/piv_tool.go
- pkg/cosign/keys.go
- pkg/cosign/pivkey/disabled.go
- pkg/cosign/pivkey/pivkey.go
- test/piv_test.go
Supporting privkey requires dynamic libs (`libpcsclite`) not present in `distroless/base`. The easiest way to fix the CI image is to drop yubikey support for the containerized `cosign` release
> disable pivkey on container build

- README.md
Tested ECR successfully on an EC2 box with an IAM role that had permissions to ECR.
> docs: add AWS ECR to list of supported registries

- pkg/cosign/pivkey/disabled.go
We should add a test for this during the container tests.
This was introduced in https://github.com/sigstore/cosign/pull/280
We should test for it in #273 
> Add another unimplemented mock for pivkey.

- cmd/cosign/cli/sign.go
- cmd/cosign/cli/upload.go
- pkg/cosign/remote.go
This is needed for cosign integration in chains!
> Make the auth pluggable for Upload.

- .github/workflows/cross.yaml
> Use matrix for build, include windows, and unify SHA256 hash with powershell

- cmd/cosign/cli/sign.go
- cmd/cosign/cli/upload.go
- pkg/cosign/remote.go
> Allow for arbitrary `remote.Option`s in `cosign.Upload`

- SPEC.md
- pkg/cosign/remote.go
- pkg/cosign/upload.go
- test/e2e_test_secrets.sh
> Use OCI Image Manifest v1

- .golangci.yml
- cmd/cosign/cli/sign.go
Also fixes an issue where bundle func no longer returns error.
Signed-off-by: Furkan Turkal <furkan.turkal@trendyol.com>
> enable unconvert and unparam linters

- pkg/cosign/upload.go
> Switch from api.rekor.dev to api.sigstore.dev.

- README.md
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- cmd/cosign/cli/verify.go
`$ cosign verify -k cosign.pub ...` is the wrong usage since we need to verify with a private key and enter the password in prompt. In case if we give a public key, it throws: `unsupported pem type: PUBLIC KEY`
Signed-off-by: Furkan Turkal <furkan.turkal@trendyol.com>
> fix usage example for sign + verify subcommands

- cmd/cosign/cli/pivcli/commands.go
- cmd/cosign/cli/pivcli/piv_tool.go
This will make scripting the setup much easier.
Here's what it looks like now:
```shell
$ cosign piv-tool attestation -output=json | jq .
{
"DeviceCertPem": "-----BEGIN CERTIFICATE-----\nMIIC+jCCAeKgAwIBAgIJAJDjrwcvIYiiMA0GCSqGSIb3DQEBCwUAMCsxKTAnBgNV\nBAMMIFl1YmljbyBQSVYgUm9vdCBDQSBTZXJpYWwgMjYzNzUxMCAXDTE2MDMxNDAw\nMDAwMFoYDzIwNTIwNDE3MDAwMDAwWjAhMR8wHQYDVQQDDBZZdWJpY28gUElWIEF0\ndGVzdGF0aW9uMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyS4ANsMp\nRQA9cigP1oUG8yQ8tQkel2IergXvY9WSYy/muj30exFWXvO323i9RaQtoT7hOS5d\nSsH1hNvSTD56fIaKpg+8jHsQLM6mF2Jo0Kb4rBduYNi+waFbGcwgrmRX1d9NcYb6\nUDJt0o0RW6aGPY6wqUvMlIj0EwNIN7Ct1wSjIdL1qFmyVwUkQkPDd/0jDv7giE0P\nM36qISQ6U8t2jNg5aWDEjf7wwWTIiMjbv0FaaiL5Vqmc7WboofKZN5nQyWGAtAtz\njTXzSkBfNPDO1eAUgbCbmu5efD8WeAtiPQyz8zQDU5UyihmDUEF1Dgr9/QMtQ5bd\nZ+FkBTtBYFp4aQIDAQA …
```
> Add JSON formatting for the device attestation commands.

- cmd/cosign/cli/copy.go
- cmd/cosign/main.go
- test/e2e_test_secrets.sh
> implement `cosign copy`

- pkg/cosign/upload.go
- pkg/cosign/upload_test.go
I spent a while trying to figure out a cleaner way to solve this, but unfortunately this is the only way I could find that worked for all the test cases. 
fixes https://github.com/sigstore/cosign/issues/322
> Add tag back in if lost during repository replacement

- cmd/cosign/cli/clean.go
- cmd/cosign/main.go
- test/e2e_test.go
> add clean sub-command for deleting signature metadata from a given image

- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_test.go
- pkg/cosign/fetch.go
- pkg/cosign/upload.go
- test/e2e_test.go
- test/e2e_test_secrets.sh
> add `-r` option for recursively signing multi-arch images

- .github/workflows/build.yaml
- .github/workflows/cross.yaml
- .github/workflows/e2e_tests.yml
- .github/workflows/tests.yaml
- Makefile
- cmd/cosign/cli/pivcli/commands.go
- cmd/cosign/cli/pivcli/disabled.go
- cmd/cosign/cli/pivcli/piv_tool.go
- pkg/cosign/pivkey/disabled.go
- pkg/cosign/pivkey/pivkey.go
Added `make cosign-pivkey` to offer support
Fixes: https://github.com/sigstore/cosign/issues/305
> make builds static (and yubikey support disabled) by default

- TOKENS.md
Fixes: https://github.com/sigstore/cosign/issues/304
> document `libpcsclite` dependency for pivkey support

- README.md
We've tested storing the cosign image signatures in Nexus Docker Registry. It works fine so, I though I submit this PR to append it to the list.
Signed-off-by: Balazs Zachar <zachar.balazs@gmail.com>
> add Sonatype Nexus Container Registry to tested registries list

- pkg/cosign/remote/index.go
Signed-off-by: Rotem Bar <rotem@cidersecurity.io>
Resolves issue in using upload-blob with AWS ECR. 
See discussion on slack - https://sigstore.slack.com/archives/C01PZKDL4DP/p1622552109047700
> split mime-type to support AWS ECR

- KMS.md
We recently added support for storing key pairs at the different paths for `Transit Secret Engine` at this [PR](https://github.com/sigstore/sigstore/pull/67) while using KMS support.
cc: @Dentrax
> add documentation for new environment variable for Vault KMS support

- test/e2e_test_secrets.sh
> allow for test image repo to be substituted in e2e tests

- cmd/cosign/cli/generate_key_pair.go
> added documentation of example usage of k8s secret support in generate-key-pair sub-command

- cmd/cosign/cli/pivcli/commands.go
- cmd/cosign/cli/pivcli/piv_tool.go
- cmd/cosign/cli/public_key.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_blob.go
- pkg/cosign/pivkey/disabled.go
- pkg/cosign/pivkey/pivkey.go
- pkg/cosign/pivkey/util.go
- test/piv_test.go
This permits flexibility to use different PIN and touch policies
for container signing. Key generation will use the default PIN
and touch policies for the specified slot unless additional flags
are set to attempt to override the default. The security key is
not guaranteed to honor a particular PIN and touch policy for the
specified slot.
Signed-off-by: Dino A. Dai Zovi <ddz@theta44.org>
> add flags to specify slot, PIN, and touch policies for security keys

- cmd/cosign/cli/sign.go
When pushing a signature to rekor originating from a private registry, the user gets the following warning message:
```
"warning: uploading to the public transparency log for a private image, please confirm [Y/N]: "
```
This message appears **even when you override the default public transparency log** with the `REKOR_SERVER` env. variable, which is confusing since the user is not sure which transparency log they are about to push to. 
In order to avoid this confusion, there were two potential avenues:
a) Override this check if `TlogServer() != rekorServer`
b) Display the transparency log address in the warning message
To avoid accidental pushes I decided to go with the b). Happy to switch to a) if you feel it's better. 
Signed-off-by: Paris Zoumpouloglou <pariszoump@gmail.com>
> Added transparency log address to warning

- KEYLESS.md
- pkg/cosign/verify.go
I noticed that in non-bundle, we are still using the integratedTime to check expiration without verifying rekor's signature of the signedEntryTimestamp
> verify the SET when getting a log entry

- CHANGELOG.md
- EXAMPLES.md
- README.md
- USAGE.md
- cmd/cosign/cli/attach/attach.go
- cmd/cosign/cli/attach/sig.go
- cmd/cosign/cli/upload/blob.go
- cmd/cosign/cli/upload/blob_test.go
- cmd/cosign/cli/upload/upload.go
- cmd/cosign/main.go
- test/e2e_test.go
- test/e2e_test_secrets.sh
This is in preparation for #368.
> Reorganize the upload and attach CLI commands.

- README.md
- cmd/cosign/cli/upload/upload.go
- cmd/cosign/cli/upload/wasm.go
- pkg/cosign/remote/index.go
- pkg/cosign/remote/remote.go
This probably isn't the ideal location/UX for the command, but I was able to get it working here when playing with https://www.kubewarden.io/.
We want to be helping sign/push WASM for other uses cases too, but they might use different storage mechanisms. This version (for kubewarden) used the one defined at https://github.com/engineerd/wasm-to-oci. There's another spec here: https://www.solo.io/blog/announcing-the-webassembly-wasm-oci-image-spec/
I'll need to understand the differences between these specs to see which (if any) might make sense to support here. For kubewarden, the policies need to be compiled to wasm and uploaded to a registry for retrieval. The documentation points to using the actual `wasm-to-oci` tool, but I was unable to get that working with GCR.
I read the spec and …
> Add cosign upload wasm command!

- cmd/cosign/cli/generate_key_pair.go
> adding documentation of the usage Hashicorp Vault for generate-key-pair sub-command

- CHANGELOG.md
- EXAMPLES.md
- USAGE.md
- cmd/cosign/cli/attach/sig.go
- cmd/cosign/cli/clean.go
- cmd/cosign/cli/copy.go
- cmd/cosign/cli/download/download.go
- cmd/cosign/cli/download/signature.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/triangulate.go
- cmd/cosign/cli/util.go
- cmd/cosign/cli/util_test.go
- cmd/cosign/cli/verify.go
- cmd/cosign/main.go
- cmd/sget/cli/sget.go
- copasetic/main.go
- test/e2e_test.go
This is in preparation for other attachment types, like SBOMs and attestations.
> Move cosign download to cosign download signature.

- cmd/cosign/cli/attach/attach.go
- cmd/cosign/cli/attach/sbom.go
- cmd/cosign/cli/download/download.go
- cmd/cosign/cli/download/sbom.go
- pkg/cosign/fetch.go
> SBOM support in "cosign attach" and "cosign download sbom".

- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_dockerfile.go
- cmd/cosign/main.go
- test/e2e_test.sh
- test/testdata/fancy_from.Dockerfile
- test/testdata/single_stage.Dockerfile
- test/testdata/unsigned_build_stage.Dockerfile
- test/testdata/with_arg.Dockerfile
> add `cosign verify-dockerfile` command

- cmd/cosign/cli/verify_dockerfile.go
> fix for documentation of the command verify-dockerfile

- cmd/cosign/cli/generate_key_pair.go
- cmd/cosign/cli/keys.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/verify.go
- pkg/cosign/kubernetes/secret.go
- pkg/cosign/kubernetes/secret_test.go
- test/e2e_test.go
Closes #347
Known issues about the implementation:
* We duplicated the Kubernetes Client logics (reducing both responsibilities to a single function?)
* It's a bit hard to distinguish `namespace/name` compared to other providers (adding a new -k8s flag for signing and verifying)
* Ref priority refactoring? (File -> KMS -> K8s) - we're checking K8s `namespace/name` in first-order ever since a file exists in that path
* We bring a brand-new `loadPublicKey` function to `cli/keys.go` due to `import cycle now allowed` problem
* We haven't been checked the values of the data map of the secret whether is nil or not nil.
* Use public key as a file
```bash 
$ kubectl get secrets my-secret -ojson | jq -r '.data["cosign.pub"]' | base64 -D > /tmp/cosign.pub
$ ./cosign verify -key /tmp/cosign.pub …
```
> signing&verifying container images based on Kubernetes Secrets

- .github/workflows/cross.yaml
Updates the output of the CI step generating the sha256 checksum in
order to make it compatible with the `sha256sum` tool.
With this update, the checksum can be verified using:
```
$ sha256sum -c cosign-darwin-amd64.sha256
cosign-darwin-amd64: OK
```
> Make .sha256 file compatible with sha256sum

- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- test/e2e_test.go
This PR adds an option to save the signature to a file when using the `cosign sign-blob` this will be helpful in the release pipeline.
> sign-blob: add option to save the signature to a file

- USAGE.md
I think cosign was intended here. `crane clean` does not exist
Signed-off-by: Russell Brown <rjbrown57@gmail.com>
> typo fix in usage.md

- KMS.md
- README.md
- go.mod
- go.sum
This bumps the sigstore dep to include https://github.com/sigstore/sigstore/pull/74 and adds documentation.
Signed-off-by: Cody Soyland <cody.soyland@solarwinds.com>
> Add AWS KMS Support

- .gitignore
- .goreleaser.yml
- Dockerfile
- Makefile
- release/cloudbuild.yaml
This PR updates the cloudbuild that will be used for the release process
- use goreleaser to build and do the cross compile and enable the piv-tool commands
- Add dockerfile to build the cosign image, due the limitation of `ko` to not support multiple ldflags at this moment
Tested in my fork repo: https://github.com/cpanato/cosign/releases/tag/v99.99.99
and image available for testing here: `gcr.io/cpanato-general/cosign:v99.99.99-1`
> update cloudbuild and goreleaser to build cosign also with piv-tool

- .goreleaser.yml
- release/cloudbuild.yaml
* Disable pivkey support on default linux release, add another release with support
* Reduce redundancy in release binary names
> Numerous updates to `.goreleaser.yml` & associated scripts

- cmd/cosign/cli/public_key.go
> added Hashicorp Vault KMS support to the description of public-key sub-command

- README.md
Just getting started with cosign. This addresses a few issues that I found while going through the readme.
Signed-off-by: João Pereira <484633+joaodrp@users.noreply.github.com>
> Readme fixes and improvements

- cmd/cosign/cli/public_key.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_blob.go
- pkg/cosign/pivkey/util.go
Previously, the default slot was Authentication (9a) which is intended to be used
for authentication with SSH or similar systems. In the context of cosign, it makes
more sense to default to the Signature slot which is intended for use with message
and code signing.
Signed-off-by: James Alseth <james@jalseth.me>
> pivkey: Change default slot to Signature (9c)

- cmd/cosign/cli/generate_key_pair.go
- cmd/cosign/cli/public_key.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- cmd/cosign/cli/verify_blob.go
- cmd/cosign/cli/verify_dockerfile.go
- go.mod
- go.sum
- update sigstore dependency to include Azure KMS
- Add AWS/Azure/Vault in the help for each command and format the text to make similar to each other
> Update sigtore dependency to include Azure KMS

- cmd/cosign/cli/pivcli/commands.go
- cmd/cosign/cli/public_key.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- cmd/cosign/cli/sign_test.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_blob.go
- pkg/cosign/pivkey/disabled.go
- pkg/cosign/pivkey/pivkey.go
- test/e2e_test.go
The `-cert` flag allows for the certificate to be included in the
Signature object when signing with `-key` or `-sk`. Adding this
certificate ensures that a verifying party does not need to fetch the
certificate from some unknown location before being able to validate the
identity of the actor that created the signature.
---
This also includes a refactor of the `pivkey` library to make it more idiomatic and to resolve an issue where calling `NewPublicKeyProvider` or `NewSignerVerifier` would lock the PIV token until the program had exited, making future calls to the PIV token outside of the signer/verifier flow impossible.
> cmd/sign: Add `-cert` flag

- specs/SIGNATURE_SPEC.md
USAGE.md isn't under the spec/ directory, it's up one level
in the repo root.
Also linking directly to 'Verify a signature was added to the
transparency log'.
Signed-off-by: Tom Hennen <tomhennen@google.com>
> Fix USAGE.md link

- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- cmd/cosign/cli/sign_test.go
- test/e2e_test.go
> Refactor signing options a bit between blob/image.

- go.mod
- go.sum
- pkg/cosign/keys.go
> more refactoring to use cryptoutils

- release/cloudbuild.yaml
Update the go builder container for the release pipeline to use go1.16.6
PR in the source that upgrade Go: https://github.com/gythialy/golang-cross/pull/13
the release of the image: https://github.com/gythialy/golang-cross/releases/tag/v1.16.6
> release: update builder container to use go 1.16.6

- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- cmd/cosign/cli/util.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_blob.go
- copasetic/main.go
- pkg/cosign/fulcio/fulcio.go
- pkg/cosign/fulcio/fulcio_test.go
- test/e2e_test.go
Implements flags for fulco, rekor and OIDC values to allow a user to set their own custom values.
The defaults fall to the public good service
> Infra flags for fulcio / rekor / oidc values

- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- pkg/cosign/fulcio/fulcio.go
- pkg/cosign/fulcio/fulcio_test.go
- pkg/cosign/remote/remote.go
* `fulcio-url` is more descriptive and consistent with Rekor
* raw PEMs are canonically `[]byte`s in the standard lib
> `fulcio-server` -> `fulcio-url`, `pkg/fulcio` refactoring

- README.md
- cmd/cosign/cli/attest.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/verify_attestation.go
- cmd/cosign/main.go
- go.mod
- go.sum
- pkg/cosign/fetch.go
- pkg/cosign/upload.go
- pkg/cosign/verifiers.go
- test/e2e_test.go
> Add "cosign attest" command!

- pkg/cosign/remote/index.go
- pkg/cosign/remote/remote.go
This type isn't used outside of the package, so there's no reason to export it. If other external packages come to depend on it you might anger people with breaking changes. Let's just unexport it now while (we think) it doesn't have many dependents. If we decide it's worth sharing we can make that decision later.
> Unexport pkg/cosign/remote.StaticLayer

- .github/workflows/codeql-analysis.yml
Ref #191 
This is now taking 20+ minutes and has still never failed. Let's run it post-merge.
> Only run codeql post-merge.

- cmd/cosign/cli/attach/sbom.go
- cmd/cosign/cli/attach/sig.go
- cmd/cosign/cli/attest.go
- cmd/cosign/cli/clean.go
- cmd/cosign/cli/copy.go
- cmd/cosign/cli/digest.go
- cmd/cosign/cli/download/sbom.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/triangulate.go
- pkg/cosign/fetch.go
- pkg/cosign/verifiers.go
- pkg/cosign/verify.go
- test/e2e_test.go
@jonjohnsonjr noticed these and says this should make cosign a lot faster.
Some of these were TODOs, some just fell out of having `AttachedImageTag` take a digest instead of a descriptor, and looking around while fixing the resulting code breakage.
> Avoid remote.Gets when the ref contains a digest

- release/cloudbuild.yaml
We will build both static and nonstatic cosign for Linux and in the release job we will use the static compiled binary, so we don't need to install the extra dependency library
> cloudbuild: remove not needed dependency library

- cmd/cosign/cli/attest.go
> fix attest command descriptions, changed attestation flag as predicate

- cmd/cosign/cli/attest.go
- pkg/cosign/attestation/attestation.go
- test/e2e_test.go
Fixes #472
Known Limitations:
* We don't add support for SPDX predicate yet, because of [that](https://github.com/in-toto/in-toto-golang/blob/886210ae2ab9bfe02fc975213d9bc0cb7ae5f6b8/in_toto/model.go#L960-L966):
> Currently not implemented. Some tooling exists here:
https://github.com/spdx/tools-golang, but this software is still in
early state.
cc: @Dentrax
> add well-known attestation specs support to the attest command

- cmd/cosign/cli/verify_manifest.go
- cmd/cosign/cli/verify_manifest_test.go
- cmd/cosign/main.go
- test/e2e_test.sh
- test/testdata/signed_manifest.yaml
- test/testdata/unsigned_manifest.yaml
Adds support for verifying kubernetes resources (manifests) and addresses #437 
It's a naive approach, but wanted to get feedback early on, especially around YAML parsing via regex and JSON support as discussed in the ticket.
> Add `cosign verify-manifest` command

- cmd/cosign/cli/verify_manifest.go
- cmd/cosign/cli/verify_manifest_test.go
Signed-off-by: Hector Fernandez <hectorj@gmail.com>
This PR is related to a discussion (https://github.com/sigstore/cosign/pull/490#discussion_r677526759) in this PR https://github.com/sigstore/cosign/pull/490. It aims to decode the manifest looking for multiple resources within a yaml file and decoding the list of core Kubernetes API types that has an image property. Considering the Kubernetes core API is in a stable state, we can assume there won't be many changes to these core types.
> verify-manifest: decode and use kubernetes resources

- cmd/cosign/cli/verify_dockerfile.go
> Verify ignore scratch images

- README.md
Signed-off-by: Jim Bugwadia <jim@nirmata.com>
fix in-toto.io link in cosign/README.md
> fix in-toto.io link

- cmd/cosign/cli/attach/sbom.go
> fix for reading sbom file from stdin

- cmd/cosign/cli/fulcio/fulcio.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_attestation.go
- cmd/cosign/cli/verify_blob.go
- cmd/sget/cli/sget.go
- copasetic/main.go
Main motivation:
* I added a `cosign init` command that sets up the TUF repository locally so that trusted targets can be verified and retrieved from there.
* Unfortunately, it's kind of circular to init the fulcio root certificate before you do that, and that also means you can't run the init command to configure your TUF mirrors and trusted keys yourself if you wanted to.
So this lazily inits the fulcio roots
Sorry for breaking semantic versioning...
> Lazy initialize the fulcio Root

- README.md
> Document the usage of COSIGN_PASSWORD env var when signing images

- README.md
Signed-off-by: Li Yi <denverdino@gmail.com>
I have tested cosign for Alibaba Cloud Container Registry and work!
My verify result:
```
$ cosign sign -key cosign.key registry.cn-hangzhou.aliyuncs.com/denverdino/busybox
Enter password for private key:
Pushing signature to: registry.cn-hangzhou.aliyuncs.com/denverdino/busybox:sha256-dca71257cd2e72840a21f0323234bb2e33fea6d949fa0f21c5102146f583486b.sig
$ cosign verify -key cosign.pub registry.cn-hangzhou.aliyuncs.com/denverdino/busybox
Verification for registry.cn-hangzhou.aliyuncs.com/denverdino/busybox --
- The signatures were verified against the specified public key …
```
> Add Alibaba Cloud Container Registry

- Makefile
- cmd/cosign/cli/version.go
- cmd/cosign/main.go
Add way to display the version when using `go install`/ `go get`
related to https://github.com/sigstore/rekor/issues/212 and similar we did for rekor: https://github.com/sigstore/rekor/pull/405
> version: add way to display a version when using go get or go install

- go.mod
- pkg/cosign/tuf/store.go
I had expired credentials that were causing this to fail. The bucket
is public, so we should just not use auth (which apparently requires being
explicit).
> Explicitly disable auth for the sigstore-tuf-root.

- cmd/cosign/cli/upload/blob.go
- go.mod
- go.sum
- pkg/cosign/remote/index.go
- pkg/cosign/remote/index_test.go
- test/e2e_test.go
this way, Chains can use this library to upload files to an OCI registry.
> Refactor upload-blob to use File interface

- KEYLESS.md
I had some trouble getting the walkthrough to work, and with @dlorenc 's help got it to work. From outside a GCE VM you need to impersonate an IAM SA.
This also updates the required `audiences` to `sigstore` (from `fulcio`), and fixes some minor nits.
> Improve docs for keyless SA signing

- .github/workflows/e2e_tests.yml
- go.mod
- go.sum
This fixes two CI-related issues hit while proposing #536 
1. e2e tests are run for all pushes, even to forked repos. This causes them to fail when they don't have the required secret configured. See https://github.com/imjasonh/cosign/actions/runs/1125396335 -- this change disables e2e tests when the repo != `sigstore/cosign`, and tells GitHub Actions to run the workflow when it's as a PR to the cosign repo, not only when it's a push. Also allow manual execution, because why not.
2. CI tests failed due to an out-of-date module dependency. See https://github.com/imjasonh/cosign/actions/runs/1125396339 -- this change runs the `go get` command in that error message.
This change also removes some unnecessary comments from e2e_tests.yml for (I think) better readability.
> Fix CI issues for forked repos

- cmd/cosign/cli/verify_manifest.go
- cmd/cosign/cli/verify_manifest_test.go
Signed-off-by: Jose Donizetti <jdbjunior@gmail.com>
Minor refactor to avoid the conversion string <-> []byte. 
Let me know if you okay with small changes like this. Thanks
> Refactor to avoid not necessary conversion

- pkg/cosign/verify.go
Signed-off-by: Jim Bugwadia <jim@nirmata.com>
Fixes https://github.com/sigstore/cosign/issues/542
Remove fetch by digest, to always retrieval of the latest digest from the registry, in case an invalid digest is passed in or if the image is deleted and the signature is not.
With this change an invalid manifest error is returned when the incorrect digest is passed in:
```sh
cosign verify -key ~/cosign.pub ghcr.io/jimbugwadia/pause@sha256:b31bfb4d0213f254d361e0079deaaebefa4f82ba7aa76ef82e90b4935ad5b105
error: GET https://ghcr.io/v2/jimbugwadia/pause/manifests/sha256:b31bfb4d0213f254d361e0079deaaebefa4f82ba7aa76ef82e90b4935ad5b105: MANIFEST_UNKNOWN: manifest unknown
```
> always check remote image

- KMS.md
- README.md
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/verify.go
This PR adds two commits to improve the examples of Kubernetes secrets in the cosign sign and verify commands, as well as the documentation:
This commit adds a Kubernetes section to the KMS document explaining how
to generate a key pair and a general overview of how cosign interacts
with secrets in the cluster.
This commit adds kubernetes examples to the help output of `cosign verify` and `cosign sign`.
In addition, square and angled brackets used as placeholders in examples are modified to match the output of both subcommands.
Signed-off-by: Adolfo García Veytia (Puerco) <adolfo.garcia@uservers.net>
> Improve Kubernetes examples in docs and commands

- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_attestation.go
There are a few things on this PR.
1 - improve documentation, listing the possible options for `-output` -> '(json|text)'
2 - fix existing behavior, where `-output` is actually ignored, [using always `text`](https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/verify.go#L166), even though the documentation says the [default is `json`](https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/verify.go#L54).
A couple questions:
1 - I think it makes more sense to rename this flag to `-format`, instead of `-output` considering the options (json/text).
2 - The current default is `text`, but fixing this to follow the documentation, it becomes `json`, but I think text looks better on the command line.
wdyt?
> Fix verify and verify-attestation output flag

- cmd/cosign/cli/generate_key_pair.go
- cmd/cosign/cli/generate_key_pair_test.go
We don't need to read from stdin or the env var twice :)
> Move the prompting/confirmation down into the password implementations.

- .golangci.yml
- Makefile
- cmd/cosign/cli/version.go
- pkg/cosign/attestation/attestation.go
Signed-off-by: Hector Fernandez <hectorf@vmware.com>
When running `lint`, we see the following warning message. 
```
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive.
```
> fix: lint warning

- CODEOWNERS
We manage the CODEOWNERS via a GitHub team which unfortunately means the list
isn't present here. Let's keep them in sync manually until we come up with
something better.
> Add a commented out list of OWNERS for transparency.

- cmd/cosign/cli/attest.go
- cmd/cosign/cli/verify_attestation.go
- pkg/cosign/remote/remote.go
- specs/ATTESTATION_SPEC.md
> Fix some bugs in the attestation support and add a formal spec.

- cmd/cosign/cli/upload/blob.go
I was playing around with the `cosign` cli and found that calling `cosign upload blob ...` with an image address but without any `-f` arguments leads to a nil pointer dereference. This patch adds a check that at least one file was provided.
The underlying cause is that calling `cremote.UploadFiles` with an empty `files` list never sets the `var img v1.Image` within and thus the returned `dgstr` is `nil`, I believe?
> fix nil pointer deref in cli/upload.BlobCmd

- release/cloudbuild.yaml
Update the go builder container for the release pipeline to use go1.17
PR in the source that upgrade Go: https://github.com/gythialy/golang-cross/pull/17
the release of the image: https://github.com/gythialy/golang-cross/releases/tag/v1.17
> release: update golang-cross image to use go 1.17

- cmd/cosign/cli/fulcio/fulcio.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_attestation.go
- cmd/sget/cli/sget.go
- pkg/cosign/tlog.go
> Make the warning around TUF roots a little less scary.

- .github/workflows/helm-ci.yaml
helm/ci: update helm repo before installing the dependency
the errors we see when merging the PR to the main branch like https://github.com/sigstore/cosign/runs/3445155267 can be related to the repo is not updated, but also to some network issues. I had similar behavior sometimes in my local.
but at least we update the repo and make sure that is up-to-date.
> helm/ci: update helm repo before installing the dependency

- KMS.md
Just a minor tidy-up.
Curiously - the GCP resource name for a key is a slightly different format to the key format in cosign:
GCP format: `projects/$PROJECT/locations/$LOCATION/keyRings/$KEYRING/cryptoKeys/$KEY/cryptoKeyVersions/$KEY_VERSION`
Cosign format: `gcpkms://projects/$PROJECT/locations/$LOCATION/keyRings/$KEYRING/cryptoKeys/$KEY/versions/$KEY_VERSION`
Note that the 2nd last path segment is "cryptoKeyVersions" not "versions" - this is based on copying the resource name out of the GCP console.
"Safer KMS Viewer Role" - I suspect this is wrong too (as I can't find anything called this) - but I don't know what the correct value is - as I wasn't able to get signing working without using KMS Admin role.
Once I get over that hurdle I'll be back...
> Add extra replacement variables and GCP's role identifier

- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_blob.go
verify_blob: add missing help option to use the pub key from a remote
> verify_blob: add missing help option to use the pub key from a remote

- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_test.go
- cmd/cosign/cli/verify.go
- test/e2e_test.go
Signed-off-by: Sambhav Kothari <sambhavs.email@gmail.com>
Fixes #610
> Add cosign attachment signing and verification

- cmd/cosign/cli/generate_key_pair.go
Also create public key with 0644 permission. Both of these changes are done using ssh-keygen as reference.
Signed-off-by: Pradeep Chhetri <pradeepchhetri4444@gmail.com>
> Make sure generate-key-pair doesn't overwrite existing key-pair

- Makefile
Signed-off-by: Hector Fernandez <hectorf@vmware.com>
I found some unused targets in our Makefile.
> chore: cleanup Makefile targers

- cmd/cosign/cli/pivcli/disabled.go
- pkg/cosign/pivkey/disabled.go
- pkg/cosign/pivkey/pivkey.go
- pkg/cosign/pivkey/util.go
A bunch of PRs are failing with this.
> Something changed in go 1.17 to make this a failure now.

- cmd/cosign/cli/init.go
- cmd/cosign/cli/util.go
- cmd/cosign/cli/verify_blob.go
Fix #608
we developed this code with @Dentrax @erkanzileli
> feat: add support for downloading signature from remote

- cmd/cosign/webhook/main.go
- pkg/cosign/kubernetes/webhook/handler.go
- pkg/cosign/kubernetes/webhook/validation.go
There was a bunch of boilerplate to differentiate between Create/Update, which wasn't particularly useful.  This drops it and streamlines a bunch of the logic.
I expect this will be the first cleanup of a number to follow...
> Drop the distinction between Create/Update.

- cmd/cosign/webhook/main.go
- pkg/cosign/kubernetes/webhook/handler.go
- pkg/cosign/kubernetes/webhook/validation.go
I noticed the unused parameter in my previous change and tugged.  Seems completely unused.
> Drop the unused `apiReader`

- cmd/cosign/cli/verify.go
- pkg/cosign/verify.go
Fixes https://github.com/sigstore/cosign/issues/556
(at least partially)
In the long term we'll want to implement the ability to explicitly state expected cert subject(s), but the UX design for that was sticky enough that I wanted to make that change independently.
> add `-cert-email` flag to specify an email for a `fulcio` cert  to be valid

- cmd/cosign/cli/verify_blob.go
Greetings. We just fixed the verify_blob command's document.
@developer-guy @Dentrax FYI guys
> docs: add remote url example for verify_blog cmd

- cmd/cosign/cli/verify_dockerfile.go
- test/e2e_test.sh
- test/testdata/with_lowercase.Dockerfile
This is a simple fix to allow "from" in dockerfiles to have their
image arguments detected by verify-dockerfile command.
Signed-off-by: Michael <mlieberman85@gmail.com>
> Fix verify-dockerfile to allow lowercase FROM

- KEYLESS.md
- cmd/cosign/cli/sign.go
- pkg/providers/doc.go
- pkg/providers/github/doc.go
- pkg/providers/github/github.go
- pkg/providers/google/doc.go
- pkg/providers/google/google.go
- pkg/providers/interface.go
This is based on some work I have been doing here: https://github.com/mattmoor/oidc-magic
At present, it is fairly tedious to use the "keyless" flow inside of environments that have a form of ambient OIDC (e.g. GKE workload identity).  For example, in the context of Tekton, one needs to overlay `cosign` on an image like `docker.io/google/cloud-sdk:slim`, and then during execution have the step do something like:
```yaml
command: ["/bin/sh"]
args:
- "-c"
- |
IDENTITY_TOKEN=$(gcloud auth print-identity-token --audiences=sigstore)
cosign sign \
-identity-token $IDENTITY_TOKEN \
my.registry/the-image@sha256:deadbeef
```
This change adds support for detecting when `cosign` is executing within an environment with this kind of ambient authentication, and automatically producing one when …
> Add logic to detect and use ambient OIDC from exec envs.

- cmd/cosign/cli/attest.go
- cmd/cosign/cli/clean.go
- cmd/cosign/cli/download/sbom.go
- cmd/cosign/cli/download/signature.go
- cmd/cosign/cli/fulcio/fulcio.go
- cmd/cosign/cli/generate.go
- cmd/cosign/cli/pivcli/commands.go
- cmd/cosign/cli/pivcli/piv_tool.go
- cmd/cosign/cli/public_key.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- cmd/cosign/cli/triangulate.go
- cmd/cosign/cli/upload/blob.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/version.go
- cmd/cosign/main.go
- cmd/sget/main.go
- copasetic/main.go
- pkg/cosign/tlog.go
This is basically these commands (I also renamed a variable in the output-capture code):
```shell
sed -i 's@fmt.Printf(@fmt.Fprintf(os.Stderr, @g' $(git grep fmt.Printf | cut -d':' -f 1 | uniq)
sed -i 's@fmt.Println(@fmt.Fprintln(os.Stderr, @g' $(git grep fmt.Println | cut -d':' -f 1 | uniq)
sed -i 's/os.Stdout/os.Stderr/g' $(git grep os.Stdout | cut -d':' -f 1)
```
---
_(some context around motivation)_
I have been experimenting with adding inline keyless verification in downstream tooling with:
```go
if cli.EnableExperimental() {
if err := cli.Verify().Exec(cmd.Context(), []string{opts.ref.String()}); err != nil {
return err
}
}
```
(and similar for keyless signing, but that's more verbose currently, so omitted)
However, some of these tools reserve STDOUT to enable command composition, …
> Consistently use STDERR for output.

- Dockerfile
- Dockerfile.cosigned
The dockerfile was referring to the tag. It is recommended to use pinned
dependencies based on SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
Changed the go:1.17 to SHA256 digest. This still works with dependabot.
> Pinned the dockerfile to sha256

- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_attestation.go
- cmd/sget/cli/sget.go
This will make it easier to customize for attestation output.
> Refactor verification output.

- KEYLESS.md
- go.mod
- go.sum
- pkg/providers/google/google.go
This requires the use of an environment variable called "GOOGLE_SERVICE_ACCOUNT_NAME"
to direct the client on which account to impersonate.
> Support GCP environments without workload identity (GCB).

- cmd/cosign/cli/fulcio/fulcio.go
I noticed this experimenting with integration with `ko` downstream.
cc @dlorenc
> Send log statement to STDERR

- cmd/cosign/cli/sign.go
- pkg/providers/all/all.go
With this change folks can avoid `_` imports to enable all plugins with:
```go
import (
providers "github.com/sigstore/cosign/pkg/providers/all"
)
```
> Provide a mechanism for downstream folks to avoid `_` imports.

- cmd/cosign/cli/attach/sbom.go
- cmd/cosign/cli/attest.go
- cmd/cosign/cli/upload/wasm.go
- pkg/cosign/remote/remote.go
- pkg/types/media.go
- pkg/types/payload.go
I noticed Chains was consuming the `Dsse` type from `cli`, which was problematic because `cli` pulls in `glog` and triggers the `-log_dir` problem.
Cosign seems to have media and payload types sprinkled everywhere, so I factored out `pkg/types/{media,payload}.go` where we can define these in a common place that's dependency free.
cc @priyawadhwa @dlorenc
> Extract a `types` package for media and payload types.

- cmd/cosign/cli/keys.go
- cmd/cosign/cli/keys_test.go
- pkg/cosign/keys.go
- pkg/cosign/keys_test.go
- test/e2e_test.go
Chains is consuming this public function, but because `./cmd/cosign/cli` pulls in `glog` we hit the `-log_dir` problem.  With this change it can drop it's dependency on `cli`.
cc @priyawadhwa @dlorenc @dekkagaijin
> Move `LoadEcdsa...` into `pkg/cosign/keys.go`

- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_test.go
- test/e2e_test.go
With this change, the keyless flow builds a single signer for all of the images, which means a single key and 3LO for all of the references we sign:
```shell
$ COSIGN_EXPERIMENTAL=true cosign sign ghcr.io/mattmoor/controller ghcr.io/mattmoor/webhook
Generating ephemeral keys...
Retrieving signed certificate...
Your browser will now be opened to:
https://oauth2.sigstore.dev/auth/auth?REDACTED
Successfully verified SCT...
tlog entry created with index: 693418
Pushing signature to: ghcr.io/mattmoor/controller:sha256-b10f4b2e04cde2e799e080068f162ef668c4db3099382798b5fe1a208023105d.sig
tlog entry created with index: 693420
Pushing signature to: ghcr.io/mattmoor/webhook:sha256-ed1b1c778685ae0739cd4c6354fa2d724351b01e998a019d1ddc2909c377483d.sig
```
Fixes: …
> Have the keyless `cosign sign` flow use a single 3LO.

- cmd/cosign/cli/dockerfile/cmdgroup.go
- cmd/cosign/cli/dockerfile/verify.go
- cmd/cosign/cli/dockerfile/verify_test.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_manifest.go
- cmd/cosign/main.go
- test/e2e_test.sh
*BREAKING*
This command group lets us begin splitting up image discovery from image signature creation/verification. Another subcommand I'm imagining is:
* `dockerfile resolve-images` which resolves `FROM image:tag`s to `FROM image@sha256:digest` and either outputs the list of image digests (e.g. for something like `cosign dockerfile resolve-images $FILE | xargs cosign verify`) or outputs a re-written file (to STDOUT or in-place).
> move `verify-dockerfile` to `dockerfile verify`

- cmd/cosign/cli/attach/sbom.go
- cmd/cosign/cli/download/sbom.go
- cmd/cosign/cli/sign.go
As I've been reading the code, I noticed a pretty consistent pattern of:
```go
// ref -> digest (nop if a digest!)
h, err := Digest(ctx, ref)
if err != nil {
return "", err
}
// ref -> repo (env var overrides!) 
repo, err := TargetRepositoryForImage(ref)
if err != nil {
return "", err
}
// construct tag with above and well-defined suffix.
dstRef := cosign.AttachedImageTag(repo, h, cosign.SBOMTagSuffix)
```
There were a handful of places missing the env variable override helper: `TargetRepositoryForImage`.
> Consistently use `TargetRepositoryForImage` with `AttachedImageTag`.

- cmd/cosign/cli/sign.go
I noticed this poking through the code.
> Move comments above the appropriate code sections.

- cmd/cosign/cli/attach/sbom.go
- cmd/cosign/cli/attach/sig.go
- cmd/cosign/cli/attest.go
- cmd/cosign/cli/clean.go
- cmd/cosign/cli/copy.go
- cmd/cosign/cli/download/sbom.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/triangulate.go
- cmd/cosign/cli/util.go
Following up on https://github.com/sigstore/cosign/pull/671 which identified a bunch of places we were incorrectly constructing the target tag name, this creates a helper that cuts this boilerplate down, since the majority of these call sites were following the exact same pattern and only computing the repo and hash for the tag construction.
> Create a helper to encapsulate a common pattern.

- cmd/cosign/cli/sign.go
- cmd/cosign/cli/verify.go
I noticed that we always parse the result of this method as a `name.Reference`, but along one of the paths we take a reference and stringify it!
This change makes `getAttachedImageRef` return a `name.Reference` and parses the input along the path where it wasn't already.
> Make `getAttachedImageRef` return a `name.Reference`

- cmd/cosign/cli/sign.go
1. Use the `DefaultRegistryClientOpts` which is a superset of what we use now, but sets `User-Agent`,
2. Pre-allocate the `toSign` array to have space for at least the number of images passed in (only more if recursive),
3. Use `Digest` to access the initial hash, which saves a `remote.Get` when we're passed a digest and non-recursive (at the cost of two requests when we are passed a tag in recursive mode),
4. Change the way we iterate over `toSign` to be conventional (not sure why we were doing it the other way before, but I'm guessing the two loops we now have were previously fused).
> Several cleanups to `SignCmd`

- .github/workflows/donotsubmit.yaml
This is a workflow I wrote for Knative, which is based on a presubmit check we had at Google.
Essentially, it fails the check (and flags the line) if it sees the words `DO NOT SUBMIT`.
So a comment practice with "work in progress" changes is to tag things that shouldn't get merged with:
```go
// TODO(mattmoor): DO NOT SUBMIT
```
Personally, I find this kind of workflow keeps me honest about things, so I thought I'd share!
N/A
```release-note
NONE
```
> Add a simple "DO NOT SUBMIT" workflow.

- .github/workflows/style.yaml
This change runs a few of the standard Go linting tools against PRs, and instead of just failing it annotates files that contain problems so users can run `gofmt -s -w <filename>` (or `goimports`).
The annotations look like this: https://github.com/sigstore/cosign/pull/680#issuecomment-920424768
This is a nice little hygiene check that we can use to keep things consistent.
This is based on the following, which we used in Knative: https://github.com/knative-sandbox/.github/blob/7d63e57ca2793794eef0b7a44035818f37f5f448/workflow-templates/knative-style.yaml#L26-L85
N/A
```release-note
NONE
```
> Run `gofmt -s` and `goimports` against PRs.

- .github/workflows/whitespace.yaml
This flags trailing whitespace at the ends of lines, and ensures there is a newline at the ends of files.
This is based on the following workflows we run in Knative: https://github.com/knative-sandbox/.github/blob/7d63e57ca2793794eef0b7a44035818f37f5f448/workflow-templates/knative-style.yaml#L160-L227
The annotations look like this: https://github.com/sigstore/cosign/pull/680#issuecomment-920424768
N/A
```release-note
NONE
```
> Add a little workflow that checks for whitespace.

- .github/workflows/tests.yaml
I noticed this adding other actions, and it seemed odd.  Looks like copy/pasta from some of the other actions that need it for h/w support.
I figure if it fails, we can just close this 🤣 
N/A
```release-note
NONE
```
> Try dropping dependency in `golangci-lint` leg.

- .golangci.yml
- cmd/cosign/cli/keys_test.go
This also fixes the only instance of `tparallel` found in a local run, and tightens up a test to avoid whitespace (I wish `gofmt -s` supported this 😞 ).
N/A
```release-note
NONE
```
> Enable several new `golangci-lint` checks.

- .golangci.yml
- cmd/cosign/cli/dockerfile/verify.go
- cmd/cosign/cli/verify_manifest.go
- copasetic/main.go
- pkg/cosign/attestation/attestation.go
- pkg/cosign/keys.go
- pkg/cosign/kubernetes/client.go
- pkg/cosign/remote/remote.go
- pkg/cosign/tlog.go
- pkg/cosign/verify.go
This mainly enables (and fixes) the `errorlint` checks.
This also fixes a handful of other things I noticed as I was passing through:
* `fmt.Errorf` without formatting -> `errors.New`
* `'%s'` -> `%q`
N/A
```release-note
NONE
```
> Enable `errorlint` checks.

- internal/oci/doc.go
- internal/oci/empty/empty.go
- internal/oci/empty/empty_test.go
- internal/oci/oci.go
- pkg/cosign/remote/remote.go
Cosign has it's own flavor of GGCR's `empty` package, which lets users toggle the media type we use with an environment variable.  This creates our own package to mirror this.
This also start to set up an `internal/` package structure that we can use to develop the new package structure without (yet) worrying about breaking folks downstream when we change things.
```release-note
NONE
```
> Create our very own `empty` package.

- release/cloudbuild.yaml
release: update cross build image to use go 1.17.1
release: https://github.com/gythialy/golang-cross/releases/tag/v1.17.1
Fixes
```release-note
release: update cross build image to use go 1.17.1
```
> release: update cross build image to use go 1.17.1

- cmd/cosign/cli/attach/sbom.go
- cmd/cosign/cli/attach/sig.go
- cmd/cosign/cli/attest.go
- cmd/cosign/cli/clean.go
- cmd/cosign/cli/copy.go
- cmd/cosign/cli/digest.go
- cmd/cosign/cli/download/sbom.go
- cmd/cosign/cli/download/signature.go
- cmd/cosign/cli/flags.go
- cmd/cosign/cli/generate.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign_blob.go
- cmd/cosign/cli/sign_test.go
- cmd/cosign/cli/triangulate.go
- cmd/cosign/cli/upload/blob.go
- cmd/cosign/cli/upload/wasm.go
- cmd/cosign/cli/util.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_attestation.go
- cmd/cosign/cli/verify_blob.go
- test/e2e_test.go
Fixes https://github.com/sigstore/cosign/issues/311
> add `-allow-insecure-registry` flag to permit unsecured container registries

- pkg/cosign/fetch.go
`remote.Get` is mainly useful when we may be dealing with an `Image` or `ImageIndex`, but in this case, we know we are dealing with an `Image`, so use `remote.Image`.
N/A
```release-note
NONE
```
> Use `remote.Image` instead of `remote.Get`.

- cmd/cosign/cli/verify_manifest.go
- cmd/cosign/cli/verify_manifest_test.go
Rather than using the known Kubernetes types, to extract images from inbound manifests using `cosign verify-manifest`, we can use a simple duck type to union the types into just the fields we need and extract the image fields directly. 
As a result of this change, we can now verify the manifests of things like Knative Serving.
Fixes https://github.com/sigstore/cosign/issues/679
```release-note
verify-manifest now supports verifying Jobs, and any other type that implements the PodSpec, PodSpecTemplate, or JobSpecTemplate shapes.
```
> cosign verify-manifest now supports Jobs and CRD Types that fit within PodSpec, PodSpecTemplate, or JobSpecTemplate

- cmd/cosign/cli/sign.go
- internal/oci/remote/remote.go
- internal/oci/remote/remote_test.go
- internal/oci/signatures.go
- pkg/cosign/fetch.go
- pkg/cosign/keys.go
- pkg/cosign/remote/remote.go
- pkg/cosign/tlog.go
- pkg/cosign/verify.go
Starting with `cosign.FetchSignaturesForImageDigest`, I am starting to peel out some of the existing logic, and try to define useful interfaces within `internal/oci.Signatures` and implement them in `internal/oci/remote.Signatures`.
This is still somewhat rough in parts, so I suspect that as we build it up, we will iterates on parts of it.
```release-note
NONE
```
> Start to flesh out `Signatures` and `internal/oci/remote`

- cmd/cosign/cli/attach/sig.go
- cmd/cosign/cli/attest.go
- cmd/cosign/cli/download/sbom.go
- cmd/cosign/cli/sign.go
- internal/oci/remote/remote.go
- internal/oci/signatures.go
1. Move `AttachedImageTag` calls closer to `UploadSignature` (and friends),
1. Make `sbom.go` use `remote.Signatures`,
1. Make `Signature` embed `v1.Layer`.
```release-note
NONE
```
> Several small changes.

- internal/oci/index.go
- internal/oci/interface.go
Starting to look at things like `remote.Get`, I realized that it will be possible for us to return either a `SignedImage` or `SignedImageIndex` and the caller can still access `Signatures()` and `Attestations()`.
Related: https://github.com/sigstore/cosign/pull/701
```release-note
NONE
```
> Define a shared `SignedEntity` interface.

- .github/workflows/milestone.yaml
I've been adding the milestone for some time, then now I think it's time to a bot assumes this 😄 
This PR adds a GitHub action that will run when we merge pull requests.
- it will add the milestone if the PR is merged and there is no milestone already associated 
If you find this useful, let's get this in and test and then I will add in the other repositories as well
```release-note
NONE
```
> ci/operations: add milestone applier

- internal/oci/remote/remote.go
- internal/oci/remote/remote_test.go
One of my previous changes switch from skipping `""` fetched from the map to using this syntax:
```go
blah, ok := themap[thekey]
if !ok {
...
}
```
However, it seems like there may be paths where we actually have these keys, but they contain empty string.
I'm seeing an index-out-of-bounds with both open PRs and HEAD trying to `cosign verify dockerfile` with `gcr.io/distroless/base`.
I'm sending this while I do a big more digging into the signatures there, but wanted to eliminate this delta quickly to avoid tripping others up.
```release-note
NONE
```
> Skip empty values, not just missing keys.

- cmd/cosign/cli/download/signature.go
- cmd/cosign/cli/util.go
- cmd/cosign/cli/util_test.go
- copasetic/main.go
- internal/oci/remote/options.go
- internal/oci/remote/options_test.go
- internal/oci/remote/remote.go
- internal/oci/remote/remote_test.go
- pkg/cosign/fetch.go
- pkg/cosign/verify.go
- test/e2e_test.go
This follows the pattern GGCR uses for functional `remote.Options`, and starts to define `SignedImage[Index]` methods, which build upon the `Signatures` implementation from a prior change.
This also tries to start adopting this pattern a few places, which drops bits of boilerplate (or changes them to functional options).
As part of this, I'm combining `FetchSignaturesForImage[Digest]` and tweaking it's signature a bit (no pun intended!), but I think long term we'll just want folks to consume the `remote` package directly themselves.
Related https://github.com/sigstore/cosign/issues/666
```release-note
NONE
```
> Start to sketch `internal/oci/remote.SignedImage[Index]`.

- cmd/cosign/cli/manifest/manifest.go
- cmd/cosign/cli/manifest/verify.go
- cmd/cosign/cli/manifest/verify_test.go
- cmd/cosign/main.go
- test/e2e_test.sh
A follow up to https://github.com/sigstore/cosign/pull/662 regarding the concerns brought up in https://github.com/sigstore/cosign/issues/437
```release-note
BREAKING: `verify-manifest` is now `manifest verify`
```
> move `verify-manifest` to `manifest verify`

- .github/workflows/milestone.yaml
the milestone workflow is not working because the PRs are from a fork and then the tempo token is not set, if we use the `pull_request_target` and limit the permissions for this workflow then this works
N/A
```release-note
NONE
```
> ci/operations: fixing milestone workflow, when running a fork the temp token is not set

- cmd/cosign/cli/download/signature.go
- copasetic/main.go
- pkg/cosign/fetch.go
- pkg/cosign/verify.go
- test/e2e_test.go
This is sort of a throwaway, since I want to kill this method, but I realized staring at it that it's a misnomer since it actually needs to handle `ImageIndex` as well today.  The name misled me into using `ociremote.SignedImage` here where I really wanted `ociremote.SignedEntity`.  Anyways, VS Code made it easy to change, so I changed it :D
N/A it's a nit
```release-note
NONe
```
> Rename `FetchSignaturesForImage` to `Reference`

- cmd/cosign/cli/download/sbom.go
- internal/oci/remote/options.go
- internal/oci/remote/options_test.go
- internal/oci/remote/remote.go
- internal/oci/remote/signatures.go
This was a TODO in the previous PR that introduces `ociremote.Option`.  This is mostly for consistency of these interfaces.
N/A
```release-note
NONE
```
> Have `Signatures` take `ociremote.Options`.

- internal/oci/empty/empty.go
- internal/oci/empty/empty_test.go
- internal/oci/remote/layer_test.go
- pkg/cosign/remote/remote.go
That's how it's used, and I need it for some of the `mutate` stuff I'm starting to look at.
This also changed `cremote.SignatureImage` to start using `ociremote.Signatures` and the `oci.Signatures` type very slightly (I stopped myself before scope creeping too badly).
```release-note
NONE
```
> Convert `empty.Image` to `empty.Signatures`

- internal/oci/signed/image.go
- internal/oci/signed/image_test.go
- internal/oci/signed/index.go
- internal/oci/signed/index_test.go
This package lets us cast (for lack of a better term) unsigned entities as signed entities with no signatures.
So with this, a user can write:
```go
si := signed.Image(img)
```
... and interact with the degenerate form of `oci.SignedImage` that has no signatures.
https://github.com/sigstore/cosign/issues/666
```release-note
NONE
```
> Introduce `signed.Image[Index]` to cast unsigned entities.

- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify_attestation.go
- copasetic/main.go
- pkg/cosign/verify.go
- pkg/sget/sget.go
I noticed that the only places we ever pass SignatureRepo to CheckOpts matches the default behavior that is already present within the library.
This drops that option, and cleans up the callers that were doing superfluous work.
N/A
```release-note
Removed the SignatureRepo from CheckOpts.  You can get the original behavior through the environment variable.
```
> Drop option that only passes default behavior.

- copasetic/main.go
- pkg/cosign/verify.go
These were only ever used to pass `options.WithContext(ctx)` and we have `ctx`, so we simply pass `ctx` to `VerifySignature` and pass `options.WithContext(ctx)` directly.
We were also inconsistent about whether we even passed `VerifyOpts` to `VerifySignature`, so now things are both simpler and more consistent.
N/A
```release-note
Retire VerifyOpts in CheckOpts, which was only used to pass `options.WithContext`
```
> Drop VerifyOpts from CheckOpts

- cmd/cosign/cli/verify/verify.go
- cmd/cosign/cli/verify/verify_attestation.go
- pkg/cosign/fetch.go
- pkg/cosign/verifiers.go
- pkg/cosign/verify.go
- pkg/sget/sget.go
There are a few cases here:
1. A few places these were simple enough "thunks" that it made sense to just inline them at the cost of a bit of redundancy.
2. I eliminated the unused `BundleVerified()` accessor and the backing state.
3. For `VerifyBundle` I made it take a `SignedPayload` instead (now that it had no state to mutate!).
Now that `SignedPayload` is *just* data, which is almost entirely a projection of accessors on `oci.Signatures`, a following change should be relatively trivial to eliminate `SignedPayload` entirely in favor of `oci.Signatures` :tada:
```release-note
SignedPayload's methods have been retired in favor of available helpers, and this type will be removed in a …
```
> Eliminate methods on `SignedPayload`.

- cmd/cosign/cli/verify/verify.go
- pkg/cosign/kubernetes/webhook/validation.go
- pkg/cosign/verifiers.go
- pkg/cosign/verify.go
- test/e2e_test.go
This changes most of the callers of `FetchSignaturesForReference` to use `ociremote.SignedEntity` directly, and eliminates essentially all usage of `SignedPayload` except one specific use case.
The places that remain calling `FetchSignaturesForReference` and using `SignedPayload` are marshalling the `SignedPayload` (one is in the cosign CLI, the other is copasetic and has rego references).
```release-note
NONE
```
> Switch most things to use `oci.Signature` directly.

- cmd/cosign/cli/verify/verify.go
- cmd/cosign/cli/verify/verify_attestation.go
- copasetic/main.go
- pkg/cosign/kubernetes/webhook/validation.go
- pkg/cosign/verify.go
- pkg/sget/sget.go
This out-param is a subtle code smell that had TODOs sprinkled no less than everywhere to remove it.
This adds a return value to `cosign.Verify` that indicates whether any bundles were verified, which is what this tracked, and updates call sites to utilize that.
```release-note
NONE
```
> Eliminate `BundleVerified` from `CheckOpts` in favor of new return value.

- cmd/cosign/cli/options/flags.go
- cmd/cosign/cli/verify/verify.go
- cmd/cosign/cli/verify/verify_attestation.go
- copasetic/main.go
- pkg/cosign/verify.go
- pkg/sget/sget.go
This is as a precursor to starting to fold some other stuff together, e.g. the SigSuffix option.
```release-note
NONE
```
> Switch `CheckOpts` to take `ociremote.Option`s.

- cmd/cosign/cli/verify/verify_attestation.go
- pkg/cosign/verify.go
As the title suggests, now that we take `ociremote.Option`, the `SigSuffix` option in CheckOpts is redundant.
```release-note
NONE
```
> Remove `SigSuffixOverride` fold into `ociremote.Option`.

- pkg/cosign/tlog.go
Minor change to move the inclusion proof  check for `nil` before dereferencing it.
```release-note
NONE
```
> Move check for nil before dereferencing InclusionProof

- internal/oci/remote/layer.go
- internal/oci/signatures.go
- pkg/cosign/remote/remote.go
This change has two main parts, the first is largely as the title indicates, which is to add an `Annotations()` method to `oci.Signature` (and our implementations thereof).  This is largely motivated by the second half of this change.
The second part of this change is starting to orient `UploadSignature` to operate in terms of our `oci` interfaces.  For a much longer-form version of the direction I'd like to drive this towards, see here: https://github.com/sigstore/cosign/issues/666#issuecomment-923609067.  This is a bit messier than I'd like, but I think it is progress towards the final form outlined in the issue since it starts to orient things like deduplication around the `oci.Signature` interface.
Related: Related: …
> Add `Annotations` to `oci.Signature`.

- internal/oci/static/options.go
- internal/oci/static/options_test.go
- internal/oci/static/signature.go
- internal/oci/static/signature_test.go
- pkg/cosign/keys.go
- pkg/cosign/remote/index.go
- pkg/cosign/remote/remote.go
This is to encapsulate the `staticLayer` functionality that lived alongside `Upload{Signature,File}`, which my previous change refactored a bunch.
This change really just moves stuff, but a subsequent change will likely try to start taking more advantage of this encapsulation.
```release-note
NONE
```
> Start building `internal/oci/static.New{Signature,File}`

- cmd/cosign/cli/attach/sig.go
- cmd/cosign/cli/attest.go
- cmd/cosign/cli/sign/sign.go
- pkg/cosign/remote/remote.go
Now that we have `static.NewSignature`, this shifts the construction out of `UploadSignature` and removes the elements passed via `UploadOpts` to simply be a part of the `NewSignature` call on the caller's side.
With this `UploadSignature` is starting to look pretty lean!
```release-note
NONE
```
> Make `UploadSignature` take an `oci.Signature`.

- cmd/cosign/cli/download/sbom.go
- internal/oci/remote/signatures.go
- internal/oci/remote/signatures_test.go
- pkg/cosign/fetch.go
- pkg/cosign/remote/remote.go
- test/e2e_test.go
The more I think about this semantics, the more I think it makes sense for it to be a native part of the library.
In places that are dealing with `SignedEntity` today, we more or less expect this semantic when we access their `Signatures`, and other places sort of do this already (e.g. `mutate.AppendManifests` implements `Signatures()` by returning `empty.Signatures()`).
Hopefully this will improve the DevX of the library a bit.
```release-note
NONE
```
> Move the `empty.Signatures()` on 404 semantic into the lib.

- cmd/cosign/cli/download/sbom.go
- cmd/cosign/cli/download/signature.go
- cmd/cosign/cli/generate/generate.go
- cmd/cosign/cli/triangulate.go
- cmd/cosign/cli/upload/wasm.go
I noticed a bunch of places were just reimplementing `regOpts.ClientOpts`, and noticed a couple other little cleanups as I was auditing calls:
* Have `GenerateCmd` call `image.Digest`
* Remove dead call in `wasm.go`
```release-note
NONE
```
> Do a pass cleaning up `regOpts.GetRegistryClientOpts`

- cmd/cosign/cli/attach/sig.go
- cmd/cosign/cli/attest.go
- cmd/cosign/cli/generate/generate.go
- cmd/cosign/cli/sign/sign.go
- internal/oci/remote/digest.go
- internal/oci/remote/digest_test.go
The only thing left in `pkg/image` was `Digest`, which potentially hits `remote.Get`.
This change introduces `ociremote.ResolveDigest`, which is similar, but takes our options and returns a `name.Digest` instead of a `v1.Hash`.
```release-note
NONE
```
> Migrate `image.Digest` to `ociremote.ResolveDigest`.

- cmd/cosign/cli/commands.go
- cmd/cosign/cli/options/root.go
- cmd/cosign/cli/options/sign.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign/sign.go
- cmd/cosign/main.go
Migrate `cosign sign` to a new cobra code path. Same options.
No option grouping yet. That will happen as we progress this process.
Relates to https://github.com/sigstore/cosign/issues/706
```release-note
NONE
```
> Migrate cosign sign to cobra

- .github/workflows/cross.yaml
- Makefile
During the release process, builds `sget` along cosign, signs, verifies
and publishes the binaries.
Fixes sigstore/cosign#725
> Add `sget` to the release artifacts

- .github/workflows/cross.yaml
After pushing sigstore/cosign#745, the signing/verifying mechanism for
the created binaries was broken. This patch fixes the issue and removes
the useless duplication, making the CI workflow DRYer.
> Fix the CI

- internal/oci/mutate/mutate.go
- internal/oci/mutate/mutate_test.go
- internal/oci/mutate/options.go
- pkg/cosign/remote/remote.go
These mutators attach a new `oci.Signature` to the `oci.Signatures` hanging off of an `oci.SignedEntity`.
A `DupeDetector` may optionally be passed via functional options, to elide the signature when a "dupe" already exists.
```release-note
NONE
```
> Add `mutate.SignEntity` and friends.

- internal/oci/remote/remote.go
- internal/oci/remote/write.go
- internal/oci/remote/write_test.go
This new method publishes the signatures associated with an `oci.SignedEntity` to a particular `name.Repository` in accordance with the `ociremote.Option`s, and the digest of the `oci.SignedEntity` with which it is affiliated.
WIP until https://github.com/sigstore/cosign/pull/761 lands
```release-note
NONE
```
> Add `ociremote.WriteSignatures`.

- cmd/cosign/cli/sign/sign.go
This change eliminates a whole bunch of the ad hoc index walking logic in favor of `mutate.Map`, and a handful of new library calls that let us attach a new signature, and then publish those signature.
This detailed comment lays out the plan: https://github.com/sigstore/cosign/issues/666#issuecomment-925459811, and this is very nearly what the code ended up being.
WIP until https://github.com/sigstore/cosign/pull/763 lands.  There is no way this is going to "just work" either, or I am going to throw some lego batman videos at y'all.
```release-note
NONE
```
> Migrate `SignCmd` to several new helpers.

- cmd/cosign/cli/sign/sign.go
- internal/oci/mutate/map.go
- internal/oci/walk/walk.go
- internal/oci/walk/walk_test.go
This adds a trivial `walk.SignedEntity` method that makes it easier to author read-only walks using `mutate.Map`.
```release-note
NONE
```
> Add a readonly variant of `mutate.Map`.

- cmd/cosign/cli/attach/sig.go
- cmd/cosign/cli/attest.go
- pkg/cosign/remote/remote.go
This was raised by Jake on one of my prior PRs that touched the adjacent code.
```release-note
```
> Rename `RemoteOpts` to `RegistryClientOpts` for consistency.

- cmd/cosign/cli/attach/sig.go
- pkg/cosign/remote/remote.go
This change retires `cremote.UploadSignature`, as this is the last caller of the old API, and it now uses the new API.
Related: #666
Related: #666
```release-note
./pkg/cosign/remote.UploadSignature API has been removed in favor of new ./pkg/oci/remote APIs
```
> Switch `attach` to new library.

- cmd/cosign/cli/options/sign.go
- cmd/cosign/cli/options/sign_test.go
When parsing annotations, there was a panic on new cobra codepath, fixing.
Related to #762 
```release-note
NONE
```
> fix panic on creating annotation maps.

- cmd/cosign/cli/attach/sbom.go
- cmd/cosign/cli/attach/sig.go
- cmd/cosign/cli/attest.go
- cmd/cosign/cli/generate/generate.go
- pkg/cosign/kubernetes/webhook/validation.go
- pkg/sget/sget.go
As I've been refactoring things, I noticed a handful of places where a single command potentially used a `name.Tag` multiple times for remote access.  There is an exceedingly small window here for a race to happen where the first tag access points to one image, and the subsequent access points to another.
I've already fixed a handful of these, and this change fixes one more (in `sget` IIRC), but also tries to add some defensive logic in a few places where we were already doing the right thing.
The defensive logic I added is to clobber `ref` with `digest` after resolving the reference:
```go
digest, err := ociremote.ResolveDigest(ref, regOpts.ClientOpts(ctx)...)
if err != nil {
return err
}
// Overwrite "ref" with a digest to avoid a race where we use a tag
// multiple times, and it …
```
> Ensure we resolve tags once.

- cmd/cosign/cli/commands.go
- cmd/cosign/cli/generate/generate_key_pair.go
- cmd/cosign/cli/generate_key_pair.go
- cmd/cosign/cli/options/generate_key_pair.go
- cmd/cosign/main.go
Migrate `cosign generate-key-pair` to cobra.
```release-note
NONE.
```
> Migrate generate-key-pair to cobra

- cmd/cosign/cli/attest.go
- pkg/oci/static/signature.go
- pkg/oci/static/signature_test.go
For attestations, the payload holds the signature, so we use an empty signature field.  This exposes a new constructor to hide that detail.
```release-note
NONE
```
> Create a `NewAttestation` constructor.

- cmd/cosign/cli/attest.go
- cmd/cosign/cli/verify/verify_attestation.go
- pkg/cosign/verify.go
- pkg/oci/interface.go
- pkg/oci/mutate/mutate.go
- pkg/oci/mutate/mutate_test.go
- pkg/oci/remote/image.go
- pkg/oci/remote/image_test.go
- pkg/oci/remote/index.go
- pkg/oci/remote/index_test.go
- pkg/oci/remote/remote.go
- pkg/oci/remote/write.go
- pkg/oci/remote/write_test.go
- pkg/oci/signed/image.go
- pkg/oci/signed/image_test.go
- pkg/oci/signed/index.go
- pkg/oci/signed/index_test.go
I know I just killed this off for being NYI, but I don't like the fact that we need `WithSignatureSuffix` to access things.
Related #666 
```release-note
NONE
```
> Try out `Attestations()`

- cmd/cosign/cli/verify/verify.go
- cmd/cosign/cli/verify/verify_attestation.go
- copasetic/main.go
- pkg/cosign/kubernetes/webhook/validation.go
- pkg/cosign/verify.go
- pkg/sget/sget.go
Previously, this was always `Signatures()`, but which sense of "signature" was nebulous (e.g. `.sig`, `.att`).
With this change, the interface here changes to take and accessor so folks explicitly specify which one they want, and I exposed `Verify{Signatures,Attestations}` methods with identical function signatures to what we exposed previously.
After this change, the only usage of `ociremote.WithSignatureSuffix` is some logic that deals with SBOMs, which it abusing things a bit, and the whole "attachment" thing is one of the next things I'm going to look at adding some abstraction for.
Related: #666 
```release-note
Changes the function signature of `cosign.Verify` so callers must be explicit about which signatures (or attestations) to …
```
> Rework `cosign.Verify` to specify what's verified.

- pkg/cosign/kubernetes/webhook/validation.go
- pkg/cosign/kubernetes/webhook/validator.go
I noticed this triaging our `name.ParseReference` calls, at a minimum this gets the call out of a loop, but I think it helps us surface better errors as well.
N/A
```release-note
NONE
```
> Hoist the `name.ParseReference` to avoid passing strings.

- cmd/cosign/cli/attest.go
- cmd/cosign/cli/attest/attest.go
- cmd/cosign/cli/commands.go
- cmd/cosign/cli/options/attest.go
- cmd/cosign/cli/options/predicate.go
- cmd/cosign/cli/public_key.go
- cmd/cosign/cli/publickey/public_key.go
- cmd/cosign/cli/publickey/public_key_test.go
- cmd/cosign/main.go
- test/e2e_test.go
- Migrate `cosign attest` to cobra.
- Move public-key command impl to a new folder.
```release-note
NONE.
```
> Migrating attest to cobra, moving public-key impl to folder

- cmd/cosign/cli/attest.go
- cmd/cosign/cli/generate_key_pair.go
- cmd/cosign/cli/init.go
- cmd/cosign/cli/public_key.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/signblob.go
- cmd/sget/cli/commands.go
Cobra provides a context, use it.
```release-note
NONE
```
> Use `cmd.Context()` everywhere.

- cmd/cosign/cli/commands.go
- cmd/cosign/cli/version.go
- cmd/cosign/main.go
Migrate `cosign version` to cobra.
```release-note
NONE
```
> Migrate cosign version to cobra

- cmd/cosign/cli/attest.go
- cmd/cosign/cli/commands.go
- cmd/cosign/cli/generate.go
- cmd/cosign/cli/generate_key_pair.go
- cmd/cosign/cli/options/annotations.go
- cmd/cosign/cli/options/attest.go
- cmd/cosign/cli/options/fulcio.go
- cmd/cosign/cli/options/generate.go
- cmd/cosign/cli/options/oidc.go
- cmd/cosign/cli/options/options.go
- cmd/cosign/cli/options/predicate.go
- cmd/cosign/cli/options/public_key.go
- cmd/cosign/cli/options/rekor.go
- cmd/cosign/cli/options/root.go
- cmd/cosign/cli/options/security_key.go
- cmd/cosign/cli/options/sign.go
- cmd/cosign/cli/options/signblob.go
- cmd/cosign/cli/public_key.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/signblob.go
- cmd/sget/cli/commands.go
- cmd/sget/cli/options/root.go
See discussion on this PR: https://github.com/sigstore/cosign/pull/781#discussion_r715904414
```release-note
NONE
```
> Migrate to `AddFlags` pattern.

- cmd/cosign/cli/attach/sbom.go
> Actually use `types.MediaType`, drop useless cast.

- cmd/cosign/cli/upload/blob.go
- pkg/cosign/remote/index.go
Previously this defined and returned a `Digester`, and constructed the digest using the ref that was passed in.  It simplifies things a bunch to just have `UploadFiles` return the digest of the thing it uploaded.
```release-note
NONE
```
> Change `UploadFiles` to return a `name.Digest`.

- cmd/cosign/cli/attest/attest.go
- pkg/cosign/remote/index.go
- pkg/oci/file.go
- pkg/oci/static/file.go
- pkg/oci/static/file_test.go
- pkg/oci/static/options.go
- pkg/oci/static/options_test.go
- pkg/oci/static/signature.go
- pkg/oci/static/signature_test.go
This type is currently just an alias for `v1.Image`, which is the unit of storage we use for files uploaded with `UploadFile[s]`.
This changes `static.NewFile` to create an `oci.File` (full image vs. just the layer previously), and `UploadFile` to use this (it's where the rest of the image came from).
Related: #666
```release-note
NONE
```
> Define `oci.File`.

- cmd/cosign/cli/sign/sign.go
- cmd/cosign/cli/verify/verify.go
Generally I prefer to have functions take/return structured types where possible, so this changes `GetAttachedImageRef` to require the caller to sanitize the input and pass the `name.Reference`.
N/A
```release-note
NONE
```
> Have `GetAttachedImageRef` take `name.Reference`.

- cmd/cosign/cli/attach/sbom.go
- cmd/cosign/cli/upload/wasm.go
- pkg/cosign/remote/index.go
This can now be done in terms of `static.NewFile` and `remote.Write`, which is simply enough to just inline.
_WIP until https://github.com/sigstore/cosign/pull/796 merges and this is rebased._
Related #666
```release-note
Remove cremote.UploadFile in favor of static.NewFile and remote.Write
```
> Eliminate `cremote.UploadFile`.

- pkg/cosign/kubernetes/webhook/validation.go
- pkg/cosign/kubernetes/webhook/validator.go
- pkg/cosign/kubernetes/webhook/validator_test.go
This change makes `cosigned` reject tag references, which can drift after validation has occured rendering the validation we perform ineffective.
This also adds unit test coverage for the bulk of the `webhook` package.
A subsequent change will introduce a mutating webhook that resolves tags to digests (we still need to validating webhook due to webhook ordering).
Related: https://github.com/sigstore/cosign/issues/784
```release-note
The cosigned webhook now requires digest references to validate references.
```
> Reject tags in `cosigned`.

- .github/workflows/kind-e2e-cosigned.yaml
- cmd/cosign/webhook/main.go
- config/200-clusterrole.yaml
- config/500-webhook-configuration.yaml
- pkg/cosign/kubernetes/webhook/validator.go
- pkg/cosign/kubernetes/webhook/validator_test.go
- test/e2e_test_cosigned.sh
This change introduces a mutating webhook to complement our validating webhook.
The validating webhook in #799 began rejecting tag reference because tags are mutable and can drift between validation and resolution by the kubelet.  This change introduces a mutating webhook that resolves tags to digests as resources are created, so that users aren't necessarily forced to provide digests, but we get the benefits of them nonetheless.
Fixes: https://github.com/sigstore/cosign/issues/784
```release-note
cosigned now includes a mutating webhook that resolves tags to digests
```
> Add digest resolution to `cosigned`.

- pkg/cosign/kubernetes/webhook/validator.go
- pkg/cosign/kubernetes/webhook/validator_test.go
This changes the `cosigned` webhook to ignore things that are being cleaned up.
As resources are cleaned up in Kubernetes (typically things with finalizers), they are first tombstoned by setting `metadata.deletionTimestamp` and once the finalizers have fully executed they are actually deleted.
To the webhook, these look like `UPDATE` operations, but are distinguishable because we can check for this field.
This also adds unit test coverage for the `duckv1.Pod` and `duckv1.WithPod` wrappers around the core validation and resolution logic.
```release-note
The cosigned webhook now ignores resources that are being deleted.
```
> Don't block things being deleted.

- pkg/cosign/remote/index.go
The logs of a failure are here: https://github.com/sigstore/cosign/runs/3705988573#step:5:492
The problem here is that when I changed the return value to be the `name.Digest`, I was setting `lastHash` to the `v1.Layer` hash, not the `v1.Image` hash, so when the post-submit job tried to sign the resulting digest things exploded.
This change properly sets `lastHash` to the `v1.Image` hash, and uses a separate `layerHash` variable for the layer's digest for the download print statement we print.
```release-note
NONE
```
> Fix the postsubmit failure introduced by #795

- cmd/cosign/cli/copy/copy.go
- cmd/cosign/cli/options/copy.go
- test/e2e_test_secrets.sh
* Fixed regression in `copy`
* `-key` -> `--key`. Prevents the e2e script from throwing a ton of warnings
```release-note
NONE
```
> Fix e2e postsubmit

- cmd/cosign/cli/commands.go
- cmd/cosign/cli/initialize.go
- cmd/cosign/cli/initialize/init.go
- cmd/cosign/cli/options/initialize.go
- cmd/cosign/cli/options/triangulate.go
- cmd/cosign/cli/triangulate.go
- cmd/cosign/cli/triangulate/triangulate.go
- cmd/cosign/main.go
- Migrate `cosign initialize` to cobra.
- Migrate `cosign triangulate` to cobra.
```release-note
NONE
```
> Migrate triangulate and initialize to cobra

- cmd/cosign/cli/attest.go
- cmd/cosign/cli/clean.go
- cmd/cosign/cli/commands.go
- cmd/cosign/cli/copy.go
- cmd/cosign/cli/generate.go
- cmd/cosign/cli/options/annotations.go
- cmd/cosign/cli/options/files.go
- cmd/cosign/cli/options/upload.go
- cmd/cosign/cli/public_key.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/signblob.go
- cmd/cosign/cli/upload.go
- cmd/cosign/cli/upload/blob.go
- cmd/cosign/cli/upload/upload.go
- cmd/cosign/cli/upload/wasm.go
- cmd/cosign/main.go
- pkg/cosign/remote/index.go
- pkg/cosign/remote/index_test.go
- Migrate `cosign upload ...` to cobra.
- Leverage cobra input validation on all other commands.
```release-note
NONE
```
> Migrate upload tree to cobra

- cmd/cosign/cli/commands.go
- cmd/cosign/cli/options/policy.go
- cmd/cosign/cli/policy_init.go
- cmd/cosign/cli/policy_init_test.go
- cmd/cosign/main.go
- go.mod
- pkg/cosign/tuf/policy.go
- pkg/cosign/tuf/policy_test.go
- pkg/cosign/tuf/signer.go
Hoping to iterate on this. This only initializes the root policy. We need to:
* Add the sign command
* Add ISSUER information to trust?
Replaces/uses code from
- https://github.com/sigstore/cosign/pull/366
- https://github.com/sigstore/cosign/pull/407
Current usage:
`./cosign policy-init --namespace gcr.io/asra-ali/busybox --maintainers asraa@google.com,lukehinds@redhat.com --threshold 2 --out root.json`
```
./cosign policy-init --namespace gcr.io/asra-ali/busybox --maintainers asraa@google.com,lukehinds@redhat.com --threshold 2 --out root.json
Uploading file from [root.json] to [gcr.io/asra-ali/busybox/root.json:latest] with media type [text/plain]
File [root.json] is available directly at …
```
> Add a policy-init using TUF metadata and Fulcio signers

- cmd/cosign/cli/commands.go
- cmd/cosign/cli/download.go
- cmd/cosign/cli/download/download.go
- cmd/cosign/cli/download/sbom.go
- cmd/cosign/cli/download/signature.go
- cmd/cosign/main.go
- Migrates `cosign download ...` subtree to cobra.
```release-note
NONE
```
> Migrate download subtree to cobra

- cmd/cosign/cli/attach.go
- cmd/cosign/cli/attach/attach.go
- cmd/cosign/cli/attach/sbom.go
- cmd/cosign/cli/attach/sig.go
- cmd/cosign/cli/commands.go
- cmd/cosign/cli/options/attach.go
- cmd/cosign/main.go
- migrate `cosign attach ...` subtree to cobra.
```release-note
NONE.
```
> Migrate the attach command tree to cobra

- cmd/cosign/cli/sign/sign.go
allow to answer both "Y" and "y" when signing a docker image using cosign
before
```
warning: uploading to the transparency log at https://rekor.example.com for a private image, please confirm [Y/N]: Y
tlog entry created with index:  1
```
```
warning: uploading to the transparency log at https://rekor.example.com for a private image, please confirm [Y/N]: y
not uploading to transparency log
```
after
```
warning: uploading to the transparency log at https://rekor.example.com for a private image, please confirm [Y/N]: Y
tlog entry created with index:  1
```
```
warning: uploading to the transparency log at https://rekor.example.com for a private image, please confirm [Y/N]: y
tlog entry created with index:  2
```
Fixes
```release-note
```
> Allow both lower and upper cases in transparency commit confirmation

- .github/workflows/cross.yaml
- .goreleaser.yml
- EXAMPLES.md
- FUN.md
- KMS.md
- Makefile
- README.md
- TOKENS.md
- USAGE.md
- cmd/cosign/cli/copy.go
- cmd/cosign/cli/manifest.go
- cmd/cosign/cli/signblob.go
- cmd/sget/cli/commands.go
- test/e2e_test.sh
- test/e2e_test_cosigned.sh
- test/e2e_test_insecure_registry.sh
- test/e2e_test_secrets.sh
find and fix examples where we are using the single dash style flags.
```release-note
`cosign` now uses POXIS style flags.
```
> find and fix examples where we are using the single dash style flags.

- cmd/cosign/cli/attest.go
- cmd/cosign/cli/options/attest.go
Fixes
* Fixes a bug with the `attest` command where the rekor URL was not passed in.
Previous behavior:
```
COSIGN_EXPERIMENTAL=1 ./cosign attest --predicate example.txt --key cosign.key --type custom gcr.io/asra-ali/busybox/demo --force
Using payload from: example.txt
Error: signing gcr.io/asra-ali/busybox/demo: Post "http:///api/v1/log/entries": http: no Host in request URL
```
```release-note
```
> Fix attest bug with rekor URL

- .github/workflows/tests.yaml
- .github/workflows/verify-docgen.yaml
Noticed while developing #839 
With the previous config, CI would run in my forked repo on any push to a branch while iterating on a PR. Since this also ran CI while the PR was open on this repo, any failure would result in two notifications.
With this change, CI tests will only run on pushes to `main` or release branches, and on PRs to this repo or forked repos. Since most pushes to forked repos are (presumably) to non-`main` branches, this should only cause runs on active PRs.
n/a
```release-note
NONE
```
> Only run CI on PRs and push to main or releases

- Makefile
This makes it so naked `make` does the expected thing
> move `make help` below the default rules

- cmd/cosign/cli/attest/attest.go
- cmd/cosign/cli/options/predicate.go
- doc/cosign_attest.md
- pkg/cosign/attestation/attestation.go
Signed-off-by: Jim Bugwadia <jim@nirmata.com>
Fixes https://github.com/sigstore/cosign/issues/846.
This PR allows users to specify a custom predicate and supply any JSON data:
```sh
./cosign attest --predicate ~/predicate.json --type https://example.com/CodeReview/v1 --key ~/cosign.key <image>
```
where `predicate.json` is:
```json
{                                                       
"repo": {                                           
"type": "git",                                    
"uri": "https://github.com/example/my-project",   
"branch": "main"                                  
},                                                  
"author": "mailto:alice@example.com",               
"reviewers": ["mailto:bob@example.com"]             
} …
```
> support user customizable predicates

- pkg/cosign/pivkey/pivkey.go
https://pkg.go.dev/crypto#PublicKey
`type PublicKey interface{}` 😢
```release-note
Bugfix: `cosign public-key -sk` causing  `error: x509: unsupported public key type: *crypto.PublicKey`
```
> fix `x509: unsupported public key type: *crypto.PublicKey`

- cmd/cosign/cli/attach/sig.go
- cmd/cosign/cli/attest/attest.go
- cmd/cosign/cli/download/sbom.go
- cmd/cosign/cli/download/signature.go
- cmd/cosign/cli/generate/generate.go
- cmd/cosign/cli/options/registry.go
- cmd/cosign/cli/sign/sign.go
- cmd/cosign/cli/triangulate/triangulate.go
- cmd/cosign/cli/verify/verify.go
- cmd/cosign/cli/verify/verify_attestation.go
- pkg/oci/remote/digest.go
- pkg/oci/remote/image.go
- pkg/oci/remote/index.go
- pkg/oci/remote/options.go
- pkg/oci/remote/options_test.go
- pkg/oci/remote/remote.go
- pkg/oci/remote/remote_test.go
- pkg/oci/remote/signatures.go
- pkg/oci/remote/write.go
At some point in the refactoring `COSIGN_REPOSITORY` magic was reintroduced to `pkg/`. This change makes its usage explicit for library users again.
> make `COSIGN_REPOSITORY` use explicit again

- cmd/cosign/cli/generate/generate_key_pair.go
- cmd/cosign/cli/generate_key_pair.go
- doc/cosign_generate-key-pair.md
- go.mod
- go.sum
- pkg/cosign/git/git.go
- pkg/cosign/git/github/github.go
- pkg/cosign/git/gitlab/gitlab.go
- pkg/cosign/kubernetes/secret.go
Signed-off-by: Erkan Zileli <erkan.zileli@trendyol.com>
Co-authored-with: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Co-authored-with: Furkan Türkal <furkan.turkal@trendyol.com>
Fixes: #838
cc: @Dentrax @developer-guy
> add github&gitlab reference support to generate-key-pair

- pkg/cosign/kubernetes/webhook/validator.go
- pkg/cosign/kubernetes/webhook/validator_test.go
```
invalid image signature: spec.jobTemplate.spec.template.spec.containers[0].image
gcr.io/distroless/static:nonroot@sha256:be5d77c62dbe7fedfb0a4e5ec2f91078080800ab1f18358e5f31fcc8faa023c4
```
Fixes
closes https://github.com/sigstore/cosign/issues/873
```release-note
* Include image name on cosigned rejections
```
> cosigned: add image name to the error messages when having an invalid signature

- .github/workflows/build.yaml
- .github/workflows/kind-e2e-cosigned.yaml
- .github/workflows/tests.yaml
we can use the `go install` with the `GOBIN` option to install ko under `/usr/local/bin` safelly.
QA Test Steps:
```shell
$ GOOGLE_KO_DIR=$(pwd)/bin 
$ GOOGLE_KO_BIN=$GOOGLE_KO_DIR/ko
$ GOBIN=$(GOOGLE_KO_BIN) go install github.com/google/ko@v0.9.3
```
Fixes #888 
```release-note
fix: safer way to install google/ko
```
> fix: safer way to install google/ko

- pkg/cosign/git/gitlab/gitlab.go
Use the documented environment variable GITLAB_HOST instead of GITLAB_BASE_URL to point to your own Gitlab instance, as suggested in https://docs.gitlab.com/ee/administration/environment_variables.html.
Fixes
```release-note
* Use GITLAB_HOST to point to a custom Gitlab server
```
> fix: use GITLAB_HOST env var name

- .github/workflows/github-oidc.yaml
This demonstrates building a container image consisting of a Go binary
(cmd/cosign in this case), pushing it to a registry, and signing it
using ambient GitHub OIDC credentials available in the GitHub Actions
build environment.
This should serve as a runnable/forkable demo, and also a test to guard
against breakages.
Because permission to push packages is not available to workflow runs
started by PRs, this action runs on pushes to main, and on a nightly
basis.
```release-note
NONE
```
cc @mattmoor
> Add a test/example for signing using GitHub OIDC

- .github/workflows/e2e_tests.yml
`go install` without a version specified installs the latest semver release of the tool. This means that a compromise of the go-containerregistry repo could result in arbitrary code running in this workflow, e.g., when e2e tests invoke `crane ls`.
With a version specified, even if the repo moves the `v0.6.0` tag to another commit, the Go module proxy will serve the previous v0.6.0 code.
v0.6.0 is the latest release of crane: https://github.com/google/go-containerregistry/releases
```release-note
NONE
```
> Pin crane dependency used in e2e tests

- cmd/cosign/cli/attest/attest.go
- pkg/cosign/attestation/attestation.go
Per a discussion with @dekkagaijin, this PR makes an incremental change to help consumers of cosign's attestation functions, specifically by allowing the caller of `attestation.GenerateStatement` to provide **any** `io.Reader` implementation  as the statement's predicate, rather than having the caller provide a file _path_. This allows consumers to control the source of the predicate bytes, which is particularly valuable for non-file predicate sources, such as bytes existing only in memory.
(Takes one step forward on sigstore/cosign#844)
```release-note
NONE
```
> Replace predicate file path with io.Reader

- pkg/oci/empty/signed.go
This was missing from #857, which WAS green, so HEAD is broken until this lands.
Fixes: #857
```release-note
NONE
```
> Add Attachment to empty.

- cmd/cosign/cli/attest.go
- cmd/cosign/cli/options/attest.go
- cmd/cosign/cli/options/sign.go
- doc/cosign_attest.md
Without this, I get the following (back to 1.0):
```
Error: signing gcr.io/mattmoor-credit/sbom@sha256:faef0ba9f497e26509d9f72f9ece7016b0e36edcb34ea3d3afe04f4bb2b01c5d: getting signer: getting key from Fulcio: retrieving cert: Get "/.well-known/openid-configuration": unsupported protocol scheme ""
main.go:48: error during command execution: signing gcr.io/mattmoor-credit/sbom@sha256:faef0ba9f497e26509d9f72f9ece7016b0e36edcb34ea3d3afe04f4bb2b01c5d: getting signer: getting key from Fulcio: retrieving cert: Get "/.well-known/openid-configuration": unsupported protocol scheme ""
exit status 1
```
With this change, it gets further, but there are still issues:
```
Error: signing gcr.io/mattmoor-credit/sbom@sha256:faef0ba9f497e26509d9f72f9ece7016b0e36edcb34ea3d3afe04f4bb2b01c5d: [POST …
```
> Add the OIDC options to `AttestOptions`.

- FUN.md
I filled in the last section of this doc! Let me know if I didn't do this the intended way 😅
> Add keyless signing w/ storage in rekor to FUN.md

- pkg/cosign/kubernetes/webhook/validator.go
The k8schain error path wasn't returning the error!  This means that when k8schain is improperly configured, images will be let through.
```release-note
```
> Return k8schain error.

- cmd/cosign/cli/attach/sbom.go
Currently the env var is ignored by this command because it directly uses GGCR registry options instead of the `ociremote` options (which include the default override).
This fixes things by passing the `ociremote` options from `regOpts` to `SBOMTag`.
Thanks to @vaikas for finding this.
```release-note
Fixes COSIGN_REPOSITORY with `cosign attach sbom`
```
> Fix `cosign attach sbom` with `COSIGN_REPOSITORY`.

- Makefile
This will direct `ko` to build `cosign` et al for all of the platforms and architectures that the configured base image ships, so for distroless that should include arm, arm64, ppc64le, s390z, and ofc amd64.
```release-note
The cosign images are now shipped for every architecture distroless ships on (currently: amd64, arm64, arm, s390x, ppc64le)
```
> Ship multi-arch images for all the cosign components.

- .goreleaser.yml
The modtime setting was missing that was required for making goreleaser builds consistent.
> Fixed modtime for reproducible goreleaser

- .github/workflows/build.yaml
- .github/workflows/cross.yaml
- .github/workflows/tests.yaml
This PR removes some potentially confusing commented out sections in some CI configs.
These sections were commented out in https://github.com/sigstore/cosign/pull/332
```release-note
NONE
```
> Remove commented out sections in CI configs

- cmd/cosign/cli/attach/sbom.go
- cmd/cosign/cli/attach/sig.go
- cmd/cosign/cli/fulcio/fulcioroots/fulcioroots.go
- cmd/cosign/cli/generate/generate_key_pair.go
- cmd/cosign/cli/manifest/verify.go
- cmd/cosign/cli/policy_init.go
- cmd/cosign/cli/publickey/public_key_test.go
- cmd/cosign/cli/sign/sign.go
- cmd/cosign/cli/sign/sign_blob.go
- cmd/cosign/cli/upload/wasm.go
- cmd/cosign/cli/verify/verify_blob.go
- pkg/cosign/git/github/github.go
- pkg/cosign/git/gitlab/gitlab.go
- pkg/cosign/kubernetes/secret.go
- pkg/cosign/pivkey/pivkey.go
- pkg/cosign/remote/index.go
- pkg/oci/remote/layer.go
- pkg/oci/static/signature.go
- pkg/providers/google/google.go
- pkg/signature/keys.go
- pkg/signature/keys_test.go
- test/e2e_test.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
N/A
```release-note
NONE
```
> refactor: move from io/ioutil to io and os packages

- cmd/cosign/cli/attest.go
- cmd/cosign/cli/attest/attest.go
- cmd/cosign/cli/options/attest.go
- doc/cosign_attest.md
- test/e2e_test.go
The `cosign attest` command has an `--upload` flag, designed to tell cosign to upload the generated attestation to the registry.
However, this bool value is set to `true` by default, which ends up meaning that **there's no way to instruct cosign _not to upload_** the generated attestation (IIUC).
This PR changes the flag to `--no-upload`, which inverts the logic and behaves as you'd expect. Without the flag, the attestation is uploaded. With the flag, the attestation is not uploaded, and instead, the attestation DSSE is sent to stdout.
**Note:** This is a breaking change for the CLI, since it removes an existing flag. The flag hadn't been affecting cosign's execution, so I'm not sure how many folks were using it. But regardless, I'm happy to approach this a different way to make the …
> Invert upload flag to allow for not uploading attestation

- .github/workflows/validate-release.yml
- .goreleaser.yml
- Dockerfile
- Dockerfile.cosigned
- Dockerfile.sget
- Makefile
- release/cloudbuild.yaml
* `ghcr.io/gythialy/golang-cross:v1.17.2` -> `v1.17.2-1`
* Fixes the release maybe?
Release is getting the error:
```
...
Step #5:       • signing                   artifact=sget-darwin-arm64 cmd=./dist/cosign-linux-amd64
Step #5:    • docker images            
Step #5:       • building docker image     image=gcr.io/projectsigstore/cosigned:1.3.0-arm64v8
Step #5:       • building docker image     image=gcr.io/projectsigstore/sget:1.3.0-arm64v8
Step #5:       • building docker image     image=gcr.io/projectsigstore/cosign:1.3.0-arm64v8
Step #5:       • building docker image     image=gcr.io/projectsigstore/sget:1.3.0-amd64
Step #5:       • building docker image     image=gcr.io/projectsigstore/cosigned:1.3.0-amd64
Step #5:       • building docker image …
```
> Fix the release

- cmd/cosign/cli/verify/verify_blob.go
- pkg/cosign/tlog.go
- pkg/cosign/verify.go
When a user has opted into keyless mode, and they have signed a blob, allow a user to verify a blob without having to specify a certificate.
questions / concerns:
- Currently, the first certificate found in the tlog (for the blob) is used when verifying. However, this might not be the correct cert to use when verifying. I'm not sure what the *best* ux around this should be. Perhaps a new flag should be introduced to help narrow down which cert is used to verify the blob.  (Allow the user to specify a subject / email address?) or perhaps cosign should loop through all the certificates it finds and attempt to verify the blob + sig against each one (this has performance implications)
- where is a good place to add tests?
Aims to improve …
> Add ability for verify-blob to find signing cert in transparency log

- cmd/cosign/cli/options/policy.go
- cmd/cosign/cli/policy_init.go
- cmd/cosign/cli/verify/verify.go
- doc/cosign_policy_init.md
- pkg/cosign/tuf/policy.go
- pkg/cosign/tuf/policy_test.go
- pkg/cosign/tuf/signer.go
- pkg/signature/keys.go
* Adds an optional issuer to the trusted maintainer keys (e.g. we trust asraa@google.com with issuer https://accounts.google.com) now that the issuer is added to the Fulcio certificate. If a maintainer signs with a different issuer than one specified, then signing fails (test added). If no issuer is specified, then anything goes.
Fixes
```release-note
```
Sample root policy:
```
{
"signatures": [
{
"cert": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNuakNDQWlXZ0F3SUJBZ0lUZXZRcVc2NEFZb0ZqcE9Zc2l6eGxrenAzNHpBS0JnZ3Foa2pPUFFRREF6QXEKTVJVd0V3WURWUVFLRXd4emFXZHpkRzl5WlM1a1pYWXhFVEFQQmdOVkJBTVRDSE5wWjNOMGIzSmxNQjRYRFRJeApNVEV3TkRFNU1UVXlPVm9YRFRJeE1URXdOREU1TXpVeU9Gb3dBREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5CkF3RUhBMElBQk1TZ0o3WGR0K00wcmgwa2VHTERZaWlCUjBiRW …
```
> root policy: add optional issuer to maintainer keys

- .github/workflows/kind-e2e-cosigned.yaml
- .github/workflows/validate-release.yml
- .goreleaser.yml
- .ko.yaml
- Makefile
- release/cloudbuild.yaml
- release/release.mk
- test/ci.mk
- test/e2e_test.sh
- add more platforms when building the binaries
- use ko to build/push the container images
n/a
```release-note
refactor release process to use ko to build the images
```
> refactor release process to use ko to build the images

- cmd/cosign/cli/attest.go
- cmd/cosign/cli/attest/attest.go
- cmd/cosign/cli/options/attest.go
- cmd/cosign/cli/options/policy.go
- cmd/cosign/cli/options/signblob.go
- cmd/cosign/cli/policy_init.go
- cmd/cosign/cli/sign/sign.go
- cmd/cosign/cli/sign/sign_blob.go
- cmd/cosign/cli/signblob.go
- doc/cosign_attest.md
- doc/cosign_policy_sign.md
- doc/cosign_sign-blob.md
- pkg/cosign/tlog.go
- test/e2e_test.go
Included a `timeout` option to `sign-blob` because uploading a large binary to `rekor` was failing with timeout.
https://github.com/sigstore/cosign/issues/990
> Included timeout option for uploading to Rekor

- cmd/cosign/cli/verify.go
- doc/cosign_verify-blob.md
Co-authored-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Signed-off-by: Erkan Zileli <erkan.zileli@trendyol.com>
An existing option is documented with an example on the verify-blob command.
Fixes
```release-note
```
> fix(doc): add an example for existing option on verify-blob command

- .github/workflows/github-oidc.yaml
- test/ci.mk
the oidc tests are broken after we make the changes in how to build the images using `ko` and adding some definitions
n/a
```release-note
ci: update oidc ci tests
```
> ci: update oidc ci tests

- .github/workflows/github-oidc.yaml
followup of https://github.com/sigstore/cosign/pull/1029 to fix the bad env var being set https://github.com/sigstore/cosign/runs/4178064242?check_suite_focus=true
from the logs
```
cosign sign -a sha=ITHUB_SHA -a run_id=1448802534 -a run_attempt=1 ghcr.io/sigstore/cosign/cosign:ITHUB_SHA
```
n/a
```release-note
NONE
```
> fix variable

- cmd/cosign/cli/attest.go
- doc/cosign_attest.md
Fix the help message for preventing uploads when using `attest`. Flag is commented as `upload` when in fact it is `no-upload`.
Though for consistency I think it would be better if it actually did use the `upload` so it would be the same as with `sign` command. But I wasn't sure if we wanted to break the backward compatibility, so just fixed the doc for now. I'd be happy to make them consistent however if that's what we would like to do.
attest: https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/options/attest.go#L58
sign: https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/options/sign.go#L57
Fixes
```release-note
Fix the attest command help msg to document the proper flag (no-upload vs upload).
```
> fix help msg upload=>no-upload

- cmd/cosign/cli/verify/verify.go
- cmd/cosign/cli/verify/verify_attestation.go
- pkg/cosign/kubernetes/webhook/validation.go
- pkg/cosign/verify.go
- pkg/sget/sget.go
This is a first pass to begin disentangling and refactoring our verification flow to make it more usable, plugable, and extensible. Behavior should remain unchanged.
Starts addressing https://github.com/sigstore/cosign/issues/844 and https://github.com/sigstore/cosign/issues/931 
```release-note
[cosign/pkg]: `cosign.Verify` has been removed in favor of explicit `cosign.VerifyImageSignatures` and `cosign.VerifyImageAttestations`
```
> remove `Verify` in favor of explicit `VerifyImage{Signatures, Attestations}`

- cmd/cosign/cli/verify/verify_attestation.go
validate whole statement not just predicate part
Fixes #1012
```release-note
feat: validate whole statement not just predicate part
```
> feat: validate whole statement not just predicate part

- test/e2e_test_cosigned.sh
This isn't great, but works. This adds two non-used keys to the list
on top of the actual signing key. This would have failed without #942.
Fixes
```release-note
```
> Adds a test to the cosigned e2e suite with multiple keys.

- go.mod
- go.sum
GGCR does not rely on the vulnerable codepath, but this PR updates the indirect dependency to avoid findings related to [CVE-2021-41092](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-41092)
```release-note
NONE
```
> update ggcr to HEAD to eliminate (false) vuln finding

- cmd/cosign/cli/sign/sign.go
This PR fixes a wrong check for when the PKCS11 certificate does not exist.
Fixes [#1037](https://github.com/sigstore/cosign/issues/1037)
```release-note
```
> PKCS11: Fix certificate check

- pkg/cosign/verify.go
> split private signature and attestation verification fns

- cmd/cosign/cli/verify/verify_blob.go
Before this commit, the verify-blob command would fail ungracefully in experimental mode
if no signature has been provided. This commit adds a better fitting error message.
```
❯ COSIGN_EXPERIMENTAL=1  cosign verify-blob /tmp/hello-world.txt
Error: verifying blob [/tmp/hello-world.txt]: read .: is a directory
main.go:46: error during command execution: verifying blob [/tmp/hello-world.txt]: read .: is a directory
```
```
❯ COSIGN_EXPERIMENTAL=1  cosign verify-blob /tmp/hello-world.txt
Error: verifying blob [/tmp/hello-world.txt]: missing flag '--signature'
main.go:46: error during command execution: verifying blob [/tmp/hello-world.txt]: missing flag '--signature'
```
None
```release-note
Fixed: verify-blob error message for missing signature flag
```
> verify-blob: make the signature flag mandatory

- pkg/cosign/tlog.go
- pkg/cosign/verify.go
Signed-off-by: houdini91 <mdstrauss91@gmail.com>
Hi guys.
My first PR to cosign hope i am not misunderstanding something critical.
PR is a patch to the rekor validation flow when using attestation.
1) When bundle is not present searching for intoto rekor entries would fail because of search was using in to the wrong entry type (rekord vs intoto).
2) When verifying the attached rekor Bundle the certificate expire was checked and the validity of the bundle signiture.
I added a  hash test between the bundle content hash and actual payload hash.
I am not sure if the idea is to verify the bundle actual body is the responsibility of the policy.
> Patch support attestation log search and bundle to payload hash check

- Makefile
- cmd/cosign/cli/attest.go
- cmd/cosign/cli/attest/attest.go
- cmd/cosign/cli/options/attest.go
- doc/cosign_attest.md
- pkg/cosign/remote/remote.go
- pkg/oci/mutate/mutate.go
- pkg/oci/mutate/options.go
- pkg/oci/mutate/signatures.go
- test/e2e_test.go
- test/piv_test.go
feat: replace option for same attestation
replace option for same attestation
Fixes #923 
```release-note
feat: replace option for same attestation
```
Huge thanks tho @imjasonh !! 
cc: @JimBugwadia @dlorenc @cpanato
> feat: replace option for same attestation

- pkg/oci/remote/layer.go
- pkg/oci/remote/layer_test.go
- pkg/oci/remote/remote_test.go
- pkg/oci/remote/signatures.go
We can use the already available Layer to get the payload, so we shouldn't need the `img` field. The only thing we lose is that we no longer call `img.LayerByDigest` so if the descriptor digest is invalid or doesn't match then we don't catch that anymore.
> Remove img field from sigLayer

- cmd/cosign/cli/clean.go
- doc/cosign.md
- doc/cosign_clean.md
update the `cosign clean` command documentation/help to align with the other commands and to fix some misalignments when using the help.
before
```
$ cosign
Usage:
cosign [command]
Available Commands:
attach             Provides utilities for attaching artifacts to other artifacts in a registry
attest             Attest the supplied container image.
clean              Remove all signatures from an image.
cosign clean <image uri>
completion         Generate completion script
copy               Copy the supplied container image and signatures.
dockerfile         Provides utilities for discovering images in and performing operations on Dockerfiles
download           Provides utilities for downloading artifacts and attached artifacts in a registry
...
```
after the change
```
$ ./cosign …
```
> cmd: update clean command help

- cmd/cosign/cli/verify/verify_blob.go
Adds an URI field to the verify-blob output.
Before this PR:
```
❯ COSIGN_EXPERIMENTAL=1  cosign verify-blob /tmp/mnemonic-0.3.1.tar.gz --signature /tmp/mnemonic-0.3.1.tar.gz.sig
Certificate is trusted by Fulcio Root CA
Email: []
Verified OK
tlog entry verified with uuid: "228527476f82c59641e27b8fb9b32f5fadbe47cf42c544ea97dc798490c4c14e" index: 853327
```
After this PR:
```
❯ COSIGN_EXPERIMENTAL=1  ./cosign verify-blob /tmp/mnemonic-0.3.1.tar.gz --signature /tmp/mnemonic-0.3.1.tar.gz.sig
Certificate is trusted by Fulcio Root CA
Email: []
URI: https://github.com/shibumi/mnemonic/.github/workflows/goreleaser.yml@refs/tags/v0.3.1
Issuer:  https://token.actions.githubusercontent.com
Verified OK
tlog entry verified with uuid: "228527476f82c59641e27b8fb9b32f5fadbe47cf42c544ea97dc798490c4c14e" …
```
> verify-blob: add URI to verify-blob output

- cmd/cosign/cli/triangulate.go
- doc/cosign.md
- doc/cosign_triangulate.md
similar to https://github.com/sigstore/cosign/pull/1058
update the `cosign triangulate` command documentation/help to align with the other commands and to fix some misalignments when using the help.
before
```
$ cosign
...
sign-blob          Sign the supplied blob, outputting the base64-encoded signature to stdout.
triangulate        Outputs the located cosign image reference. This is the location cosign stores the specified artifact type.
cosign triangulate <image uri>
upload             Provides utilities for uploading artifacts to a registry
verify             Verify a signature on the supplied container image
verify-attestation Verify an attestation on the supplied container image
verify-blob        Verify a signature on the supplied blob
version            Prints the cosign version …
```
> cmd: update triangulate help command

- cmd/cosign/cli/options/sign.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign/sign.go
- cmd/cosign/cli/sign/sign_test.go
- doc/cosign_sign.md
- test/e2e_test.go
Fixes #1059
Co-authored-by: Batuhan <batuhan.apaydin@trendyol.com>
Applied the same logic as we did in [signBlobCmd](https://github.com/sigstore/cosign/blob/413d06e1d3d202dbc3517109f2b228b3f1d43249/cmd/cosign/cli/sign/sign_blob.go#L104).
```bash
$ ./cosign sign --key cosign.key --output signature.sig devopps/alpine:latest
$ cat signature.sig
MEYCIQCG2Jo24lRKoXryj7xKkHrsW8K/P7iUtqWQ/2WIZ0bwfgIhAKjEKbEH7IJnoMlDPHwemOlQ6iHEHZyZPd9TH9CdtiRo
```
> feat: add output flag for signCmd

- release/cloudbuild.yaml
- release/release.mk
- adding keyless way to sign the images 
signing the images only for now with keyless because we have an issue when uploading the data to Rekor when trying to sign the blobs. As soon as that is fixed we can add keyless as well to the blobs.
rehearsal release can be found here: https://github.com/cpanato/cosign/releases/tag/v99.999.00-keyless
and the verify works now as well
```console
$ export COSIGN_EXPERIMENTAL=1
$ cosign verify gcr.io/cpanato-general/sget:v99.999.00-keyless
Verification for gcr.io/cpanato-general/sget:v99.999.00-keyless --
- Existence of the claims in the transparency log was verified offline …
```
> adding keyless way to sign the images 

- cmd/cosign/cli/options/signblob.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/sign/sign_blob.go
- cmd/cosign/cli/signblob.go
- doc/cosign_sign-blob.md
- go.mod
- test/e2e_test.go
- test/piv_test.go
With cosign 1.3.0 it is not possible to store the public certificate generated by the OIDC-issuer in a convenient way.
To store the public key locally on disk, the user has to  intercept the cosign stdout, parse it and store it.
This is inconvenient and error-prone.  We want to make signing and public key distribution as easy as possible, hence this PR introduces a new `pubkey-output` flag for the `sign-blob` sub-command.
The `pubkey-output` flag respects the `b64` flag and prints the certificate/key as file in a given file path.
Fixes None
```release-note
The cosign cli is now able to store the public certificate/key during sign-blob operations via the `pubkey-output` flag.
```
> implement a new flag for sign-blob subcommand to save certificate to disk or stdout

- pkg/cosign/verify.go
- pkg/oci/signatures.go
- pkg/oci/static/options_test.go
I noticed that vendoring `pkg/oci` was pulling in stuff from `mongodb`, and pulling the thread it seems to come from this line.
`Base64` is an alias of `[]byte`, and changing it seems to break nothing, so great!
```release-note
The SignedEntryTimestamp is now typed []byte, to get the previous behavior call strfmt.Base64(SignedEntryTimestamp)
```
> Drop `strfmt.Base64` from `pkg/oci`.

- pkg/oci/mutate/mutate.go
- pkg/oci/mutate/mutate_test.go
This adds `mutate` methods for attaching SBOMs to `oci.Signed*`, so that downstream tools can start to manipulate the attachments on `oci.Signed*`.
Related: https://github.com/google/ko/pull/506
cc @imjasonh 
```release-note
Introduce new helpers in mutate to attach named oci.Files to oci.Signed*
```
> Add `mutate.AttachFileTo*` for attaching SBOMs.

- pkg/oci/static/options.go
- pkg/oci/static/signature.go
I noticed that pulling in `./pkg/oci/static` downstream pulled in a ton of stuff I don't really want or need.
Related: https://github.com/google/ko/pull/506
```release-note
NONE
```
> Prune a few dependencies from ./pkg/oci

- cmd/cosign/cli/options/signature_digest.go
- cmd/cosign/cli/options/verify.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify/verify.go
- doc/cosign_dockerfile_verify.md
- doc/cosign_manifest_verify.md
- doc/cosign_verify.md
- pkg/signature/keys.go
- test/e2e_test.go
While, at the time of writing, it's not possible to manually specify the signature digest algorithm which should be used when signing an image, some KMS providers have key types which force a digest algorithm which isn't sha256; e.g. GCP KMS with RSA4096 / SHA512 keys.
Cosign will happily use these keys for signing and will infer the digest algorithm based on what the KMS provider mandates, leading to a situation where cosign generates signatures which it can't later verify.
This commit adds a new `--signature-digest-algorithm`  flag which allows the user to manually specify one of 4 commonly-used secure hashes when using `cosign verify`.
1. Normally I'd (of course) add an e2e test for this kind of thing, but I can't see an obvious way of generating, say, a SHA512 signature without using …
> Add flag for manually specifying a hash algo when verifying

- .goreleaser.yml
On #1019 there are some discussion about the builds not being reproducible.
We could also ditch the ldflags and read from `debug.ReadBuildInfo()` only.
What this PR does is:
- enable go mod proxying, so all releases (except snapshots) are built from the gomod proxy version instead of local code
The other bits goreleaser needs for reproducible builds are already there, so this should be working assuming the same inputs are given.
More info:
- https://goreleaser.com/customization/build/#reproducible-builds
- https://goreleaser.com/customization/gomod/
- https://goreleaser.com/cookbooks/build-go-modules/
- refs  #1019
```release-note
```
> fix: reproducible builds

- cmd/cosign/cli/verify/verify_blob.go
#1016 added a new `--output-certificate` flag. It writes the certificate as base64 by default (given `--b64` is true by default), but then if you try to use that same file to verify the blob later, it fails, as verify does not decode the string.
This makes `--certificate` works with both a base64'ed file and a regular one.
Not sure if this makes sense and if its the best impl, just throwing the idea around...
```console
$ COSIGN_EXPERIMENTAL=1 go run ./cmd/cosign/ verify-blob --key key.pem --signature README.md.sig README.md
Error: verifying blob [README.md]: loading public key: pem to public key: PEM decoding failed
main.go:46: error during command execution: verifying blob [README.md]: loading public key: pem to public key: PEM decoding failed
exit status 1
```
```console
$ ❯ …
```
> feat: verify-blob --cert base64

- pkg/cosign/kubernetes/client.go
- pkg/cosign/kubernetes/secret.go
- pkg/cosign/kubernetes/secret_test.go
Fixes #1090
Co-authored-by: Batuhan <batuhan.apaydin@trendyol.com>
Co-authored-by: Erkan <erkan.zileli@trendyol.com>
> Kubernetes: set secret immutable by default for version >= 1.21

- cmd/cosign/cli/options/signblob.go
- cmd/cosign/cli/sign.go
- cmd/cosign/cli/signblob.go
Flag was added to the sign-blob command, but alias was added to sign.
refs #1016 
```release-note
Fix --output-signature alias on sign-blob
```
> fix: alias output to output-signature on sign-blob

- pkg/oci/layout/index.go
- pkg/oci/layout/write.go
- pkg/oci/layout/write_test.go
- pkg/oci/remote/write.go
- test/e2e_test.go
This doesn't save empty signatures/attestations to disk, since we can't write them later anyway.
Also rename the annotation used to differentiate images to "kind"
ref #1015
```release-note
Add support for storing attestations in `oci/layout`
```
> Add support for storing attestations in `oci/layout`

- cmd/cosign/cli/attest/attest.go
- cmd/cosign/cli/policy_init.go
- cmd/cosign/cli/sign/sign.go
- cmd/cosign/cli/sign/sign_blob.go
- cmd/cosign/cli/verify/verify_blob.go
- pkg/cosign/tlog.go
- pkg/cosign/verify.go
This makes the `timeout` argument unnecessary
```release-note
NONE
```
> minor: plumb `context` through to tlog requests

- cmd/cosign/cli/verify/verify_blob.go
- go.mod
- go.sum
- pkg/cosign/tlog.go
- pkg/cosign/verify.go
* Use a hashed rekord type for tlog upload to allow for signing large blobs with keyless flow.
**THIS IS A NOT A DRAFT ANYMORE BECAUSE...**
1. Prod rekor needs to be deployed with the new type **(DONE)**
2. The bigger issue is that if someone is using `COSIGN_EXPERIMENTAL` and uploading signed entries, let's say, with a KMS provider that uses a specific hash algorithm, then defaulting to the SHA256 I hard-coded in `rekorEntry` will be incorrect and will fail signature verification. The hash algorithm needs to be plumbed through, so I imagine that SignerVerifier would have to expose a new method to it's interface providing the hash function that it uses by default (doesn't look like cosign will ever use a `WithCryptoSignerOpts(otherHashFunc)` on …
> Use hashed rekord type for tlog upload

- cmd/cosign/cli/sign/sign.go
Gets rid of a small chance of memory leak
```release-note
NONE
```
> bugfix: call Close() on security keys before returning error

- cmd/cosign/cli/sign/sign.go
When keyless signing a private image today we prompt the user about uploading to Rekor, but in automation this prompt fails and on error this code panics (today).
This change rewords the prompt, and makes the error path non-fatal (emits a WARNING, see below):
```
COSIGN_EXPERIMENTAL=true cosign sign ghcr.io/mattmoor/bundles < /dev/null
Generating ephemeral keys...
Retrieving signed certificate...
Non-interactive mode detected, using device flow.
Enter the verification code MVRL-JKVG in your browser at: https://oauth2.sigstore.dev/auth/device?user_code=MVRL-JKVG
Code will be valid for 300 seconds
Token received!
Successfully verified SCT...
"ghcr.io/mattmoor/bundles" appears to be a private repository, please confirm uploading to the transparency log at "https://rekor.sigstore.dev" [Y/N]: …
```
> Make the transparency log upload non-fatal.

- cmd/cosign/cli/options/verify.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify/verify.go
- doc/cosign_dockerfile_verify.md
- doc/cosign_manifest_verify.md
- doc/cosign_verify.md
- pkg/cosign/verify.go
Add ability to verify via signature reference in verify cmd
Fixes #1067 
```release-note
feat: support signature file in verify cmd
```
> feat: support signature file in verify cmd

- cmd/cosign/cli/generate/generate_key_pair.go
- cmd/cosign/cli/sign/sign.go
This updates the output for `cosign sign` to match what's in the documentation. A few other output cleanups:
* Changed when the newline is written for fetching a password
* Removed writing the signature to stdout, only writing the signature to a file when requested
New output:
```
$ ~/go/bin/cosign sign --key cosign.key us-west1-docker.pkg.dev/project/docker-repo/image:tag1
Enter password for private key:
Pushing signature to: us-west1-docker.pkg.dev/project/docker-repo/image
```
Previous output:
```
$ ~/go/bin/cosign sign --key cosign.key us-west1-docker.pkg.dev/project/docker-repo/image:tag1
Enter password for private key: MEYCI....
```
```release-note
NONE
```
> Update sign output to note when signatures are pushed

- cmd/cosign/cli/options/fulcio.go
- doc/cosign_attest.md
- doc/cosign_policy_sign.md
- doc/cosign_sign-blob.md
- doc/cosign_sign.md
- doc/cosign_verify-attestation.md
Fixes
```release-note
BREAKING: This change means new cosign versions will generate signatures that
do not validate in older versions of cosign. This only applies to "keyless" experimental mode.
To opt out of this behavior, use: --fulcio-url=https://fulcio.sigstore.dev when signing payloads.
```
> Switch (temporarily) the fulcio endpoint to our new v1 service.

- .github/workflows/validate-release.yml
- release/cloudbuild.yaml
-  ghcr.io/gythialy/golang-cross v1.17.4-0 is out https://github.com/gythialy/golang-cross/releases/tag/v1.17.4-0
that uses go 1.17.4
n/a
```release-note
update  ghcr.io/gythialy/golang-cross to use go 1.17.4
```
> update  ghcr.io/gythialy/golang-cross to use go 1.17.4

- go.mod
- pkg/cosign/tuf/policy.go
The existing cjson hasn't been maintained. The last update was 9 years
ago. This was replaced by the upstream go-securesystemslib
https://github.com/secure-systems-lab/go-securesystemslib/pull/10
cc @asraa
> cjson - Move to go-securesystemslib

- cmd/cosign/cli/options/attach.go
- doc/cosign_attach_sbom.md
- pkg/types/media.go
Signed-off-by: Sambhav Kothari <skothari44@bloomberg.net>
Add support for syft format in cosign attach sbom
Fixes #1136 
```release-note
Add support for syft format in cosign attach sbom
```
> Add support for syft json type to cosign

- cmd/cosign/cli/options/sign.go
- cmd/cosign/cli/sign.go
- doc/cosign_sign.md
This flag was added in https://github.com/sigstore/cosign/pull/1066 and obsoleted in https://github.com/sigstore/cosign/pull/1095, which are both within the 1.4.0 release
```release-note
NONE
```
> remove obsolete `--output` flag

- .goreleaser.yml
The flag was changed in https://github.com/sigstore/cosign/pull/1016
```release-note
NONE
```
> `sign-blob` `--output` -> `--output-signature`

- cmd/cosign/cli/save.go
- pkg/oci/layout/index.go
- pkg/oci/layout/write.go
- pkg/oci/remote/write.go
- test/e2e_test.go
Save and load were assuming we were only saving and loading SignedImages. This PR should add support for saving and loading SignedImageIndex's as well!
ref https://github.com/sigstore/cosign/issues/1015
```release-note
fix: saving and loading a signed image index to disk
```
cc @haydentherapper who is working on verification for this!
> Fix bug when saving and loading a manifest list

- cmd/cosign/cli/sign/sign_blob.go
`--output-certificate` was producing empty certificates.
Likely a bad merge from me when working on #1095
Refs #1095
```release-note
fix sign-blob --output-certificate writing an empty file
```
> fix: --output-certificate not working properly

- cmd/cosign/webhook/main.go
cosigned was the last tool to expose the version/gitstate/buid time information
adding this when cosigned start, if there is another better way to expose this info please let me know
```
$ ./cosigned
2021/12/05 16:58:46 {
"GitVersion": "v99.999.00-keyless-37-ge233ce8-dirty",
"GitCommit": "e233ce828a70491d5fec699477fb2b679efce8dc",
"GitTreeState": "dirty",
"BuildDate": "'2021-12-04T13:38:20Z'",
"GoVersion": "go1.17.4",
"Compiler": "gc",
"Platform": "darwin/amd64"
}
2021/12/05 16:58:46 Registering 2 clients
2021/12/05 16:58:46 Registering 2 informer factories
2021/12/05 16:58:46 Registering 3 informers
2021/12/05 16:58:46 Registering 3 controllers
{"severity":"INFO","timestamp":"2021-12-05T16:58:46.706712+01:00","caller":"logging/config.go:116","message":"Successfully created the logger."} …
```
> cosigned: add version to cosigned

- cmd/cosign/cli/sign/sign.go
- cmd/cosign/cli/sign/sign_blob.go
- create certificates and signature with less permissions (`0600` vs `0666` - the default of `os.Create`
- improve error handling a bit by wrapping the errors
n/a
```release-note
--output-signature and --output-certificate now created with 0600 permissions
```
> fix: improve perms, error handling

- .github/workflows/e2e-with-binary.yml
add job to run some e2e tests to sing a artifact and check the outputs
Fixes
```release-note
add job to run some e2e tests to sing a artifact and check the outputs
```
> add job to run some e2e tests to sing a artifact and check the outputs

- pkg/cosign/tlog.go
- pkg/cosign/tuf/client.go
- pkg/cosign/verify.go
This (probably) doesn't fix the error being seen by @cpanato during verification on windows, but it does surface the error and take care of some potential root causes
```release-note
NONE
```
> return error when rekor pub cannot be retrieved, fix file path construction

- .github/workflows/e2e-with-binary.yml
- .github/workflows/tests.yaml
- pkg/cosign/tuf/client.go
- pkg/cosign/tuf/client_test.go
I expanded our Windows CI test coverage with the goal of root causing https://github.com/sigstore/cosign/issues/1153. Still haven't done that, yet, but I figure I should get this in
Mitigates https://github.com/sigstore/cosign/issues/1160 -related failures in testing
```release-note
bugfix: `cosign` Windows releases panicking under certain circumstances
```
> expand CI testing to Windows and OSX, fix issues uncovered

- Makefile
- cmd/help/verify.sh
This just simplifies regenerating documentation.
```release-note
NONE
```
> Add make target for doc generation

- cmd/cosign/cli/options/verify.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify/verify.go
- doc/cosign_dockerfile_verify.md
- doc/cosign_manifest_verify.md
- doc/cosign_verify.md
- pkg/cosign/verify.go
- test/e2e_test.go
This builds on the previous work to support saving an image and its signature for airgapped environments. This adds a flag, `--local-image`, to verify a signed image from disk.
Example:
```
cosign save us-west1-docker.pkg.dev/project/docker-repo/image:tag1 --dir .
cosign verify --key cosign.pub --local-image . --verbose
```
With `--verbose`, we see no network calls.
Ref #1015
```release-note
Add `cosign verify --local-image path` for verifying signed images from disk
```
> Add option to verify local image

- pkg/cosign/tuf/client.go
Follow-up to https://github.com/sigstore/cosign/pull/1158
```release-note
NONE
```
> use `sync.Once` to init the global tuf root

- .github/workflows/e2e-with-binary.yml
Didn't catch it earlier because it's only run on push
```release-note
NONE
```
> disable broken Windows e2e-with-binary

- go.mod
- go.sum
This picks up a change that dramatically speeds up the http fallback when pushing to insecure registries (e.g. `.svc.cluster.local`)
I am confirming this fixes the issue I was seeing downstream now with a private image build at HEAD (with this change).
```release-note
Fixes some context-deadline exceeded errors pushing to insecure registries (e.g. `.svc.cluster.local`)
```
> Bump GGCR to latest.

- cmd/cosign/cli/options/verify.go
- cmd/cosign/cli/verify.go
- cmd/cosign/cli/verify/verify_attestation.go
- doc/cosign_dockerfile_verify.md
- doc/cosign_manifest_verify.md
- doc/cosign_verify-attestation.md
- doc/cosign_verify.md
- pkg/cosign/verify.go
- test/e2e_test.go
This is very similar to a previous PR (#1159) that added support for verifying signatures from a local image.
Ref #1015 
Example:
```
...generate attestation...
cosign save us-west1-docker.pkg.dev/project/docker-repo/image:tag1 --dir .
cosign verify-attestation --key cosign.pub --local-image . --verbose
```
With `--verbose`, we see no network calls.
```release-note
Add `cosign verify-attestation --local-image path` for verifying signed images with attestations from disk
```
> Add option to verify attestations from local image

- go.mod
- go.sum
- pkg/cosign/tuf/client.go
- pkg/cosign/tuf/client_test.go
This pulls in fixes in https://github.com/theupdateframework/go-tuf/pull/188 and https://github.com/theupdateframework/go-tuf/pull/189
Mostly (fully?) addresses https://github.com/sigstore/cosign/issues/1160
```release-note
NONE
```
> update go-tuf and use the newly exposed `Close()`

- .github/workflows/tests.yaml
- test/e2e_test.ps1
I haven't been able to provoke the bug in #1153, but at least we have some powershell-based tests now
```release-note
NONE
```
> add e2e tests for Windows + PowerShell

- .github/workflows/validate-release.yml
- release/cloudbuild.yaml
- update golang cross image to use go1.17.5
release: https://github.com/gythialy/golang-cross/releases/tag/v1.17.5-0
```console
$ docker run --entrypoint="" ghcr.io/gythialy/golang-cross:v1.17.5-0 go version
go version go1.17.5 linux/amd64
```
n/a
```release-note
update golang cross image to use go1.17.5
```
> update golang cross image to use go1.17.5

- cmd/cosign/cli/initialize/init.go
- cmd/cosign/cli/options/initialize.go
- doc/cosign_initialize.md
This patch allows fetching TUF root from HTTP in addition to GCS. If the
specified mirror is an HTTP link, then HTTPRemoteStore will be used.
Otherwise it defaults to GCS.
> Allow fetching TUF root from HTTP

- CHANGELOG.md
> add 1.4.1 relnotes

- CHANGELOG.md
The `# Changelog` top level title is redundant and this makes it easy to copy-paste relnotes into the GitHub release
```release-note
NONE
```
> nit: drop every section title down a level

- config/webhook.yaml
Fixes https://github.com/sigstore/cosign/issues/1207
```release-note
NONE
```
> add a writeable `$HOME` for the `nonroot` cosigned user

- pkg/oci/mutate/options.go
- pkg/oci/mutate/signature.go
- pkg/oci/mutate/signature_test.go
> create `mutate` functions for `oci.Signature`

- go.mod
- go.sum
update google.golang.org/api from 0.62.0 to 0.63.0
Fixes
```release-note
update google.golang.org/api from 0.62.0 to 0.63.0
```
> update google.golang.org/api from 0.62.0 to 0.63.0

- internal/pkg/cosign/ephemeral/signer.go
- internal/pkg/cosign/ephemeral/signer_test.go
> clean up references to 'keyless' in `ephemeral.Signer`

- cmd/cosign/cli/fulcio/fulcioroots/fulcioroots.go
cosign requires both fulcio.crt.pem and fulcio_v1.crt.pem in the TUF
root which doesn't make sense when using local TUF. fulcio_v1.crt.pem
was added in the embedded TUF in order to support Fulcio v1 but it
shouldn't be required when users initialize cosign with their own TUF
repo.
Closes: #1229
Signed-off-by: Radoslav Gerganov <rgerganov@vmware.com>
> Do not require multiple Fulcio certs in the TUF root

- .github/workflows/validate-release.yml
- go.mod
- go.sum
- pkg/providers/all/all.go
- pkg/providers/spiffe/doc.go
- pkg/providers/spiffe/spiffe.go
- release/cloudbuild.yaml
Support ambient credential detection with SPIFFE/SPIRE by looking at socket path and through SVID (Spiffe Verifiable Identity Document)
Fixes #645 
```release-note
feat: add ambient credential detection with spiffe/spire
```
> feat: add ambient credential detection with spiffe/spire

- cmd/cosign/cli/options/predicate.go
- doc/cosign_attest.md
- doc/cosign_verify-attestation.md
- pkg/cosign/attestation/attestation.go
- specs/COSIGN_VULN_ATTESTATION_SPEC.md
Users might upload vulnerability scan results in form of attestation within the OCI registry
Fixes #442 
```release-note
feat: vuln attest support
```
> feat: vuln attest support

- .github/workflows/build.yaml
feat: generate/upload sbom for cosign projects
Fixes #959 
```release-note
feat: generate/upload sbom for cosign projects
```
> feat: generate/upload sbom for cosign projects

- cmd/cosign/cli/sign/sign.go
Currently we print the image repo being signed as if we were pushing the
signatures to that same repo, which could lead to users being surprised.
Instead try to get the override and print that instead
Resolves: #1242
```release-note
NONE
```
> Log the proper remote repo for the signatures on verify

- cmd/cosign/cli/verify/verify.go
- cmd/cosign/cli/verify/verify_blob.go
`verify` and `verify-blob`'s `--cert` param should accept an URL as well, so we can verify without previously downloading files, e.g.:
```sh
cosign verify-blob \
--cert https://github.com/goreleaser/supply-chain-example/releases/download/v1.0.0/checksums.txt.pem \
--signature https://github.com/goreleaser/supply-chain-example/releases/download/v1.0.0/checksums.txt.sig \
https://github.com/goreleaser/supply-chain-example/releases/download/v1.0.0/checksums.txt
```
https://github.com/gythialy/golang-cross/pull/67/files#r774120479
```release-note
verify and verify-blob resolve --cert from URL
```
> feat: resolve --cert from URL

- cmd/cosign/cli/attest/attest.go
The 'payloadType' field in a DSSE envelope is always supposed to be set
to the in-toto media type. We were incorrectly placing the inner predicateType
here.
The DSSE library probably shouldn't even expose this as a parameter given that it's
a MUST in the spec.
Fixes
```release-note
```
> Fix semantic bug in DSSE specification.

- pkg/cosign/verify.go
- pkg/cosign/verify_test.go
DSSE requires that the payload types match, but the Attestation
spec requires that the payload type be the specific in-toto one. We
don't actually do anything with the content here other than dump it
in plain text, but semantically we're calling these attestations in the
CLI so we should enforce that part of the specification as well.
Fixes
```release-note
BREAKING: In-Toto Attestations generated in older versions of cosign will not verify in newer versions. 
```
> Fix semantic bugs in attestation verifification.

- cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier_test.go
- test/pkcs11_test.go
Remove the remaining ioutil usage from the code
Signed-off-by: Morten Linderud <morten@linderud.pw>
Fixes
```release-note
```
> Remove remaining ioutil usage

- cmd/cosign/cli/sign/sign.go
Moved logic to print certificate during signing earlier on otherwise logic is not reached when `--upload=false`
> Moved certificate output before checking for upload during signing

- cmd/cosign/cli/fulcio/fulcioroots/fulcioroots.go
- cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go
- cmd/cosign/cli/initialize/init.go
- pkg/cosign/tlog.go
- pkg/cosign/tuf/client.go
- pkg/cosign/tuf/client_test.go
Refactor the tuf client code.
This is my attempt at refactoring the TUF client code to better
support the configuration modes we've recently added.
This also adds support for SIGSTORE_NO_CACHE, and eliminates most
writes to disk from cosign outside of cosign initialize.
I think these tests are about equivalent to what we had before, if not
a bit better. The coverage is at 72% and hits most non-sporadic errors.
Fixes
```release-note
```
> Refactor the tuf client code.

- cmd/cosign/cli/attach.go
- cmd/cosign/cli/attach/attestation.go
- cmd/cosign/cli/options/attach.go
- doc/cosign_attach.md
- doc/cosign_attach_attestation.md
To test this, run the following commands:
```shell
$ crane copy alpine <registry>/<username>/alpine
$ echo "foo" > bar
$ cosign attest --key cosign.key --predicate bar <registry>/<username>/alpine
$ cosign download attestation <registry>/<username>/alpine > signedpayload.json
$ cosign attach attestation --key cosign.pub --attestation signedpayload.json <registry>/<username>/alpine
```
Fixes #1202 
```release-note
feat: support attach attestation
```
> feat: support attach attestation

- .github/workflows/validate-release.yml
- .goreleaser.yml
- release/cloudbuild.yaml
- release/release.mk
- add the sbom for the binaries as part of the release process
- fix the tuf db when validating the builder image
rehearsal release: https://github.com/cpanato/cosign/releases/tag/v99.99.04
n/a
```release-note
enable sbom generation when releasing
```
> enable sbom generation when releasing

- cmd/cosign/cli/commands.go
- test/e2e_test_secrets.sh
The writer was getting closed prematurely in the PreRun command. We need to save
this as a temp variable at the command level and close the writer in PostRun.
Fixes
```release-note
```
> Fix output-file flag.

- cmd/cosign/cli/generate/generate_key_pair.go
- cmd/cosign/cli/importkeypair/import_key_pair.go
- pkg/cosign/common.go
Refactor the common utilities for password prompting, checking for file existence as well as determining terminal status, per #1078 
Signed-off-by: Ivan Wallis ivan.wallis@venafi.com
Summary
Ticket Link
Fixes
Release Note
> refactor core password prompting, file exist and terminal checks

- pkg/cosign/tuf/client_test.go
These tests worked by mocking at the "isExpired" level. When the real files
ARE expired, but we mock them to be NOT expired, the code continues down a
path it shouldn't and fails later, trying to use expired metadata.
We should fix this "better" by generating real expired and unexpired metadata,
or changing the system clock somehow.
Fixes
```release-note
```
> Fix the unit tests with expired TUF metadata.

- specs/SIGNATURE_SPEC.md
The timestamp will be used to find a versioned TUF target metadata.
This allows targets to be rotated while still being able to validate
old entries that were signed by previous targets.
Ref #1273
Cosign currently can only verify signatures from current TUF metadata. This will cause signature verification to fail for old entries once the target, such as the Fulcio certificate, is rotated. Including the timestamp, along with additional work to persist versioned TUF targets, will allow cosign to find the previous target used to generate the signature.
I will implement this feature to be backwards compatible. If an entry does not include the timestamp, then cosign will use the latest TUF metadata.
#1273 contains additional context. …
> Update signature spec with TUF timestamp

- .github/workflows/validate-release.yml
- release/cloudbuild.yaml
- update release image to use go 1.17.6
release: https://github.com/gythialy/golang-cross/releases/tag/v1.17.6-0
n/a
```release-note
update release image to use go 1.17.6
```
> update release image to use go 1.17.6

- pkg/cosign/tuf/client.go
* In getRoot, the metadata is always stored at the top level,
not under repository/. This resulted in initialize always falling
back to the embedded root.
* In Initialize, download all metadata and targets. This should
avoid a disk write on verify.
Fixes
```release-note
```
> Fix a few bugs in cosign initialize

- cmd/cosign/cli/verify/verify.go
- cmd/cosign/cli/verify/verify_blob.go
- pkg/cosign/verify.go
1. We weren't checking the expiry of the cert against the time the entry was added to rekor
2. We weren't verifying the cert passed in by `--cert`
> Fix a couple bugs in cert verification for blobs

- go.mod
- go.sum
- Bump github.com/xanzy/go-gitlab from 0.54.2 to 0.54.3
replaces: https://github.com/sigstore/cosign/pull/1285
n/a
```release-note
NONE
```
> Bump github.com/xanzy/go-gitlab from 0.54.2 to 0.54.3

- cmd/cosign/cli/attest/attest.go
- internal/pkg/cosign/rekor/signer.go
- pkg/cosign/bundle/rekor.go
- pkg/cosign/fetch.go
- pkg/cosign/tlog.go
- pkg/cosign/verify.go
- pkg/oci/internal/signature/layer.go
- pkg/oci/internal/signature/layer_test.go
- pkg/oci/mutate/options.go
- pkg/oci/mutate/signature.go
- pkg/oci/mutate/signature_test.go
- pkg/oci/signatures.go
- pkg/oci/static/options.go
- pkg/oci/static/options_test.go
- pkg/oci/static/signature.go
- pkg/oci/static/signature_test.go
This makes a little more sense since the bundle isn't really tied to oci, and will make it easier to implement the on-disk bundle for #1193 by creating the `EntryToBundle` func which was previously duplicated across packages.
> Move bundle definition out of `oci` and into `bundle` package

- pkg/cosign/tuf/client.go
Adds a better error handling and comment for https://github.com/sigstore/cosign/issues/1293
I don't think there's a way yet to store state of your remote repository's location (in go-tuf client there isn't), so the best you can do is detect that youre trying to use a different repo than the default remote repo and to warn to check your cache
Fixes
```release-note
```
> TUF: Add error message when local cache's TUF metadata is expired

- pkg/cosign/keys.go
- pkg/cosign/keys_test.go
This adds support for PKCS#8 encoded private keys, which means
we can also import ED25519 keys. I've added tests for PKCS#8
RSA and ECDSA keys too.
I also added some validation of keys before importing. For RSA,
we will require that the key size be between 2048 and 4096.
For ECDSA keys, we will only disallow NIST P-224, since Cosign
generates P-256 by default. Other curves are not supported
by Go's crypto library.
#549
```release-note
* Added support for importing PKCS#8 private keys
* Added validation of imported private keys
```
> Add support for importing PKCS#8 private keys, and add validation

- cmd/cosign/cli/sign/sign.go
- internal/pkg/cosign/fulcio/signer.go
- internal/pkg/cosign/fulcio/signer_test.go
- internal/pkg/cosign/rekor/mock_rekor_client.go
- internal/pkg/cosign/rekor/signer.go
- internal/pkg/cosign/rekor/signer_test.go
- pkg/cosign/tuf/client.go
- pkg/cosign/tuf/client_test.go
- pkg/cosign/tuf/timestamp.go
- pkg/oci/internal/signature/layer.go
- pkg/oci/internal/signature/layer_test.go
- pkg/oci/mutate/options.go
- pkg/oci/mutate/signature.go
- pkg/oci/mutate/signature_test.go
- pkg/oci/signatures.go
- pkg/oci/static/options.go
- pkg/oci/static/options_test.go
- pkg/oci/static/signature.go
- pkg/oci/static/signature_test.go
This updates the code to add the TUF timestamp to the OCI signature when signing with Fulcio or writing to Rekor.
Changes to each package:
* `pkg/oci` - Add support for reading and saving the timestamp by annotation key
* TUF client - Put the timestamp in memory on client initialization
* fulcio and rekor signers - Include the timestamp on signing
I also added some unit tests for the signers, including a mock Rekor client (that's incomplete, should be updated as needed).
Ref #1273
```release-note
Bundled TUF timestamp with OCI signature on signing, to use to verify signatures with old targets
```
cc @asraa
> Bundle TUF timestamp with signature on signing

- test/e2e_test.go
There must have been a race condition between merging https://github.com/sigstore/cosign/pull/1306 and an extra arg being added to `VerifyBlobCmd` -- this should fix the failing test.
> Fix TestSignBlobBundle

- .github/workflows/donotsubmit.yaml
- .github/workflows/kind-e2e-cosigned.yaml
Switches to `go install` for kind and verifying checksum of `reviewdog` instead of `curl | sh`. 
Fixes #1323
> Verify checksum of downloaded utilities during CI

- cmd/cosign/cli/fulcio/fulcio.go
- cmd/cosign/cli/fulcio/fulcio_test.go
- cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go
- cmd/cosign/cli/sign/sign.go
The default value of empty string for OIDC client secret doesn't always
work. Users should be able to specify their own.
Closes #1309
Signed-off-by: Radoslav Gerganov <rgerganov@vmware.com>
> Take OIDC client secret into account

- cmd/cosign/cli/sign/sign.go
Currently, when specifying an output signature file name during signing, the signature file is overridden when attempting to sign recursively. This feature enables appending a suffix of the image digest to the name of the output file provided. The `@` in the digest string is replaced by a `-` in a similar fashion as when tags are applied to signatures and attestations 
Non recursive sign: `<signature_output_provided>`
Recursive sign: `<signature_output_provided>-<modified_digest>`
Resolves #1257
> Add suffix with digest to signature file output for recursive signing

- .github/workflows/build.yaml
`/bin/sh: 1: goimports: not found` for example: https://github.com/sigstore/cosign/runs/4827474245?check_suite_focus=true
n/a
```release-note
NONE
```
> fix missing goimports in the build github action

- go.mod
- go.sum
Bump sigstore dependency to fix #1301. 
cosign verify --key hashivault://testcosign-kms  golang:1.16
Error: no matching signatures:
Failed vault verification
main.go:46: error during command execution: no matching signatures:
Failed vault verification
Fixes #1301 
```release-note
```
> fix: cosign verify for vault

- .github/workflows/build.yaml
- update gcp setup for the GH action
doing this because the current way is deprecated 
```
Warning: "service_account_key" has been deprecated. Please switch to using google-github-actions/auth which supports both Workload Identity Federation and Service Account Key JSON authentication. For more details, see https://github.com/google-github-actions/setup-gcloud#authorization
```
Not sure if the service_account name is correct 
n/a
```release-note
NONE
```
> update gcp setup for the GH action

- .github/workflows/build.yaml
previous PR (https://github.com/sigstore/cosign/pull/1330) updated the step to auth in the gcp project, however some parameters is not needed.
n/a
```release-note
NONE
```
> remove wrong settings in the gco auth for gh actions

- .github/workflows/build.yaml
Error in the post github action when building the images using `ko`
```
LDFLAGS="-X github.com/sigstore/cosign/pkg/version.GitVersion=888b392-dirty -X github.com/sigstore/cosign/pkg/version.gitCommit=888b39200d1ae4319aa7c6d6c3b5102abf8871ed -X github.com/sigstore/cosign/pkg/version.gitTreeState="dirty" -X github.com/sigstore/cosign/pkg/version.buildDate='2022-01-15T22:28:40Z'" GIT_HASH=888b39200d1ae4319aa7c6d6c3b5102abf8871ed GIT_VERSION=888b392-dirty \
ko publish --base-import-paths --bare \
--platform=all --tags 888b392-dirty --tags 888b39200d1ae4319aa7c6d6c3b5102abf8871ed \
github.com/sigstore/cosign/cmd/cosign
2022/01/15 22:33:50 Using base gcr.io/distroless/base:debug-nonroot for github.com/sigstore/cosign/cmd/cosign
2022/01/15 22:33:51 Using build config cosign for …
```
> install latest release for ko instead of head of main branch

- go.mod
- go.sum
- pkg/cosign/git/github/github.go
- update go-github to v42 release
n/a
```release-note
NONE
```
> update go-github to v42 release

- pkg/cosign/verify.go
Calling the existing `VerifyImageSignatures` function multiple times for the same image with different verifiers will download the OCI manifest multiple times. This is inefficient and slow.
Exporting a function that verifies a single signature allows the decoupling of the fetch and verification stages.
```release-note
```
> Export function to verify individual signature

- README.md
[#568](https://github.com/sigstore/cosign/pull/568) bumps the Go version for tests to 1.17. Now they break for 1.16:
```sh
$ TMPDIR=$(mktemp -d)
$ cd $TMPDIR
$ git clone https://github.com/sigstore/cosign 2> /dev/null
$ cd cosign
$ for go in go_1_16 go_1_17; do
>   nix-shell \
>     -p ${go} \
>     -p gnumake \
>     --command 'make test' \
>     > /dev/null 2>&1
>   if [ $? -eq 0 ]; then
>     echo ${go} good
>   else
>     echo ${go} bad
>   fi
> done
go_1_16 bad
go_1_17 good
```
[#1252](https://github.com/sigstore/cosign/pull/1252) adds a call to `testing.T.Setenv`, added in [1.17](https://go-review.googlesource.com/c/go/+/326790/3/api/go1.17.txt), which caused this breakage.
(We're still testing *builds* on 1.16, so that's fine.)
Fixes N/A
```release-note
NONE
```
> Bump recommended Go development version in README

- README.md
Signed-off-by: John Speed Meyers <jsmeyers@chainguard.dev>
Fixes minor typo in main README documentation
> Fix minor typo (a missing verb) in README

- cmd/cosign/cli/initialize/init.go
- cmd/cosign/cli/options/initialize.go
- pkg/cosign/tuf/client.go
- pkg/cosign/tuf/client_test.go
Caches the remote repository location so that updates will pull from the cached remote instead of defaulting to the sigstore GCS bucket. This allows clients to automatically pull updates from their custom root when their root is expired and avoids a local/remote mismatch.
This fixes https://github.com/sigstore/cosign/issues/1289 per @rgerganov and https://github.com/sigstore/cosign/issues/1293
```release-note
```
> Cache the location of the remote repository when running cosign initialize

- pkg/version/version.go
- add ascii art when using the version command
```console
$ ./cosign version
______   ______        _______. __    _______ .__   __.
/      | /  __  \      /       ||  |  /  _____||  \ |  |
|  ,----'|  |  |  |    |   (---- |  | |  |  __  |   \|  |
|  |     |  |  |  |     \   \    |  | |  | |_ | |  .    |
|  '----.|  '--'  | .----)   |   |  | |  |__| | |  |\   |
\______| \______/  |_______/    |__|  \______| |__| \__|
cosign: A tool for Container Signing, Verification and Storage in an OCI registry.
GitVersion:    v1.4.1-91-g7ca90c8
GitCommit:     7ca90c8cd732897238cc92756eeb69a93af5c29f
GitTreeState:  clean
BuildDate:     '2022-01-22T18:24:37Z'
GoVersion:     go1.17.6
Compiler:      gc
Platform:      darwin/amd64
```
Fixes
```release-note
NONE
```
> add ascii art when using the version command

- go.mod
- go.sum
Fixes #1350 
Picks up https://github.com/google/go-containerregistry/pull/1265
```release-note
Fixes issue with using environment registry credentials for Azure Container Registry
```
> Bump go-containerregistry to pick up ACR keychain fix

- cmd/cosign/cli/verify/verify_blob.go
- cmd/cosign/cli/verify/verify_blob_test.go
Adds the ability to verify DSSEs from the `verify-blob` command.
Fixes sigstore/cosign#1321
> Update verify-blob to support DSSEs

- README.md
Fix the link to "race condition" in README.md, and use the term "race condition" consistently. (Previously it used "race" in one place and "racy" in the other, making it difficult to do a find/grep.)
```release-note
NONE
```
> README: fix link to race conditions

- cmd/cosign/cli/options/fulcio.go
- cmd/cosign/cli/options/oidc.go
- cmd/cosign/cli/options/rekor.go
- expose the Fulcio, Rekor, and OIDC Issuer default URLs and make those available if any service that wants to implement can use the default URLs and not change the code when this get an update
example of usage will be here https://github.com/kubernetes-sigs/release-sdk/pull/25
n/a
```release-note
expose dafaults fulcio, rekor, oidc issuer urls
```
> expose dafaults fulcio, rekor, oidc issuer urls

- test/e2e_test.go
Just saw this little nit while fixing the e2e tests in another PR. I
think we can also avoid the time conversions because we already pass the
correct type to the functions.
None
```release-note
None
```
> Fix double `time` import in e2e tests

- pkg/cosign/remote/remote.go
- test/e2e_test.go
Currently the replace option compares `r.predicateURI == payloadData["payloadType"]` when evaluating each signature:
https://github.com/sigstore/cosign/blob/21e6b806143652331b77c29c62a131fb33a71ae0/pkg/cosign/remote/remote.go#L142
This appears to be comparing the payload's `predicateType` (e.g a URI `https://example.com/predicate` or `cosign.sigstore.dev/attestation/v1` for custom) to the signature's `payloadType` (which is always(?) `application/vnd.in-toto+json`). This appears to be a bug unless I'm misunderstanding something.
Fix this by making the replace option replace all attestations which match the current predicate type. I think this is the intended behavior?
The command line output has been updated to clarify the actions taken, clearly listing all the attestations retained and …
> Fix comparison in replace option for attestation

- cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go
- cmd/cosign/cli/verify/verify_blob.go
- pkg/cosign/tlog.go
- pkg/cosign/tlog_test.go
- pkg/cosign/verify.go
This will be used to verify old entries using a set of trusted
keys. No changes are needed for Fulcio, since the underlying
verification library already accepts multiple trusted roots.
Ref #1273
Fixes
```release-note
NONE
```
> Minor refactor to verify SCT and Rekor entry with multiple keys

- .github/workflows/validate-release.yml
- .goreleaser.yml
- release/cloudbuild.yaml
- update cosign and cross-build image for the release job
n/a
```release-note
update cosign and cross-build image for the release job
```
> update cosign and cross-build image for the release job

- cmd/cosign/cli/initialize/init.go
- pkg/cosign/tuf/client.go
- pkg/cosign/tuf/client_test.go
Add structured output describing the TUF root, for example:
```
$ rm -r $HOME/.sigstore && ./cosign initialize
Root status: 
{
"local": "/home/asraa/.sigstore/root",
"remote": "sigstore-tuf-root",
"expiration": {
"root.json": "11 May 22 19:09 UTC",
"snapshot.json": "15 Feb 22 00:39 UTC",
"targets.json": "11 May 22 19:10 UTC",
"timestamp.json": "15 Feb 22 00:39 UTC"
},
"targets": [
"rekor.pub",
"artifact.pub",
"ctfe.pub",
"fulcio.crt.pem",
"fulcio_v1.crt.pem"
]
}
```
Fixes https://github.com/sigstore/cosign/issues/1297
```release-note
* Adds TUF root status with expiration and repository locations to output of `cosign initialize`
```
> TUF: Add root status output

- pkg/cosign/common.go
There is no newline after entering a password and the output is hard to read.
Before:
```
$ cosign sign --key cosign.key knqyf263/cosign-test
an error occurred: no provider found for that key reference, will try to load key from disk...
Enter password for private key: Pushing signature to: index.docker.io/knqyf263/cosign-test
```
After:
```
$ cosign sign --key cosign.key knqyf263/cosign-test
an error occurred: no provider found for that key reference, will try to load key from disk...
Enter password for private key:
Pushing signature to: index.docker.io/knqyf263/cosign-test
```
```release-note
Add a newline after entering password
```
> Add a newline after password input

- pkg/oci/remote/image.go
- pkg/oci/remote/index.go
- pkg/oci/remote/remote.go
Before:
```
$ cosign sign gcr.io/imjasonh/aslkjdlfkjasdlkfjasf
...
Error: signing [gcr.io/imjasonh/aslkjdlfkjasdlkfjasf]: accessing entity: GET https://gcr.io/v2/imjasonh/aslkjdlfkjasdlkfjasf/manifests/latest: MANIFEST_UNKNOWN: Failed to fetch "latest" from request "/v2/imjasonh/aslkjdlfkjasdlkfjasf/manifests/latest".
main.go:46: error during command execution: signing [gcr.io/imjasonh/aslkjdlfkjasdlkfjasf]: accessing entity: GET https://gcr.io/v2/imjasonh/aslkjdlfkjasdlkfjasf/manifests/latest: MANIFEST_UNKNOWN: Failed to fetch "latest" from request "/v2/imjasonh/aslkjdlfkjasdlkfjasf/manifests/latest".
```
After:
```
$ go run ./cmd/cosign sign gcr.io/imjasonh/akjsldkfjalkjsdflkajsdf
...
Error: signing [gcr.io/imjasonh/akjsldkfjalkjsdflkajsdf]: accessing entity: entity not found in …
```
> Improve error message when image is not found in registry

- pkg/providers/spiffe/spiffe.go
- pkg/providers/spiffe/spiffe_test.go
SPIFFE_ENDPOINT_SOCKET
Allow overriding the Spiffe socket when using Spiffe provider with `SPIFFE_ENDPOINT_SOCKET` environmental variable.
Fixes #1420
Fixes #1420
```release-note
Allow overriding the Spiffe socket when using Spiffe provider with `SPIFFE_ENDPOINT_SOCKET` environmental variable.
```
> Add ability to override the Spiffe socket via environmental variable:

- cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go
Introduced in #1396, this incorrectly checked err instead
of verifySctErr. This resulted in no error being printed
when SCT validation failed. Verified this is working
correctly now with local testing.
Fixes
```release-note
```
> Fix incorrect error check when verifying SCT

- pkg/cosign/keys.go
- pkg/signature/keys.go
This allows API consumers to omit providing a password.
None
```release-note
Allow `PassFunc` to be `nil`, which translates to having no password at all.
```
> Allow `PassFunc` to be `nil`

- DEPRECATIONS.md
- FEATURES.md
Adding these in preparation for GA. I'm not sure if we have features we're in the process of deprecating, but I can add them in if we do!
These follow the policy described [here](https://docs.sigstore.dev/api-stability).
Ref https://github.com/sigstore/sigstore-website/issues/119
> Add docs on API stability and deprecation table

- .github/workflows/validate-release.yml
- release/cloudbuild.yaml
- update cross-build image which adds goimports
n/a
```release-note
update cross-build image which adds goimports
```
> update cross-build image which adds goimports

- cmd/cosign/cli/clean.go
- cmd/cosign/cli/options/clean.go
- doc/cosign_clean.md
- test/e2e_test.go
To let people specify which tag type they want to delete from an image, .sig or .att or both.
Fixes #1425 
```release-note
feat: enhance clean cmd capability
```
> feat: enhance clean cmd capability

- pkg/cosign/git/github/github.go
Updates the printed info shown when using `generate-keypair` for Github and Gitlab providers.
Fixes N.A.
```release-note
Improve generate-keypair info printing
```
> Improve log lines to match with implementation

- cmd/fig/fig.go
- go.mod
- go.sum
will generate autocompletion typescript code of cosign for fig
Fixes #1359 
```release-note
feat: fig autocomplete feature
```
> feat: fig autocomplete feature

- .github/workflows/validate-release.yml
- release/cloudbuild.yaml
- update cross-build to use go 1.17.7
n/a
```release-note
update cross-build to use go 1.17.7
```
> update cross-build to use go 1.17.7

- cmd/cosign/cli/fulcio/fulcioroots/fulcioroots.go
- cmd/cosign/cli/fulcio/fulcioroots/fulcioroots_test.go
- cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go
- pkg/cosign/tlog.go
- pkg/cosign/tuf/client.go
- pkg/cosign/tuf/client_test.go
- pkg/cosign/tuf/status_type.go
- pkg/cosign/tuf/status_type_test.go
- pkg/cosign/tuf/usage_type.go
- pkg/cosign/tuf/usage_type_test.go
Continuing #1273, this adds support for fetching a list of TUF targets by custom metadata. This will be used for verification using expired/rotated targets. All targets will be persisted in the TUF target metadata. Only one will be marked as `active` while the others are marked as `expired`.
The custom metadata on a target looks like looks like:
```
"fulcio.crt.pem": {
"custom": {
"sigstore": {
"status": "Active",
"usage": "Fulcio"
}
},
"hashes": {
"sha512": "f2e33a6dc208cee1f51d33bbea675ab0f0ced269617497985f9a0680689ee7073e4b6f8fef64c91bda590d30c129b3070dddce824c05bc165ac9802f0705cab6"
},
"length": 740
},
```
Possible statuses are `active` or `expired`, and possible usages are `fulcio`, `rekor`, and `ctfe`. `unknown` is also supported for each as a default value.
To test this, I:
* Used …
> Fetch verification targets by TUF custom metadata

- cmd/cosign/cli/sign/sign_blob.go
- cmd/cosign/cli/signblob.go
- test/e2e_test.go
In `SignCmd` we do not pass a context any more but use the timeout from
the root options. This is now done in `SignBlobCmd` too.
None
```release-note
None
```
> Streamline `SignBlobCmd` API with `SignCmd`

- Makefile
- release/cloudbuild.yaml
After advise from @cpanato , updated the existing cloud build to generate a yaml artifact for the cosigned webhook instead of the standalone github action. This ensure that the image is built the same way as other artifacts.
This makes #1436 obsolete.
Fixes
#1414
```release-note
NONE
```
> convert release cosigned to also generate yaml artifact.

- config/500-webhook-configuration.yaml
This is taking longer than 10s sometimes now, breaking CI.
Matt did some debugging and found it's because the distroless image we use here
has accumulated so many signatures that it takes a long time to fetch them all.
Fixes
```release-note
```
> Bump webhook timeout.

- cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go
- cmd/cosign/cli/verify/verify_blob.go
- pkg/cosign/tlog.go
- pkg/cosign/verify.go
This adds console messages when the TUF metadata
used for Rekor or the CTFE key is marked as expired.
I haven't added a log message for Fulcio yet. The way
that certificates are verified is different. Instead of
multiple verifications where we can easily determine
which key successfully verified an object, the x509
library uses a CertPool and returns a valid chain.
I'll need to plumb through the TUF information.
Fixes
```release-note
Added information when old TUF targets are used to verify signatures
```
> Print message when verifying with old TUF targets

- test/e2e_test.sh
- test/e2e_test_cosigned.sh
- test/e2e_test_insecure_registry.sh
- test/e2e_test_secrets.sh
This uses `bash` from the user's `$PATH`, which is (usually) preferable to hardcoding a particular `bash` location: https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my
Selfishly, without this change these scripts don't work on NixOS.
Fixes N/A
```release-note
NONE
```
> tests: `/bin/bash` -> `/usr/bin/env bash`

- release/release.mk
Increase the goreleaser timeout from 30m (default) to 60m.
Fixes (hopefully) #1471
Fixes
```release-note
NONE
```
> Double goreleaser timeout

- .github/workflows/validate-release.yml
- .goreleaser.yml
- release/cloudbuild.yaml
- release/release.mk
In the PR https://github.com/sigstore/cosign/pull/1453 we added the YAML for cosigned, but that is not pushed to the GitHub release because it out of scope for Goreleaser and run outside
This PR joins the image generation using `ko` inside the Goreleaser job and runs as before hook and in the end, it pushed the YAML for cosigned to the release.
Rehersal: https://github.com/cpanato/cosign/releases/tag/v99.99.01
image:
```
$ cosign verify gcr.io/cpanato-general/cosign:v99.99.01
Verification for gcr.io/cpanato-general/cosign:v99.99.01 --
- Existence of the claims in the transparency log was verified offline …
```
> refactor release cloudbuild job

- cmd/cosign/cli/options/attach.go
- doc/cosign_attach_attestation.md
Super small wording correction... In `cosign attach attestation --attestation <path>`, the path should be to a file with the entire attestation envelope, not the predicate.
> Fix wording on attach attestation help

- CHANGELOG.md
- add initial changelog for 1.5.2
n/a
```release-note
NONE
```
> add initial changelog for 1.5.2

- cmd/cosign/cli/verify/verify.go
- cmd/cosign/cli/verify/verify_attestation.go
- pkg/cosign/verify.go
- pkg/cosign/verify_test.go
- pkg/sget/sget.go
- test/e2e_test.go
Cherry picks
#[GHSA-ccxc-vr6p-4858](https://github.com/sigstore/cosign/security/advisories/GHSA-ccxc-vr6p-4858)
#1484
> Cherry pick vulnerability PRs to release-1.5

- Makefile
use new features in ko v0.10.0
cc: @imjasonh 
Fixes
```release-note
chore(makefile): use kocache, convert publish to build
```
> chore(makefile): use kocache, convert publish to build

- cmd/cosign/cli/copy/copy.go
Fixes #700
add sbom and attestation copying support to copy cmd
Fixes
```release-note
feat: support other types in copy cmd
```
> feat: support other types in copy cmd
